qutip/qip/models/circuitprocessor.py
=> fixed np namespace bug, removed unused imports

qutip/cy/codegen.py, qutip/entropy.py, qutip/ipynbtools.py, qutip/steadystate.py
Only code formatting changes in the generated cython code.
=> generate tidier cython code, for easier debugging

qutip/bloch.py, qutip/control/setup.py, qutip/cy/setup.py
Simply setting compiler flags and add link-time optimizations.
=> ENH: Simplify Compiler flags

qutip/bloch.py
=> FIX: Issue with repeated saving of Bloch sphere.

qutip/states.py, qutip/tests/test_states.py
This fixes issue [#305] (linkhttps://github.com/qutip/qutip/issues/305)
=> Fixed a bug that resulted in unormalized T_0 triplet state

qutip/control/setup.py, qutip/cy/setup.py
-This should not affect much of anything on x86 systems, and has no
effect on x64.
-Removes incompatibility with ARM systems.
=> Remove call to fpmath

qutip/cy/sparse_utils.pyx, qutip/graph.py, qutip/tests/test_graph.py
Column permutation that sorts columns of a sparse matrix in ascending order according to the number of nonzeros in each column.  Sometimes useful for reducing fill-in in LU factors.
=> ADDED: column_permutation

qutip/fileio.py
=> Fix for qload decoding error

qutip/tests/test_fileio.py
Check if qsave and qload work as expected
=> Add test for qsave/qload

qutip/control/loadparams.py
This allows parameter file values to use numpy functions
e.g. np.sqrt(2) etc
=> numpy as np imported in loadparams

qutip/steadystate.py, qutip/tests/test_steadystate.py
- Add profile output in debug.
- Add ability to use wbm.
- Remove rounding of BRF.
=> Updates to SS power method

qutip/correlation.py
For details, please see http://nbviewer.ipython.org/gist/jfeist/bdcb43f1abcf05292a3a.
(also fixes a typo in one FutureWarning)
=> fix a bug in _spectrum_es calculation

qutip/fortran/mcsolve_f90.py
Corrected output states mismatch for ntraj=1
=> Fixes for mcsolve_f90

qutip/control/pulsegen.py, qutip/control/pulseoptim.py
A few very minor fixes
Details in commit messages
=> Qtrl crab bug fix1

qutip/qip/circuit.py
=> Some changes and additions in qip.circuit

qutip/__init__.py, setup.py
=> Misc issues

qutip/steadystate.py
- Made output dict uniform over solvers.
=> WIP: SS updates

qutip/qip/algorithms/qft.py
added the __all__ statement to the qft module.
=> Minor edits to match the qutip standard

qutip/qip/gates.py, qutip/tests/test_gates.py
This PR introduces a new generator function, qubit_clifford_group, that yields each member of the single-qubit Clifford group as a Qobj. This functionality should be useful in contexts such as quantum error correction and randomized benchmarking.
=> Single-qubit Clifford group

qutip/__init__.py
=> Give better warning message when $HOME not defined

qutip/control/dynamics.py, qutip/control/fidcomp.py, qutip/control/loadparams.py, qutip/control/optimconfig.py, qutip/control/optimizer.py, qutip/control/optimresult.py, qutip/control/propcomp.py, qutip/control/pulsegen.py, qutip/control/pulseoptim.py, qutip/control/termcond.py, qutip/control/tslotcomp.py, qutip/stochastic.py, qutip/tests/Hadamard_params.ini, qutip/tests/test_control_pulseoptim.py
Units tests added for the qutip.control modules
Tests based on the notebook examples
Some other small fixes applied to issues found during the testing.
=> Qtrl unit tests

qutip/ipynbtools.py
The call to Client in ipython parallel has moved modules in V4.
=> Fix ipynb parallel

qutip/control/dynamics.py
typo in dynamics.Dynamics.onto_evo_target fixed
=> Fix for Qtrl Qobj integration

qutip/matplotlib_utilities.py
A simple line plot is produced that illustrates clearly that the pulse is piecewise constant in the timeslots
A standard Matplotlib line plot suggests that the amplitudes vary linearly throughout the timeslot, which is not the case
=> Function for plotting control pulses added to matplotlib_utilities

qutip/control/dynamics.py, qutip/tests/test_control_pulseoptim.py
The dimensions of the evolution operator were incorrect when attempting state-to-state transfer control
This fixes the problem
=> Qtrl fix evo dims

qutip/random_objects.py, qutip/tests/test_rand.py
- Added random stochastic operators.
- rand_herm and rand_dm can be passed an array of eigenvalues that will be the eigenvalues of the resulting random operators. This is done via complex Jacobi rotations, but is really only suitable for operators with dimensionality <~=1000.
- Added unit tests.
=> Rand updates

qutip/qobj.py, qutip/tests/test_basis_transformation.py
A collection of updates at do the following:
- Restore ability to set Q.isherm, Q.type, and Q.superrep explicitly.
- Q.transform now works properly for arrays directly from sp_eigs (or eig).
- Q.groundstate now checks for degenercy.
=> Qobj updates

qutip/cy/graph_utils.pyx, qutip/graph.py, qutip/states.py, qutip/steadystate.py, qutip/subsystem_apply.py, qutip/tests/test_subsys_apply.py, qutip/wigner.py
All deprecation warnings issued by numpy during the tests have now been fixed, resolving #381 
The motivation was to try and make it more clear when and why issue #430 arises
=> Fix integer deprec warnings

qutip/cy/graph_utils.pyx, qutip/graph.py, qutip/states.py, qutip/steadystate.py, qutip/subsystem_apply.py, qutip/tests/test_subsys_apply.py, qutip/wigner.py
Some of the norms calculated in the test_ComplexSuperApply were above the tolerance of 1e-12
In 50 repeated tests 7 errors occurred. norms as large as 5e-11 were reported.
After increasing tol to 1e-10 test were repeated 200 times and no errors occurred
=> Increase subsys test tolerance

qutip/tests/test_dimensions.py, qutip/tests/test_gates.py, qutip/tests/test_random.py, qutip/tests/test_steadystate.py, qutip/tests/test_superop_reps.py, qutip/tests/test_tensor.py
- Removed yield commands as they output to the console.
- Removed the lgmres steady state tests since this will be removed.
- Fixed test name going over 80 chars.
=> Test updates

qutip/mcsolve.py
random_integers has been depreciated in favor of randint.
=> Mcsolve deprec fix

qutip/cy/sparse_utils.pyx, qutip/sparse.py
This is added in response to my comments on the issue of expm (#462). This might also be useful elsewhere.
=> ENH: Fast checking for diagonal sparse matrix

qutip/qobj.py, qutip/sparse.py, qutip/tests/test_qobj.py
Updated expm function.  Fixes bug in previous version.  Defaults to sparse=False as resulting matrix is almost always dense, and the algorithm runs about 10x faster.
=> FIXED: Expm

qutip/sparse.py
The new version of expm that I grabbed from Expokit does not behave quite as well as the SciPy version.  After a bit of testing, the SciPy version performs the best overall.  For our purposes, I think that either method would be sufficient.  However, the SciPy version is the current best algorithm, and replacing as much code as possible with SciPy code is probably a good thing.
This code still defaults to the dense method.
=> ENH: Move to SciPy expm

qutip/random_objects.py, qutip/wigner.py
- Fix neg only real parts in rand_ket.
- Made 'clenshaw' default method in Wigner.
=> Minor fixes

qutip/operators.py
Removed hard coding of isherm.  Fixes #482.
=> FIXED: Spin operator isherm

qutip/control/dump.py, qutip/control/dynamics.py, qutip/control/io.py, qutip/control/optimconfig.py, qutip/control/optimizer.py, qutip/control/pulseoptim.py, qutip/control/tslotcomp.py, qutip/mesolve.py, qutip/operators.py, qutip/sesolve.py, qutip/tests/test_control_pulseoptim.py, qutip/tests/test_mesolve.py, qutip/tests/test_metrics.py
Unitarity checking added for propagators of time evolution
dumping of transient calculation operators added
generation of summaries for pulse optimisation iterations and system evolution computations added
=> Qtrl data check and dump

qutip/mcsolve.py
Wrong sign in summation of Hamiltonian terms caused Issue #490
=> Quick fix for Issue #490

qutip/tests/test_mcsolve.py
=> #490 unittest

qutip/propagator.py, qutip/tests/test_propagator.py
- Propagator can now be run in parallel.
- Simplified dissipative calling by unifying 'sparse' and dense calls when dissipative.
- Added propagator unit tests.
=> Updates to propagator

qutip/control/dynamics.py, qutip/control/pulseoptim.py, qutip/tests/test_control_pulseoptim.py
A few people have been asking for this again recently. 
I have produced this new PR, rather than apply #396, as its a bit simpler and more flexible. It is a bit more memory consumptive, but probably a small percentage of the whole. It's also based an recent pull. 
No notebook as yet, as I will wait for feedback from those who requested it.
=> Control -  time dependent drift

setup.py
Reverts qutip/qutip#518. This has been causing some issues when being downloaded directly from git. Will rework it.
=> Revert "ENH: PEP440 versioning fix"

qutip/cy/codegen.py
- Replaced csr_spmv & for-loop at end with spmvpy calls.
- Removed codegen steps that are no longer needed.
=> ENH: Simplified & optimized mcsolve codegen

qutip/permute.py, qutip/tests/test_qobj.py
A bug is fixed in Qobj permute and bra vector tests are added.
The bug is found by a student of mine Slava Kuzmin (IQOQI).
=> Bugfix in bra vector permute

qutip/countstat.py, qutip/steadystate.py, qutip/tests/test_countstat.py
This is my first attempt at fixing and slightly extending the functionality of the countstat_current_noise()
function in countstat.py.   There were several issues with this function, which I have attempted to rectify as described below.  Also its my first pull request (instead of asking anubhav or alex to help), so if I messed it up let me know.
1) The default method, a direct solution using sparse matrices, would fail with an "exactly singular" error on small examples (like the well studied single-resonant level or double quantum dot examples).  The other sparse methods also suffered from the same issue, as did the 'direct' method for dense solutions.
The latter, the dense matrices solver, I have fixed by capturing the error using lstsq() if np.linalg.solve() fails.
For the sparse cases …
=> Fixes to countstat and pseudo-inverse functions

qutip/cy/sparse_utils.pyx, qutip/propagator.py, qutip/sesolve.py, qutip/solver.py, qutip/tests/test_propagator.py
- Solve for all basis vectors in unitary propagator simultaneously.
- Use this method as default.
=> ENH: Batch solve unitary propagator

qutip/utilities.py
Fix for Issue #552 by checking if 'libraries' is in the dict keys.
=> BUG: _blas_info fix (Issue #552)

qutip/control/dynamics.py, qutip/tests/test_control_pulseoptim.py
Bug fixed where using tau array cause self referential loop
=> Fix for control pulseoption tau array for timeslots

qutip/__init__.py
- The current choice of CFLAGS made generating the str-based c-code slower than necessary for little to no speed gain.  Here we choose flags that optimize less since there is no benefit.
=> ENH: CFLAGS updates

qutip/operators.py
=> Revert "Fix redundancy and sign error in jmat."

qutip/cy/sparse_utils.pyx
Removed some unnecessary calls back to Python.
=> ENH: Optimized cython for sparse_utils

MANIFEST.in, setup.py
manifest for sdist added
version bumped to 4.0.1
=> setup dist changes

qutip/qip/gates.py
The documentation for controlled phase gate did not mention the word 'controlled'
=> Corrected typo in documentation

MANIFEST.in, qutip/control/loadparams.py, qutip/tests/test_control_pulseoptim.py
This is more of a guess at a fix for #598 as I am not able to replicate
but seems there is a good chance it will work
=> str cast params filename

MANIFEST.in, qutip/tests/test_control_pulseoptim.py
All pulseoptim tests now passing on Windows
=> Qtrl increase test tol

MANIFEST.in, qutip/correlation.py
All rhs*.pyx files now deleted
=> Correlation td tidy up

MANIFEST.in, setup.py
=> Setup updates

qutip/qip/circuit.py, qutip/tests/test_qubitcircuit.py
This is in ref to #610. I have also cleaned up some pep8 and added a test for `add_gate`. This is now ready for review. @ajgpitch
=> Add gate object directly with QubitCircuit.add_gate(gate)

qutip/propagator.py
Adds lines to remove .pyx files hanging around after calls to propagator, and fixes a few pep8 issues
=> Bugfix #643

qutip/__init__.py, setup.py
src directories added to packages
cpp and hpp files included in package_data
=> C++ headers included in package_data

setup.py
Applying fix from #660 to the release branch
=> Patch4.1 graph utils xcode compile

qutip/__init__.py, qutip/utilities.py
applying  qutip/qutip#668 to this release branch
=> Update4.1 handle num cpus

qutip/bloch_redfield.py, qutip/cy/br_codegen.py, qutip/tests/test_brmesolve_td.py
Also added to the doc-string as to how to input the split-operator format.
=> ENH: Allow for Cubic_Splines as split td-aop terms

qutip/bloch_redfield.py, qutip/tests/test_brmesolve_td.py
=> BUG: Multiple split BR a_ops not indexed correctly.

qutip/rcsolve.py
Now imports the correct Options class. 
Probably need a good unittest for this @nwlambert.
=> BUG: rcsolve imported old Odeoptions

qutip/solver.py, qutip/tests/test_rhs_reuse.py
This Pull attempts to fix the issues with Win not finding RHS functions when repeated time-dependent solvers are used in the tests.  I have also added some unit tests to verify that rhs_reuse still works.
=> BUG: Fix strange RHS file error on Win

qutip/cy/graph_utils.pyx, qutip/cy/heom.pyx, qutip/cy/interpolate.pyx, qutip/cy/openmp/br_omp.pxd, qutip/cy/openmp/parfuncs.pxd, qutip/cy/openmp/parfuncs.pyx, qutip/cy/parameters.pxi, qutip/cy/ptrace.pyx, qutip/cy/sparse_utils.pyx, qutip/cy/spconvert.pyx, qutip/cy/spmatfuncs.pxd, qutip/cy/spmatfuncs.pyx, qutip/cy/spmath.pyx, qutip/cy/stochastic.pyx, qutip/cy/testing.pyx
Cython 0.26 changed a few internal items, and was causing come issues with our builds.  This should alleviate those problems.
=> Fixes for Cython 0.26

qutip/cy/graph_utils.pyx, qutip/cy/heom.pyx, qutip/cy/interpolate.pyx, qutip/cy/openmp/br_omp.pxd, qutip/cy/openmp/parfuncs.pxd, qutip/cy/openmp/parfuncs.pyx, qutip/cy/parameters.pxi, qutip/cy/ptrace.pyx, qutip/cy/sparse_utils.pyx, qutip/cy/spconvert.pyx, qutip/cy/spmatfuncs.pxd, qutip/cy/spmatfuncs.pyx, qutip/cy/spmath.pyx, qutip/cy/stochastic.pyx, qutip/cy/testing.pyx, qutip/qobj.py, qutip/rcsolve.py, qutip/solver.py, qutip/tests/test_brmesolve_td.py, qutip/tests/test_rhs_reuse.py, qutip/wigner.py, setup.py
Added changes from master for new release
=> 4.2 release ready

qutip/_mkl/spsolve.py, qutip/steadystate.py
The spsolve in our MKL module was passing an array for the dict key, rather than the str value that is needed.
=> BUG: MKL error checking dict key error

qutip/visualization.py
Make the useful function even better
=> ENH: 'clenshaw' method by default for plot_wigner

qutip/correlation.py
=> BUG: args not being passed to coherence_function_g2

MANIFEST.in, setup.py
This will include the README, LICENSE and requirements files
=> release 4.2 MANIFEST added

MANIFEST.in, qutip/__init__.py, setup.py
Files from root drive of project could only be added via manifest
=> Add readme etc via manifest

setup.py
PyPi release done. Bump 4.2.0 to 4.2.1. @ajgpitch
=> bump to 4.2.1

qutip/control/optimizer.py, qutip/control/optimresult.py
It is the full evolution based on the initial pulse
It is set when the optimisation starts
=> New attribute evo_full_initial added to OptimResult

qutip/control/symplectic.py
clarity and numpydoc compliance.
=> calc_omega comments updated

qutip/cy/spmatfuncs.pyx, qutip/expect.py, qutip/tests/test_expect.py
This is a pure sparse based method for doing expectation values with kets.  About 10x+ faster than previous version.
=> ENH: Faster ket expectation values

qutip/cy/spmath.pyx, qutip/qobj.py
Much faster trace on smaller Qobj's.
=> ENH: Faster Qobj trace

qutip/cy/spmath.pyx, qutip/qobj.py, qutip/tests/test_qobj.py, qutip/tests/test_sp_eigs.py
Faster routine to compute inner products.  About 30x faster than previous versions.
=> ENH: ~30x faster Q.overlap() [inner product]

qutip/qip/circuit.py
=> fix the latex code for Toffoli gate in Quantum Circuits

qutip/qobj.py
Fix for Issue #769.
Allows for computing dims internally is user wants `type='super'` when building Qobj from scratch.
=> BUG: Fix for Issue #769

qutip/cy/spmath.pyx, qutip/tests/test_spmath.py
Also added more isherm testing.
=> ENH: Clean up zcsr_isherm a bit

qutip/entropy.py, qutip/partial_transpose.py
partial_transpose doesn't work properly if mask is boolean array instead of integer array.
=> BUG: Fix partial_transpose

qutip/propagator.py, qutip/solver.py
=> BUG: Propagator missing safety_check call

qutip/visualization.py
Because not everyone uses angular frequencies.  Should resolve Issue #782.
=> BUG: Remove 2pi rescaling of eigenenergies

qutip/nonmarkov/heom.py
This was raised by @nwlambert and the code change fixes the issue of setting appropriate dimensions while constructing the RHS when the system is a tensor product. This is a fix for the issue: https://github.com/qutip/qutip/issues/794
=> Fixes #794: Changed dimensions for allowing tensor product of states

qutip/sesolve.py
Just fixes a small inconsistency.
=> ENH: Make sesolve progress_bar kwarg function like mesolve version.

qutip/propagator.py
Fixes hard coded options in propagator 'batch' mode, Issue #807.
=> BUG: Fix issue #807

setup.py
Hi,
I noticed that the current message regarding the citations gets lost in the end of the build messages and warnings. A small modification to make the message stand out. @ajgpitch
=> Better citation message

qutip/sesolve.py
rho0 arguments replaced with psi0
references to density matrices removed
Just to avoid any confusion. No functional changes
=> sesolve - rho0 replaced with psi0

qutip/operators.py, qutip/qobj.py, qutip/tests/test_qobj.py
add isunitary attribute for checking if qobj is a unitary operator:
unitary checking func and property funcs added
initialisation of isunitary
clear flag on operations that risk unitarity
qobj unitarity testing added
preset isunitary for qeye
=> qobj isunitary attrib

qutip/steadystate.py, qutip/stochastic.py, qutip/tests/test_steadystate.py
Hopefully this will fix #862 
Unfortunately 'legacy' did not behave as scipy 0.x. Some tests still failed. I had to add facility to set much higher tol on the gmres method.
The missing kwarg is handled. So should work for scipy < 1.1
=> Fix for iterative lu solve atol keyword issues

.travis.yml, qutip/semidefinite.py
cvxpy Variable and Parameter dims passed as tuple
cvxpy and its depends only installed in tests for NOMKL builds
Extra test added for NOMKL with OPENMP
=> fix - semidefinite cvxpy Variable and Parameter

.travis.yml
The .travis.yml file in the merged changes at https://github.com/qutip/qutip/pull/873 was failing. This PR will attempt to fix this starting from the previous working version of Travis
=> Travis CI tests update - NOMKL+OPENMP, cvx NOMKL only

.travis.yml
blas=*=mkl for Intel MKL
blas=*openblas for openblas
=> Travis CI tests - Specify blas type in conda env create

.travis.yml
Not installing cvxpy will do this.
This is to deal with #880
=> Ignore dnorm tests

qutip/states.py
The final one of my old fixes rebased and renamed by request.
solves issue #820
=> Fix ENR fock dims

setup.py
We are making a 4.3 release so that master is bumped to 4.4 now. @ajgpitch
=> Bumped master to 4.4

setup.py
It is about time that we made the 4.3 release, @ajgpitch @nonhermitian. Could you please check and merge this? I will build the 4.3 dist and the documentation and then update pip and the conda-forge version. We have the new scattering module and PIQS in this version.
=> 4.3 release

MANIFEST.in, setup.py
Bumping micro after pypi release.
=> Bump to 4.3.1

MANIFEST.in, setup.py
Adding all the other necessary files.
=> Qutip 4.3.x

qutip/cy/pyxbuilder.py, setup.py
This fixes installations on OSX 10.14
fixes #919
=> Fix for installing on OSX 10.14

.travis.yml
This updates the Travis build process.  It is for Py3 only.
=> Update Travis build process

qutip/control/dynamics.py, qutip/eseries.py, qutip/qobj.py, qutip/tests/test_piqs.py
Added the __array__ method to Qobj so that np.array(Qobj) return the array.
Asked in issue 937
=> __array__ for Qobj

qutip/cy/br_codegen.py, qutip/cy/codegen.py, qutip/cy/math.pxd, qutip/cy/math.pyx
Addresses issues in the help group.
=> Add complex erf Cython function 'zerf'

qutip/stochastic.py
=> fix the integer overflow when calling np.random.randint

setup.py
Issue #905 and #892
Numpy Requirements updated to 1.12 from 1.8 and Optional Dependency for Matplotlib added.
MacOS test is failing as mentioned in #963
=> Issue #905 and #892

qutip/tests/test_wigner.py, qutip/visualization.py, qutip/wigner.py
... sphere functionality. See wigner_visualization notebook in examples for details.
=> Added calculating the wigner distribution and plotting it on the Bloch

qutip/distributions.py, qutip/fastsparse.py, qutip/nonmarkov/heom.py, qutip/orbital.py, qutip/tests/test_gates.py, qutip/utilities.py, requirements.txt, setup.py
Update to account for moved function in scipy 1.3.
This increase the minimum requirement to scipy 1.0
=> Update sp 1.3

qutip/qip/circuit.py
=> Typo In Specifying the datatype is fixed

.codeclimate.yml, README.md
Will take some trial and error to make this useful but has some interesting stats.
=> codeclimat config

qutip/cy/cqobjevo.pxd, qutip/cy/cqobjevo.pyx, qutip/cy/cqobjevo_factor.pxd, qutip/cy/cqobjevo_factor.pyx, qutip/cy/mcsolve.pyx, qutip/cy/openmp/cqobjevo_omp.pyx, qutip/cy/stochastic.pyx, qutip/floquet.py, qutip/mcsolve.py, qutip/propagator.py, qutip/qobjevo.py, qutip/qobjevo_codegen.py, qutip/solver.py, qutip/stochastic.py, qutip/superoperator.py, qutip/tests/test_qobjevo.py, setup.py
Rewrote, cythonized and simplified `mcsolve`.
`mcsolve` implementation based on `qobjevo`.
It is now class based with the general structure I would propose for solvers.
It has (experimental, hidden for now) support for diagonalized evolution.
Collapse history can be obtained by the Hamiltonian.
Otherwise the same algorithm than the previous version.
Between #990 and #969
=> Qoe mcsolve

qutip/cy/cqobjevo.pxd, qutip/cy/cqobjevo.pyx, qutip/cy/cqobjevo_factor.pxd, qutip/cy/cqobjevo_factor.pyx, qutip/cy/mcsolve.pyx, qutip/cy/openmp/cqobjevo_omp.pyx, qutip/cy/stochastic.pyx, qutip/floquet.py, qutip/mcsolve.py, qutip/mesolve.py, qutip/propagator.py, qutip/qip/circuit.py, qutip/qip/models/circuitprocessor.py, qutip/qobjevo.py, qutip/qobjevo_codegen.py, qutip/rhs_generate.py, qutip/sesolve.py, qutip/solver.py, qutip/stochastic.py, qutip/superoperator.py, qutip/tests/test_qobjevo.py, qutip/tests/test_rhs_reuse.py, setup.py
Updating the qip_opt branch with the master as base.
=> Updating qip_opt

qutip/cy/openmp/cqobjevo_omp.pyx
Removed the unsigned int in the openmp loop mentioned in #955
=> removed usingned int in prange

qutip/cy/spconvert.pyx, qutip/cy/stochastic.pyx, qutip/mcsolve.py, qutip/mesolve.py, qutip/sesolve.py, qutip/solver.py
Faster output for each runs states.  Issue #1023.
=> faster mcsolve postprocessing

.travis.yml, MANIFEST.in, qutip/about.py, qutip/cy/mcsolve.pyx, qutip/floquet.py, qutip/tests/test_metrics.py, setup.py
Update master with the official version 4.4
=> Qutip 4.4.x release ready

qutip/cy/inter.pyx
QobjEvo array coefficients needed to start from 0. 
Made it to be able to start from anywhere.
=> QobjEvo do not need to start from 0 anymore

qutip/qobjevo.py, qutip/tests/test_qobjevo.py
Should fix the issue #1039 
Added matching automated test.
=> picking bug on windows

qutip/mesolve.py, qutip/sesolve.py
=> Remove mutable default values in mesolve/sesolve

qutip/qobjevo.py
@Ericgig I made two small change for constant `QobjEvo`:
1. ``QobjEvo=([Qobj, Qobj, ...])`` gives the correct type
2. Addition of two constant QobjEvo gives the correct type
=> Compatibility of constant QobjEvo

qutip/control/dynamics.py, qutip/control/fidcomp.py, qutip/control/loadparams.py, qutip/control/optimizer.py, qutip/control/propcomp.py, qutip/control/pulseoptim.py, qutip/control/tslotcomp.py
change `from qutip import Qobj` to `from qutip.qobj import Qobj`
=> Fix potential cyclic importation in the control module

qutip/qobjevo_codegen.py, qutip/sesolve.py
Add import of os in codegen
Remove prints in sesolve
=> core: sesolve and codegen little fixes

qutip/essolve.py
=> fix error checking for null matrix in essolve

qutip/__init__.py
Remove the error showing in  #1109
=> inverted test

qutip/about.py
Docstring change to the `qutip.about()` message.
=> Add previous lead devs to qt.cite

qutip/operators.py, qutip/states.py, qutip/tests/test_basis_transformation.py
Removed code that raised warning with scipy 1.4
=> Update for scipy 1.4

qutip/tests/test_basis_transformation.py, qutip/tests/test_brmesolve.py, qutip/tests/test_brmesolve_td.py, qutip/tests/test_brtools.py
To get more familiar with bits of the internals, I'm going through and migrating the tests to `pytest`.  While I'm at it, I'm also fixing PEP8 issues in the testing files, since CodeClimate will moan at me if I don't.
I'm basically learning how to use `pytest` and how to code as part of an organisation as I go, so please feel free to correct me if I'm doing something wrong.
I'll leave this PR as in draft mode until I've made it through more of the testing files.
=> Move tests to pytest

qutip/qobjevo_codegen.py, setup.py
Adding a commit that should fix tests in 4.5.1.
=> Patch4.5 fix1169

qutip/about.py, setup.py
@nathanshammah please can you merge this and redo the sdist after before making the 4.5.1 release.
Thanks
Alex
=> Boxi Li added to authors and admins

qutip/wigner.py
This will resolve #1128.
I've allowed the `spin_q_function` (Husimi function) and the `spin_wigner` functions to handle half-integer spin values.
I've also improved the docstrings.
=> Fix spin husimi/wigner functions

.github/pull_request_template.md
Add a suggestion for tests in the PR template.
Improve #1198 
**Changelog**
Add a suggestion for tests, documentation and notebook in the PR template.
=> Add a suggestion for tests in the PR template

qutip/tests/test_utilities.py
Merged the PR about non-int clebsch wihtout waiting for a test. Add one here
=> Add test for half integer for clebsch

.travis.yml, qutip/parallel.py, qutip/tests/test_mcsolve.py
Moved the openmp, mkl, no cython tests to python 3.8
Also added (temporaly?) a mac test on python 3.8.
=> Udated tests to 3.8

qutip/qip/circuit.py
Refactor Qutip.Qip.Circuit.solve_gates as a dispatch-like method for assigning different functions and make the QubitCircuit module more commutable.
These changes make it easier for maintenance and provide a clearer workflow.
**Changelog**
Refactor Qutip.Qip.Circuit.solve_gates
=> Refactor solve gates

qutip/qip/circuit.py
1. `self.N` in `QubitCircuit` is not the number of gates but the number of qubits.
2. The error of index excesses number of gates was not captured.
3. `self.gates.remove(self.gates[self.N - i])` removes the first match but not the last.
=> fix function QubitCircuit.remove_gate

.github/pull_request_template.md, README.md
**Checklist**
Describe here the proposed change.
Please mention the related issues or PRs here. If the PR fixes an issue, use the keyword fix/fixes/fixed followed by the issue id, e.g. fix #1184
**Changelog**
Give a short description of the …
=> Changing of qutip_dev_contrib.md to CONTRIBUTING.md as issue 111  in qutip/qutip-doc

qutip/tests/test_control_pulseoptim.py, qutip/tests/test_correlation.py, qutip/tests/test_countstat.py, qutip/tests/test_enr_state_operator.py, qutip/tests/test_entropy.py, qutip/tests/test_fileio.py, qutip/tests/test_floquet.py, qutip/tests/test_heom_solver.py
These are all the remaining files from #1181 that neither Eric nor Boxi had explicitly said they were checking, with the commits all tidied up and rebased onto `master`.
This is based on #1249, and that one needs to be merged first.
**Changelog**
Major test refactor into a pytest style.
=> Convert tests to pytest (assorted)

qutip/tests/conftest.py, qutip/tests/pytest.ini, qutip/tests/test_brmesolve.py, qutip/tests/test_brmesolve_td.py, qutip/tests/test_brtools.py, qutip/tests/test_cavityqed.py, qutip/tests/test_gates.py
These are the files that Boxi (@BoxiLi) was checking in #1181, but the commits are tidied up and rebased onto `master`.  The merge conflict in `test_gates.py` that's present in #1181 is fixed (with all the tests safely maintained).
This is based on #1249, and that one needs to be merged first.
**Changelog**
Major test refactor into a pytest style.
=> Convert tests to pytest (gates and cavityqed)

qutip/qip/compiler/cavityqedcompiler.py, qutip/qip/compiler/spinchaincompiler.py, qutip/qip/device/cavityqed.py, qutip/qip/device/modelprocessor.py, qutip/qip/device/processor.py, qutip/qip/device/spinchain.py, qutip/qip/pulse.py, qutip/tests/test_processor.py
- Improve the documentation and use more understandable variable names.
- Add mcsolve as an optional solver for `Processor`
- The figure plotted by ``Processor.plot_pulse`` now has a better look
**Changelog**
A few updates to the device simulator
=> Updates for the device simulator: fixing bugs, better doc and visual demo

qutip/fastsparse.py, qutip/legacy/ptrace.py
Scipy 1.5 changed the methods of performing the matrix multiplication to
avoid copying the `indptr` matrix multiple times.  This is actually not an
issue at all for us, because we only allow int32 indices (so if the
indices were to upcast, we just throw and exception), but the underlying
private Cython call structure also changed, and our `fast_csr_matrix` was
a direct clone.
We add try/catch blocks to switch on the correct types (the overhead
from a failed lookup is trivial compared to the matrix multiplication
time), because we have to support more than just the most recent version
of scipy.  We could look up the version of scipy installed, but the
"try it and see" approach is more typical Python.
This problem should be eliminated by the move to the new data types, as
we will stop …
=> Support scipy >= 1.5 in fast_csr_matrix matmul and legacy.ptrace

qutip/lattice.py
Add the PR from @BoxiLi 's Lattice bug on windows.
@jakelishman's #1312 is not be added since the tests upgrade to pytest are not in the release. (yet?)
apply #1313  to 4.5.2
=> add 1313 to 4.5.2

MANIFEST.in
Tell setup to include `pyproject.toml` in the distribution.
#1309 add to file.
=> add pyproject.toml to manifest

qutip/bloch.py
Description
Modification of PR #1315 .Added option to include colors to Bloch vectors and points instead of just cycling from a list
Related issues or PRs
fix #1292
Changelog
Added an optional argument called colors for the Bloch.add_vectors, Bloch.add_points and Bloch.add_states method.
Tested it here: https://github.com/rajathshetty20/misc/blob/master/qutip%20%231292.ipynb
=> added option for color in bloch.py

.coveragerc, .travis.yml
This is a completely equivalent PR to #1347, but applied to `dev.major`.  See the comments and discussion in that PR for more details.
Addresses #1339.
=> Fix test coverage on `dev.major`

qutip/dimensions.py, qutip/expect.py, qutip/floquet.py, qutip/metrics.py, qutip/operators.py, qutip/qip/circuit.py, qutip/qip/noise.py, qutip/qip/operations/gates.py, qutip/qip/pulse.py, qutip/states.py, qutip/tensor.py
This PR makes small changes to docstrings to work with doctest (and run doctests on docstrings when possible). This is corresponding with the [ipython_to_doctest](https://github.com/qutip/qutip-doc/pull/120) PR in qutip-doc. 
https://github.com/qutip/qutip-doc/pull/120
**Changelog**
fix docstrings for doctest
=> small changes to docstrings

qutip/core/data/convert.pyx
Minor change - just fixes a simplification I accidentally left in when writing the original function.
=> Fix the weight calculation in data.to

setup.py
Whitespace only, no major changes.
=> Fix whitespace in setup.py

.travis.yml
Duplicate of #1381 for `dev.major` - should fix the super broken tests.
=> Fix setting of Python version in .travis.yml

qutip/_mkl/spmv.py
**Checklist**
Fix one warning of #1389 , the others have already been fixed in the main branch.
Fixes #1389 
**Changelog**
Fix one installation warning.
=> MAINT: Fix one warning

qutip/bloch3d.py
Fix for an issue in Bloch3d when calling add_points
fix #1399 
**Changelog**
Fixed sorting of zipped list
=> Fix for Bloch3d.add_points() bug while sorting zipped arrays

qutip/_mkl/spmv.py, qutip/_mkl/utilities.py, qutip/bloch_redfield.py, qutip/cite.py, qutip/control/dynamics.py, qutip/control/fidcomp.py, qutip/control/tslotcomp.py, qutip/cy/pyxbuilder.py, qutip/mesolve.py, qutip/operators.py, qutip/pdpsolve.py, qutip/permute.py, qutip/piqs.py, qutip/qip/algorithms/qft.py, qutip/qip/circuit.py, qutip/qip/device/spinchain.py, qutip/qip/noise.py, qutip/qip/operations/__init__.py, qutip/qip/pulse.py, qutip/qobj.py, qutip/qobjevo.py, qutip/sparse.py
The unused import statements have been found via an automated code analysis.
=> Remove some unused imports

qutip/qip/circuit.py, qutip/qip/circuit_latex.py
Wrong plot 
Correct plot now
**Changelog**
Fix broken gate plotting
=> fix the circuit latex generation for measurement and swap gate

.travis.yml, README.md, pyproject.toml, qutip/_mkl/spmv.py, qutip/about.py, qutip/continuous_variables.py, qutip/control/dynamics.py, qutip/control/pulseoptim.py, qutip/eseries.py, qutip/essolve.py, qutip/lattice.py, qutip/operators.py, qutip/piqs.py, qutip/propagator.py, qutip/qip/circuit.py, qutip/qip/device/processor.py, qutip/qobj.py, qutip/random_objects.py, qutip/simdiag.py, qutip/states.py, qutip/tests/test_lattice.py, qutip/tests/test_piqs.py, qutip/tests/test_qubitcircuit.py, qutip/tests/test_three_level.py, qutip/three_level_atom.py, setup.py
Boxi and I decided to hold off on 4.6.0 until after the next admin meeting - it was too rushed to finish off all the features, and there are deprecations to be discussed.
This is a proposed patch release on the 4.5.X branch that purely adds the fixes for NumPy 1.20.  The base of this PR is the code state at 4.5.2, so this PR is a complete list of changes from 4.5.2 to 4.5.3.
=> QuTiP 4.5.3

qutip/mesolve.py, qutip/tests/test_mesolve.py
If the initial state was found to be of type 'oper', no further testing was done in initialisation of mesolve on the dimensions.  For example, if a user incorrectly created a density matrix, such as by doing
```python
tensor(basis(20, 0), qeye(20)/20)
```
(presumably intending `basis(20, 0).proj()` or similar), it would have a type of 'oper' inside Qobj, and mesolve would recognise it as a "proper" density matrix, even though the shape was actually incorrect.  Such an object would get passed down into the C layer, which does no shape checking, without having its shape explicitly tested, and eventually could cause a segfault in the matrix multiplication routine.
The correct check in this setup is to test the shapes when passed into `mesolve`, if this is possible.  If the …
=> Fix mesolve segfault with bad initial state

qutip/superoperator.py
Also for `operator_to_vector`, though this is harder to mis-use.  The documentation now spells out exactly what we expect, and we verify that we do have the correct inputs, rather than exploding with a misleading error message (at best) or silently doing something very unexpected (at worst).
Fix gh-1204.
=> Improve documentation of vector_to_operator

qutip/core/data/reshape.pyx
This was an incredibly minor optimisation that had a ~2% speedup in some cases on Linux/Mac, but was preventing the build in some configurations on Windows due to failed type conversions.
That's not a worthwhile trade-off for some functions that aren't even used that heavily in QuTiP code.
I'm now using `dev.major` QuTiP on a Windows machine in day-to-day life, so maybe I'll catch a few more problems with it.
=> Remove div_t usage

qutip/solve/pdpsolve.py
Fixed small typo in the documentation of `pdpsolve.py`
**Changelog**
Fixed small typo in the documentation of `pdpsolve.py`
=> [DOC] Fixed a ducumentation typo.

README.md, doc/conf.py, doc/frontmatter.rst, qutip/about.py, setup.cfg
Add Simon Cross to authors.
**Changelog**
Added Simon Cross to authors.
=> Add Simon Cross to authors.

README.md
Fixes #1552.
**Changelog**
Add a "Citing QuTiP" section to the README, containing a link to the QuTiP papers.
=> Add link to QuTiP papers.

doc/changelog.rst
=> Changelog update for v4.6.2

doc/frontmatter.rst
Added Pulser to the list of external libraries using QuTiP.
None.
=> Added Pulser to external libraries using QuTiP

doc/guide/dynamics/dynamics-floquet.rst, doc/guide/guide-bloch.rst, doc/guide/guide-control.rst, doc/guide/guide-correlation.rst, doc/guide/guide-measurement.rst, doc/guide/guide-parfor.rst, doc/guide/guide-states.rst, doc/guide/guide-tensor.rst
Describe here the proposed change.
Fixed typos and corrected grammar in docs.
None.
=> Fixed numerous typos in docs

qutip/core/data/mul.pyx
Fixes the neg_dense docstring in dev.major
**Changelog**
in neg_dense docstring
CSR matrix -> Dense matrix
=> fix_docstring_neg_dense

qutip/control/dynamics.py, qutip/core/data/kron.pyx, qutip/solve/countstat.py, qutip/tests/core/data/test_mathematics.py
Add `kron_dense` specialization to dispatch and test.
=> Add 'kron_dense' specialization

doc/installation.rst, requirements.txt
**Changelog**
Added packaging to the requirements in `installation.rst`.
Update requirements.txt with the information in setup.cfg.
=> Added packaging to the installation.rst requirements.

qutip/superop_reps.py
Fix typo in docstring of chi_to_choi.
* Fixes #1730
**Changelog**
Fix typo in docstring of chi_to_choi.
=> Fix typo in docstring of chi_to_choi.

.github/workflows/build.yml, pyproject.toml
Fix cibuildwheel issues introduced in #1747 and make any other necessary post PR clean ups.
- Follow on from #1747
**Changelog**
Fix cibuildwheel builds in CI.
=> Fix cibuildwheel builds.

qutip/utilities.py
Cherry-pick numpy 1.22 fix for develop branch
PR #1752
=> Handle change in configuration attributes for numpy 1.22.0

setup.cfg
Add project urls to linking to the source repository, issue tracker and documentation to setup.cfg. These appear in PyPI and other places, e.g.,
None.
**Changelog**
Add project urls to linking to the source repository, issue tracker and documentation to setup.cfg.
=> Add project urls to setup.cfg.

doc/guide/guide-basics.rst, doc/guide/guide-overview.rst, doc/guide/guide-states.rst
Clean up verbiage
1759
**Changelog**
Clean up verbiage and clarify language.
=> Guide basics2

.github/workflows/build.yml
Add building of wheels for Python 3.10 to the cibuildwheel job.
- None
**Changelog**
Add building of wheels for Python 3.10 to the cibuildwheel job.
=> Build wheels for Python 3.10.

doc/guide/dynamics/dynamics-time.rst
**Changelog**
Modified some grammar in `dynamic-time.rst` to make some sentences clear.
=> Minor grammatical tweaks to `dynamic-time.rst`

qutip/qobj.py, qutip/tests/test_qobj.py
As observed by @amitjansc, tidyup did not properly reacted to change to the default tolerance in settings.
Fix this and add tests.
Close #1829 
**Changelog**
Ensure `tidyup`'s default tolerance is read from settings at each call.
=> Fix tidyup not reacting to change in settings.

qutip/orbital.py, qutip/tests/test_orbital.py
The orbital function had some errors in it. Here, I replaced the manual calculation of the spherical harmonics, with the implementation provided by SciPy. Additionally, I provide some tests to the function.
fixes #1839 
**Changelog**
Fixed errors in orbital functions
=> use spherical_harmonics from scipy in orbital function

.github/workflows/tests.yml, qutip/tests/test_metrics.py
Add GitHub actions test run on windows-latest.
- Clean up of #1849
**Changelog**
Add GitHub actions test run on windows-latest.
=> Add GitHub actions test run on windows-latest.

.github/workflows/build.yml, .github/workflows/tests.yml, doc/changelog.rst, qutip/core/coefficient.py, qutip/core/qobj.py, qutip/solver/options.py, qutip/solver/parallel.py, qutip/tests/core/test_metrics.py, qutip/tests/solve/test_steadystate.py, qutip/tests/solver/test_parallel.py
Merge the latest changes of master.
- Activating the windows tests.
- Updating the changelog.
=> Merge master post 4.7

qutip/core/cy/qobjevo.pyx
Updating cython to 0.29.30 break some tests... This fix the issue.
**Changelog**
Add support for cython 0.29.30
=> Add fix for cython 0.29.30 for dev.major

qutip/orbital.py
Tiny removal of unused import, due to early merge in https://github.com/qutip/qutip/pull/1844
https://github.com/qutip/qutip/pull/1844
**Changelog**
Removing unused import in qutip.orbital.
=> remove unused import

qutip/bloch.py, qutip/tests/test_bloch.py
Clean-up of the point method in the `Bloch` class. This PR does not add any new feature but it does:
- Improve readability and logic in the point methods for the Bloch class. 
- Extended test coverage of the point methods.
- Now add_points raises error if the arguments `points` or `meth` are wrong.
**Changelog**
Clean-up of the point methods in the `Bloch` class.
=> Bloch cleanup dev

doc/biblio.rst, doc/guide/guide-control.rst
**Changelog**
Added missing citation for the GRAPE algorithm to the control guide.
=> Updated Bibliography and added citation for GRAPE

qutip/core/qobj.py, qutip/tests/core/test_qobj.py
Fix `Qobj.groundstate` and add a test. 
Fixes #1937
Thank you @christian512 for finding the bug.
=> Fix groundstate and add test

doc/changes/1958.doc, doc/guide/dynamics/dynamics-bloch-redfield.rst, doc/guide/dynamics/dynamics-floquet.rst, doc/guide/scripts/floquet_ex3.py
Added description of the Floquet Markov formalism.
=> Update docs Floquet Markov formalism

doc/changes/1967.doc, doc/development/ideas.rst, doc/development/ideas/tensorflow-data-backend.rst, doc/development/roadmap.rst
Update the roadmap and ideas to show completed work as of August 2022.
None.
=> Update the roadmap and ideas to show completed work as of August 2022.

qutip/core/data/expm.py, qutip/core/qobj.py, qutip/tests/core/data/test_mathematics.py, qutip/tests/core/test_qobj.py
Add `Qobj.logm()` for the matrix logarithm operation.
Only create the `Dense` operation was created.
`expm_dense` was also added.
Fix #1990 for dev.major
=> Add `Qobj.logm` for dev.major

doc/changes/2038.bugfix, qutip/fileio.py, qutip/tests/test_fileio.py
Add back .qu suffix to saved objects.
- Fixes #1877
- See #1813 for the PR that introduced the bug
=> Add back .qu suffix to saved objects

setup.py
Fix parsing of version numbers when using packaging 22.
- #2037
- #2036
=> Fix parsing of version number when using packaging 22.

.github/workflows/build.yml, .github/workflows/tests.yml, doc/changes/2041.misc
Add python 3.11 build using 3.11 from conda-forge.
- None
=> Add python 3.11 build using 3.11 from conda-forge.

doc/changelog.rst, doc/changes/1924.misc, doc/changes/1927.doc, doc/changes/1940.doc, doc/changes/1946.misc, doc/changes/1950.doc, doc/changes/1958.doc, doc/changes/1961.bugfix, doc/changes/1964.bugfix, doc/changes/1965.bugfix, doc/changes/1967.doc, doc/changes/1970.bugfix, doc/changes/1979.bugfix, doc/changes/1980.feature, doc/changes/1983.bugfix, doc/changes/2011.bugfix, doc/changes/2012.bugfix, doc/changes/2037.bugfix, doc/changes/2038.bugfix, doc/changes/2040.bugfix, doc/changes/2041.misc, doc/changes/2043.misc
Update changelog for 4.7.1.
- None
=> Update changelog for 4.7.1.

.github/workflows/build.yml, doc/changelog.rst, pyproject.toml
Cherry pick the build fixes from #2046.
- Cherry picks the build fix commits from #2046.
=> Fix builds for 4.7.1

qutip/solver/spectrum.py, qutip/tests/solver/test_correlation.py
When I updated correlation to use the data layer in #1997. `spectrum` was moved to its own file, but was left mostly unchanged.
This update `spectrum` to use the data layer,
=> Update `spectrum` to use the data layer

README.md
Add note to README on master branch switching to v5.
None.
=> Add note to README on master branch switching to v5.

qutip/settings.py
Fix the bug in the logic to find the blas info reported in #2053.
Close #2053
=> Fix logic finding blas libraries

README.md, doc/installation.rst
Add a short note about the availability of v5.0.0a1 on PyPI with link to the changelog in both the README and the installation instruction from the documentation.
=> Add pre release installation instruction

doc/requirements.txt
See dependabot PR #2085.
- #2085
=> Bump versions of ipython and prompt-toolkit.

README.md
Add links and badges for Read the Docs.
- #2087
- #2090
=> Add links and badges for Read the Docs.

.github/workflows/tests.yml, doc/changes/2105.misc
Restore the towncrier check that was disabled for in dev branch.
=> Restore towncrier checks

doc/changes/2103.misc, qutip/core/semidefinite.py, qutip/measurement.py
fix #2101
Added `__all__ ` to files:
- `qutip/measurements.py`
- `qutip/core/semidefinite.py`
Added all the user facing functions were added into `__all__`
=> added __all__ to files: fix #2101

.github/workflows/tests.yml, doc/changes/2119.misc
Remove Windows test suite warning suppression.
- None
=> Remove Windows test suite warnings suppression.

qutip/core/cy/coefficient.pyx, qutip/core/data/solve.py, qutip/solver/integrator/explicit_rk.pyx, qutip/tests/solve/test_piqs.py, qutip/tests/solver/test_scattering.py, qutip/tests/test_openmp.py, qutip/tests/test_partial_transpose.py, qutip/tests/test_qpt.py, qutip/tests/test_subsys_apply.py, qutip/tests/test_three_level.py, qutip/tests/test_wigner.py
- Remove `run_module_suite`, call nosetest, not pytest.
- Change `assert_` to `assert`, the later work better with pytest.
- Add some missing `__all__`.
=> Remove `run_module_suite` and `assert_`

qutip/tomography.py
Simplify `_index_permutations` using `itertools`.
=> tomography uses itertools

doc/changes/2049.misc, qutip/stochastic.py
=> Fix typo in stochastic.py

doc/apidoc/classes.rst, doc/changes/2163.doc, doc/changes/2167.doc, qutip/solver/solver_base.py
Add inherited members (properties and methods) in the API docs for the solvers mentioned in the issue.
Add inheritance of these solvers showing from which base classes they inherit.
fixes #2163
=> Dev uhack solver docs

doc/changes/2174.doc, doc/guide/dynamics/dynamics-bloch-redfield.rst
Correct minor grammar issues
none
=> Capitalize Monte Carlo

qutip/solver/floquet.py, qutip/tests/solver/test_floquet.py
Fallback to `fsesolve` passed unused argument.
Add a test.
=> Fix fsesolve fallback

.github/workflows/tests.yml, pyproject.toml, setup.cfg
Atempt to fix the issue with cython 3.0.3 and python <=3.9 with conditional requirements.
=> Conditional cython requirement

doc/changes/2243.bugfix, qutip/visualization.py
Fix the issue with matplotlib 3.8 for 4.7.
fix #2233
=> Adapt qutip 4.7 for matplotlib 3.8

doc/changes/2252.bugfix, qutip/qobj.py, qutip/tests/test_enr_state_operator.py
Avoid int overflow in Qobj dims check 
fix #2249
=> Avoid int overflow in Qobj dims check

qutip/core/qobj.py
Minor cleanup of `Qobj` (docstrings, removed unused variable, fixed typo in setter of `data`).
Docstring fixes include: removing `type` parameter from constructor, documenting possible types of `inpt` parameter, adding a handful missing functions to the list of functions.
=> Qobj minor fixes

doc/changelog.rst, doc/changes/1974.bugfix, doc/changes/1996.feature, doc/changes/2057.feature, doc/changes/2210.feature, doc/changes/2234.bugfix, doc/changes/2257.misc, doc/changes/2262.bugfix, doc/changes/2269.bugfix, doc/changes/2271.misc, doc/changes/2272.bugfix, doc/changes/2280.bugfix, doc/changes/2284.misc, doc/changes/2288.bugfix, doc/changes/2296.feature, doc/changes/2303.feature, doc/changes/2306.misc, doc/changes/2311.misc, doc/changes/2313.misc, doc/changes/2325.misc, doc/changes/2331.misc, doc/changes/2333.bugfix, doc/changes/2342.misc
Apply towncrier.
Also import the change logs entries from the 4.7.X branch.
=> Update changelog for v5b1

doc/changelog.rst, doc/changes/2289.misc
Seems I forgot to pull master before making the changelog in #2343, missing one entry.
=> Add last minute merge to changelog

qutip/core/data/reshape.pyx
`reshape_dense` use `idxint` for internal computation where the input can by `size**2` and could overflow.
A 11 qubit system in `mesolve` could overflow when the input `dm` was `C` ordered (found by @nwlambert).
This fix this overflow and speed up `column_stack_dense` for `C` ordered.
=> Fix reshape_dense integer overflow

doc/changes/2352.feature, qutip/core/qobj.py
Add dtype to printed ouput of qobj
fix #2339
=> add dtype to printed output of qobj

doc/changelog.rst
Fix the latex build issue introduced in v5's changelog
=> Fix doc build error from changelog 5

.github/workflows/tests.yml, doc/changelog.rst, doc/changes/2352.feature, doc/changes/2354.misc, qutip/core/cy/qobjevo.pyx, qutip/core/data/matmul.pyx, qutip/core/data/reshape.pyx, qutip/core/qobj.py, qutip/core/states.py, qutip/core/superoperator.py, qutip/simdiag.py, qutip/solver/_feedback.py, qutip/solver/mcsolve.py, qutip/solver/multitraj.py, qutip/solver/nonmarkov/transfertensor.py, qutip/solver/result.py, qutip/solver/solver_base.py, qutip/solver/stochastic.py, qutip/tests/core/data/test_dense.py, qutip/tests/core/test_qobj.py, qutip/tests/solver/test_stochastic.py, qutip/tests/test_enr_state_operator.py, qutip/tests/test_wigner.py, setup.cfg
Merge latest changes to qutip-5.0.X branch for a v5 release soon.
=> Prepare qutip 5.0.0

doc/guide/dynamics/dynamics-monte.rst
`mcsolve` taking Liouvillian input replace the photocurrent_mesolve function.
Add the equations for open mcsolve evolution to the mcsolve page in the guide.
Help cases such as #2060
=> Add equation in the guide for open mcsolve evolution

CONTRIBUTING.md, README.md, setup.cfg
That PR was not cherry-picked in the prepare-5.0.1 PR...
=> Fix broken links for the doc (#2376)

qutip/solver/steadystate.py, qutip/tests/test_enr_state_operator.py
Updated steadystate solvers to use ` _dims[0].oper ` (instead of `dims[0]`) to get the dimensions of the returned state from the Liouvillian.  This should fix the issue with enr states and steadystate solvers.  
Also updated the svd method a little bit to be more consistent with the others.
Added a basic test of just the default steadystate solver method.
fixes #2386
=> ENR state fixes for steadystate solvers

doc/changes/2401.doc, doc/guide/guide-basics.rst
=> Fix mistake in doc

doc/changelog.rst, doc/changes/2280.bugfix, doc/changes/2371.bugfix, doc/changes/2382.bugfix, doc/changes/2388.misc, doc/changes/2393.bugfix, doc/changes/2401.doc, doc/changes/2409.doc, doc/changes/2413.misc, doc/changes/2425.misc, doc/changes/2427.misc
Create changelog for 5.0.2 and merge 5.0.1's.
=> Changelog 5.0.2

qutip/solver/solver_base.py
The check that the initial state was already normalised for normalising output would branch over values, which breaks `jax.jit` support... Moved the option check first.
Also changed the `isoper` check to filter out rectangular operator.
Rectangular state in solver are tolerated, but we don't have tests for it. I did not add any here, but we should 
qutip/qutip-jax#49 qutip/qutip-tutorials#100
=> Ensure `_prepare_state` support jax

.github/workflows/tests.yml
Not sure why, but after merging, #2457, the tests failed.
This fix tests (at least in my fork...).
=> Install optionals dep with runtime numpy version

qutip/core/data/csr.pyx, qutip/core/data/dia.pyx
Quick fix to support scipy 1.14.
=> Add scipy 1.14 support patch

qutip/entropy.py
This PR introduces support for different numerical backends in entropy.py. By leveraging dynamic backend selection, we enable compatibility with both NumPy and JAX
This PR builds upon the groundwork laid in PR #2461, further extending the capability of dynamic backend selection.
=> add dynamic backend selection for entropy.py

doc/changelog.rst, qutip/core/data/csr.pyx, qutip/core/data/dia.pyx
Added last minute patch: support for scipy 1.14.
=> Prepare 5.0.3 (2nd try)

doc/changelog.rst, doc/changes/2400.bugfix, doc/changes/2421.misc, doc/changes/2441.doc, doc/changes/2443.bugfix, doc/changes/2454.bugfix, doc/changes/2457.misc
Create the changelog for 5.0.3
=> Changelog for 5.0.3

doc/changes/2474.feature, qutip/solver/stochastic.py, qutip/tests/solver/test_stochastic.py
Allow merging trajectories of 2 stochastic evolutions.
=> Allow merging stochastic results

doc/changelog.rst, doc/changes/2466.bugfix
=> Merge 5.0.4 changelog

qutip/core/environment.py
Mini fix to correct the column titles of the fit summary in spectral density fits.
=> Corrected column titles in SD fit info

.github/workflows/build.yml
Add wheels for python 3.13.
Fix sanity check.
Same as #2587
=> Build .py313

qutip/about.py
I've not been a "current" admin for some time now.
None
=> Remove Jake from "current admins" list

.github/workflows/tests.yml
I though we already ran some test with python 3.13...
Add some for all OS.
=> Run some tests on python 3.13

doc/changes/2599.doc, qutip/distributions.py
Added docstrings and type hints for functions in `distributions.py`.
=> Docstrings and type hints  for distributions

doc/apidoc/experimental.rst, doc/apidoc/visualization.rst, doc/changes/2607.feature, qutip/animation.py, qutip/distributions.py, qutip/tests/test_animation.py, qutip/tests/test_distributions.py, qutip/tests/test_visualization.py, qutip/visualization.py
Removed WignerDistribution, QDistribution from distributions.py and their tests. 
Added Harmonic Oscillator to API doc.
=> Removed certain distributions already in visualization

doc/changelog.rst, doc/changes/2595.bugfix
Synchronise the changelog with the `qutip-5.1.X` branch for the patch release 5.1.1.
=> Add changelog for 5.1.1

doc/guide/guide-control.rst
**Checklist**
I update the link of qutip-qoc. because previous link was outdated
fix#2524
=> update qutip-qoc link

doc/changes/2680.bugfix, qutip/core/operators.py
fix#2680 Added missing abs when checking for hermiticity
=> fix#2680 Phasegate bugfix

doc/changes/2646.bugfix, qutip/core/coefficient.py, qutip/tests/core/test_coefficient.py
Fix bug were args are not properly updated at coefficient creation when initialised from another coefficient.
fix #2646
=> Fix bug were args are not properly updated at coefficient creation.

doc/changes/2435.feature, qutip/solver/countstat.py, qutip/tests/solver/test_countstat.py
Adding the first three cumulants using the expressions of C. Flindt's PhD Thesis (page 80): https://orbit.dtu.dk/en/publications/electrons-in-nanostructures-coherent-manipulation-and-counting-st
I have modified the code so it is consistent with the previous work made in QuTip. And I have added it as an independent function so it doesn't modify the original code.
@nwlambert these are the changes mentioned in my previous email.
feature #442
=> Third cumulant

qutip/solver/brmesolve.py, qutip/solver/solver_base.py
**Checklist**
This small PR fixes the missing exceptions. It also fixes a few typos along the way.
=> Fix missing exceptions
