qutip/tests/test_qobj.py

Attempt to solve issue with false errors in Qobj division tests on 32 bit system by using comparison that is more robust to floating-point errors.

fix Qobj division unit test

---

qutip/random_objects.py
qutip/tests/test_random.py

This PR addresses #315 by providing sampling for Haar (unitary), Hilbert-Schmidt (DMs), Ginibre (DMs) and BCSZ (superoperators) distributions. Some more documentation is needed still, but the tests pass locally on Python 2.7 and 3.4.

Improved Random Quantum Objects

---

.travis.yml
qutip/control/setup.py
qutip/cy/setup.py

gcc 4.4 does not support the `-flto` option for link time optimization. This is still a common compiler because it is the system gcc in centos 6 and redhat enterprise 6.
In this pull request I've removed that option. Users who need this could set the CCFLAGS environment variable to customize the compiler flags. Alternatively, we could add options to `setup.py` to enable or disable link time optimization.
I've also added additional rows to the travis build matrix to test building with gcc 4.4 and clang. In its current form this adds 4 additional rows to the build matrix (2 additional compilers, each tested with python 2.7 and 3.4). Let me know if you think this is excessive. It's possible to add just one python version for gcc 4.4 and clang.

Fix gcc44 build

---

qutip/control/dynamics.py
qutip/control/loadparams.py
qutip/control/optimconfig.py
qutip/control/optimizer.py

Fix in load params where 'pulsegen' was 'optim'
Fix to error handing when creating output directory
FileExistsError is new in Python 3
Hence swapped to OSError using errno for Python 2 compatability

Fixes in load_params and output_dir creation error handling

---

qutip/ipynbtools.py

I've been annoyed from time to time that the output of the very useful version_table is ordered randomly. This fixes that by using a list of tuples instead of a dictionary (an OrderedDict would work equally well, of course).

change version_table in ipynbtools to use deterministic output order

---

cython_fail_test.py
qutip/cy/codegen.py

This seems to fix the issue reported by Vlad on the Google group.
This fixes the errors when using complex cmath header and typedef variables.  Variables must be of float, int, or complex, not np.kind_t

Possible fix for cython codegen errors

---

qutip/control/cy_grape.pyx
qutip/control/dynamics.py
qutip/control/fidcomp.py
qutip/control/optimconfig.py
qutip/control/propcomp.py
qutip/control/pulseoptim.py

hi,
i think there was a bug in the computation of gradients for unitary problems. im not sure if i tracked them down correctly, but the gradients seem to be more consistent now. this can be checked with the following code after initialization of an Optimizer object `optim`.
```python
from scipy.optimize import check_grad
func = optim.fid_err_func_wrapper
grad = optim.fid_err_grad_wrapper
x0 = optim.dynamics.ctrl_amps.flatten()
check_grad(func, grad, x0)
```
also, im new to github and im not sure if im doing this correctly.

Fixed a bug in gradient computations in control module

---

qutip/bloch_redfield.py

Mostly by replacing explicit loops with vectorized numpy expressions. For a simple test Hamiltonian with a single N-level bosonic operator, it is faster by a factor of ~40 for N=100 (Hamiltonian 100x100), i.e., it takes 12 seconds instead of 460 seconds. The speedup improves about linearly with N for this system.
I checked for some test systems that the results are the same as before. The only difference in interface is that c_ops is [] by default, and c_ops=None is not accepted anymore. This seems to me more in line with the rest of qutip, but could be changed back trivially.

optimized bloch_redfield_tensor routine

---

qutip/control/optimizer.py

approx_grad attribute added to the Optimizer object that forces the
optimisation method to use the gradient approximation
(rather than any exact method)
The motivation for this is to allow adding of custom fidelities that do not have an exact gradient formula.
As an aside: The CRAB algorithm already used these approximate gradient methods, and is most likely to be faster with these custom fidelities

Optimizer approx_grad

---

qutip/control/loadparams.py

This small change allows parameter values of data type list, Qobj and ndarray to be given in parameter files.
As with the other data types supported, the set_param function looks at the existing data type for the object property to determine how to parse the value in the parameter (ini) file.
Lists are expected to appear in the file in a format that can be pass to list() as 
setattr(obj, attrib_name, list(eval(val)))
is the call made, e.g.
[Dynamics]
evo_times=[1,2,5,10]
Similarly with arrays the call is 
setattr(obj, attrib_name, np.array(eval(val), dtype=a.dtype)) 
e.g.
target = [[1, 1], [1, 1]]
The same goes for Qobj

Qtrl load params list, Qobj and ndarrays

---

qutip/qobj.py

When csr_matrix(spmat) is called with a sparse matrix spmat, the
default argument is copy=False, which then returns a reference to
spmat rather than a copy.
This behavior is the cause of at least one other bug (involving Qobj
multiplication) I have found, which I will fix separately if this
behavior is the intended result.
This probably hasn't been identified before because in many places
qobj.data is replaced with new matrices following computations. Also
copying can happen implicitly if the sparsity is changed as discussed 
here:
http://stackoverflow.com/questions/16722316/scipy-sparse-matrices-copy-argument

Add copy=True to csr_matrix() in Qobj constructor

---

qutip/control/optimizer.py
qutip/control/pulseoptim.py

Recent changes to the Optimiser class had left the bounds only being applied for the CRAB algorithm
Bounds now applied for GRAPE using l-bgfs-b and fmin_l_bfgs_b
fixes issue #353

Amplitude bounds now applied (again)

---

qutip/qobj.py

This commit makes `Qobj().iscp` compare the choi matrix eigenvalues to `-settings.atol` rather than `0`. Otherwise it returns `False` for cases where some eigenvalues are negative due to numerical noise but should really be zero.

Make Qobj().iscp compare to -settings.atol rather than zero

---

qutip/superop_reps.py
qutip/tests/test_superop_reps.py

In writing the documentation for #332, I noticed that the chi-matrix produced for several test channels was incorrect due to my placing the dagger in the wrong place. I apologize for that mistake--- this PR should fix it, and add unit tests that ensure that the chi matrix produced by to_chi agrees with that for some known Pauli channels and a unitary rotation.

Fixed basis transform in to_chi, added unit tests for regression.

---

qutip/superop_reps.py
qutip/tests/test_superop_reps.py

This feature starts work towards implementing diamond norms between quantum channels by providing Stinespring dilations of ``type="super"`` Qobjs. This requires generalizing the current ``to_kraus`` feature, since the left and right Kraus operators are the same only for CP maps, whereas the arguments to diamond norms are very often not CP (in particular, will often be a difference, || \Lambda_1 - \Lambda_2 ||_\diamond).
The pull request is currently in an incomplete state, so as to solicit feedback before solidifying the design. The docstrings are missing or are incomplete, Python 3 compatibility has not yet been tested, and I still need to make unit tests. Most importantly, the ``dims`` attribute of the input Qobj is not yet preserved, in lieu of solving #331.

Stinespring dilations of type="super" Qobj

---

qutip/metrics.py
qutip/superop_reps.py
qutip/tests/test_metrics.py
qutip/visualization.py

This PR introduces a new metric, unitarity, based on [work with Wallman, Harper and Flammia](https://scirate.com/arxiv/1503.07865). In that work, we show that this metric is useful for discriminating between coherent and incoherence noise. As such, I hope that contributing an implementation of our new metric to QuTiP will be of use, especially for comparison to experimental data from randomized benchmarking. While it still needs some more documentation and test cases, I wanted to open the PR now to get some initial feedback.

Feature unitarity

---

.travis.yml

Pursuant to discussions over the build failures observed in #359, this PR migrates Travis CI support to their new container-based configuration. I've observed that the builds with this configuration are more reliable, but they are slower for some reason. In the [instructions](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#Faster-builds) they provide, Travis say that this configuration should be faster, and to let them know if our build is slower; that might be worth doing.

Travis migration

---

qutip/qobj.py
qutip/tests/test_qobj.py

This PR changes ``Qobj.__mul__`` and ``Qobj.__add__`` to leave ``isherm`` lazily-evaluated (that is, ``_isherm = None``) unless the Hermicity of the result is already known from closure under addition. This change was prompted by noticing that ``isherm`` alone took up over half of the runtime of a computation I was attempting, despite that nothing actually ever looked at the Hermicity of a product of two ``Qobj`` instances. I also added additional tests to ensure that ``__mul__`` doesn't result in incorrect values of ``isherm``, something that was not previously covered by ``qutip.tests.test_qobj.test_QobjHerm``. The new tests pass locally on Python 2.7 and 3.4 (Ubuntu 14.10) as well as on Windows with Python 2.7.

__mul__ and __add__ leave isherm lazily-evaluated.

---

qutip/metrics.py
qutip/tests/test_metrics.py

This new function doesn't calculate the explicit sqrtm() unless
absolutely necessary to improve numerical stability. Also includes new
tests to check for regressions of #361.

New more numerically stable fidelity (fixes #361)

---

qutip/metrics.py
qutip/tests/test_metrics.py

The target kwarg for average_gate_fidelity makes it easier to compare
channels to a particular desired unitary without needing to apply the
target unitary on superoperator space. This is especially important to
open quantum systems control.

Adds target kwarg to average_gate_fidelity; unit tests.

---

qutip/control/dynamics.py
qutip/control/fidcomp.py
qutip/control/loadparams.py
qutip/control/optimizer.py
qutip/control/propcomp.py
qutip/control/termcond.py
qutip/control/tslotcomp.py

Use of iteritems removed in apply_params to make compatible with Python3
fixes #367 
Also some changes to the way max_metric_corr and accuracy_factor method_params are applied in the optimizer

Python3 compatibility fix in control classes apply_params

---

setup.py

removed import of setuptools as this breaks fresh installations (i.e
under macports) on some systems by not registering the qutip module
properly. Added it just to try wheels builds so not important

Undo wheels

---

qutip/correlation.py

corr_mat casting made explicit
A cast from object to complex that was acceptable in numpy 1.9
was failing in numpy 1.10
This was causing an error in #379 Travis tests

casting fix for correlation_2op_2t 

---

qutip/tensor.py
qutip/tests/test_tensor.py

This PR fixes #386 by changing checking if ``j == i + 1``, in which case NumPy doesn't automatically move fancy indices to the left. In particular, for adjacent indices, we should sum over index ``i``, not over index ``0`` as was assumed before. To catch regressions, this PR also adds more robust unit tests that check more unusual tensor contractions. Thanks to @arnelg for pointing this out!

Fix #386 by changing axis for np.sum().

---

qutip/superop_reps.py
qutip/tests/test_superop_reps.py

The previous implementation of ``choi_to_chi`` and ``chi_to_choi`` required that ``dims`` be specified explicitly as qubits; for example, ``[[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]`` for a three-qubit system. This PR generalizes to allow for ``dims`` built from powers of 2 instead, as in ``[[[8], [8]], [[8], [8]]]``. In addition, this PR adds new test cases to check that ``to_choi`` and ``to_chi`` properly roundtrip for multiqubit dimensions.

Generalized superop reps to more robustly handle multiqubit dims.

---

qutip/cy/utilities.py

Simpel fix for depreciation warning is sysconfig used to remove old cython temp files.

Sysconfig fix

---

qutip/__init__.py

When `qutip.settings.num_cpus==0` in `__init__.py`, the `qutip.hardware_info` module was replaced with the `hardware_info` function through `from qutip.hardware_info import hardware_info`. This caused problems in `ipynbtools.version_table`, which tries to call `qutip.hardware_info.hardware_info()`.

fix use of hardware_info in __init__.py

---

qutip/control/loadparams.py
qutip/control/optimconfig.py

additional arguments added to load_parameters so that a general object attributes can be loaded from a configuration file. For a example a custom fidelity computer

Qtrl load params general

---

setup.py

This is to fix issue #413 that caused new installations to be non-functional.
Anyone got any ideas as to why this was not picked up by the travis tests?

nonmarkov added to list of packages

---

qutip/control/pulsegen.py
qutip/control/pulseoptim.py
qutip/tests/test_control_pulseoptim.py

Removed hardcoded pulse generator num_waves from create_pulse_optimizer
Changed TRIANGLE pulse type to start from zero (to match the other periodic types)
Added test that checks freq and num_waves pulse parameters are applied correctly in create_pulse_optimizer
resolves issue #412

Fix for num_waves and freq pulse parameters being ignored

---

qutip/tests/test_superoper.py

This PR changes the norm used in ``qutip.tests.test_superoper.testLiouvilleImplem`` to the max-norm. Previously, this test used the tr-norm, which scaled badly with the dimension of the Liouvillian under test, such that spurious failures were generated (see #419).

Fix for Liouville test

---

qutip/qobj.py
qutip/tests/test_qobj.py

This PR introduces a new method on``Qobj`` that forces an instance to be a valid density operator. This is useful when dealing with tomographic estimators that do not constrain to the space of density operators, such as least-squares fits. In particular, this PR allows for two different truncation algorithms: ``clip``, which is fast and straightforward, and the [SGS algorithm](https://dx.doi.org/10/bb76).

Truncation of negative eigenvalues

---

qutip/control/setup.py
qutip/cy/setup.py

- Switched to -mtune=native
The latest version of Anaconda does not play well with the -march flag.  I am not sure if this is due to the use of MKL on all platforms, or if it is something else.  -mtune works fine though.

BUG: Anaconda 2.5 does not like -march=native

---

qutip/qobj.py

This PR fixes how ``Qobj.trunc_neg_eigs(method='sgs')`` handles eigenvalues equal to 0, which should resolve #425.

Fix for #425

---

qutip/settings.py
setup.py

This PR addresses #410 by attempting to import ``setuptools``, which has support for unittesting and nose integration. Upon failure, it should leave the setup process as it was. This PR also fixes a rare exception in ``settings.py`` that can be caused if you have a ``*.pyc`` file for ``logging.py`` and call into QuTiP from something like nose.

Add `test` subcommand to setup.py and fix exception in settings.py

---

qutip/superop_reps.py

This PR addresses #433 by manually setting ``Qobj.superrep`` to suppress warnings in ``chi_to_choi``. The change of basis for chi → choi is currently represented as a ``superrep='super'``, as that makes sense in several other contextx, such that spurious warnings were raised when performing this conversion.

Suppress superrep warnings when we know what we're doing.

---

qutip/qobj.py
qutip/tests/test_qobj.py

- A Qobj times a dense vector would result in a recursive loop and
crash the computer.
- Made the multi array check better about handling dtypes and added
test.
The output is a dense array.  However if we do create a dense Qobj class (as described in #437) then that should be the returned object.

BUG: Qobj*vec crashes computer

---

qutip/states.py

This may seem like a pedantic change, but is does (very slightly) improve performance in hsolve, and also avoids addressing an array index as a non-integer.
Seems to make sense for the state numbers to be integers anyway.

state numbers made positive in state_number_enumerate

---

qutip/qobj.py
qutip/tests/test_superop_reps.py

This PR should fix #451 by adding an additional check to ``Qobj.iscp`` to check the hermicity-preserving condition. Since this is a useful condition in its own right, the PR also adds ``Qobj.ishp`` to expose that logic separately. Finally, new unit tests have been added to check for regressions on #451, and for the new ``Qobj.ishp`` attribute.

Fix for #451, new ishp attribute, new unittests to cover.

---

qutip/tests/test_wigner.py
qutip/wigner.py

A new iterative method using Clenshaw summation is implemented. It is numerically stable and fast (2-3 times faster than 'iterative').
Test:
```
import matplotlib.pyplot as plt
from qutip import *
import numpy as np
xvec=np.linspace(-10,10,101);yvec=xvec;X,Y = np.meshgrid(xvec, yvec)
psi=coherent(100,7.3*np.exp(1j*0.5))
rho0 = ket2dm(psi)
WW = wigner(rho0,xvec,yvec,method='iterative')
WWc = wigner(rho0,xvec,yvec,method='clenshaw')
plt.contourf(X,Y,WW,100,cmap=plt.cm.viridis)
plt.show()
plt.contourf(X,Y,WWc,100,cmap=plt.cm.viridis)
plt.show()
```

Correct way of calculating Wigner function

---

qutip/metrics.py

Having a warning that appears every time qutip is imported should be avoided.  That is unless we want a ton of questions on the google help group.

ENH: Remove CXVPY logger warning in metrics

---

qutip/superop_reps.py

The previous version contained multiple antipatterns:
- casting to list
- map when comprehension can be used
- map over a comprehension
- len(range(list)) looping
I also suspect that the `zip(*vecs)` call is just a  strange way to reimplement the transpose method, but I am not familiar with the code and did not want to change it.

Fix a complicated list-cast-map-list antipattern

---

qutip/control/dynamics.py

eigh now used in place eig for all oper_dtype
This resolved loss of unitary evolution that had be observed in some cases.

Hermitian eigenvalue solver used for spectral_decomp

---

qutip/tests/test_metrics.py

This PR addresses #484 by skipping dnorm() tests in the known failure case that MKL is present (see #484 and cvxopt/cvxopt#57).

Skipping dnorm tests when MKL is present.

---

qutip/mesolve.py
qutip/sesolve.py
qutip/tests/test_mesolve.py

- Fixed the dims on the final_state output in mesolve and sesolve.
- Also explicitly set the isherm on ouput from mesolve to be True, since the output should be viewed as aa DM regardless if small numerical errors may the isherm check fail.

FIXED: Wrong dims (Issue #480)

---

qutip/tests/test_qpt.py
qutip/tests/test_superoper.py

Some of the super operator and QPT tests may have name space issues as reported in the google group: 
https://groups.google.com/d/msg/qutip/Z-5o4HHYRv4/yRX7dvjiEgAJ
I can not reproduce the errors, but here is a clean up that will likely fix this possible issue.

Clean up test namespace

---

setup.py

As raised in #426, QuTiP currently does not install correctly if listed in the requirements.txt for an external project unless the target environment already has numpy installed. This is due to the use of ``numpy.distutils`` in the current ``setup.py``, such that this PR attempts to solve the issue by falling back to setuptools and then distutils when numpy is missing.

Fix setup.py for use from external requirements.txt

---

qutip/dimensions.py
qutip/qobj.py
qutip/tests/test_dimensions.py
qutip/tests/test_superop_reps.py

This PR addresses #498 by collapsing composite (multipartite) dimensions before taking the partial trace. This is backed by new functions to collapse dimensions specifications of multipartite systems, and both these new functions and the originally erroneous behavior of ``Qobj.istp`` are now covered by new test cases.

Fix for istp of composite systems

---

qutip/correlation.py
qutip/essolve.py
qutip/operators.py
qutip/tests/test_correlation.py
qutip/tests/test_oper_types.py

This branch adds the ability to calculate two-time correlations with fully time-dependent Hamiltonians and collapse operators. The time-dependence may now either be in the Hamiltonian or the collapse operators, or both. Additionally, support for the numpy list format was added. New tests were made to test all of these functionalities. Bugs were fixed.

Ability to calculate two-time correlations with time-dependent c_ops and bug fixes related to the correlator module

---

qutip/nonmarkov/memorycascade.py

Changed from `mesolve` to `propagator` to find the propagator
in the `nonmarkov/memorycascade` module. Gives significant speedup for larger systems and slightly slower for smaller systems. "Larger systems" correspond to long times and "smaller systems" to short times in the memorycascade method.

Use propagator in nonmarkov/memorycascade

---

qutip/stochastic.py
qutip/tests/test_stochastic_me.py

New methods for single stochastic jump operator are implemented:
- 1/2 order predictor-corrector euler-maruyama
- 1 order semi-implicit Milstein
- 3/2 order explicit and semi-implicit Taylor 1.5
Tests for all the new (and old) methods are added.
There is a corresponding notebook which shows that the solvers achieve (or exceed) their order of convergence.
https://github.com/qutip/qutip-notebooks/pull/37
Here is the scaling of solver error as a function of stepsize:
Bug: fast-milstein modifies input noise - fixed.
The explicit Taylor 1.5 method and most of the coding is done by **Manuel Grimm** under supervision of **Niels Lörch** at University of Basel.

ENH: New methods for homodyne stochastic solver

---

qutip/qobj.py
qutip/tests/test_qobj.py

This PR makes ``Qobj`` a callable, in keeping with the proposed semantics discussed in #475. Hopefully, this should make it easier for newcomers and experienced users alike to use the superoperator functionality by removing the need to use ``operator_to_vector`` and ``vector_to_operator`` in simple cases.

Qobj.__call__

---

qutip/control/dynamics.py
qutip/control/fidcomp.py
qutip/control/propcomp.py
qutip/control/tslotcomp.py

Various memory optimisations options in the control time evolution computation.
The main new one is the non-caching of propagator gradients
Most memory optimisations switched on with single dynamics attribute, although each can now be switched individually. All have some cost in execution speed, but can be very beneficial when working with large systems, especially if they have a lots of controls.

control memory optimisations

---

qutip/cy/spmatfuncs.pxd
qutip/cy/spmatfuncs.pyx

We were outputting unnecessary arrays for spmvpy when the function should be void

BUG: spmvpy is not void

---

qutip/qobj.py

Fixed a bug where an object of dimensions m<10 and n>>>1 (e.g. superoperator) triggers a huge latex rendering.

BUG:Fix for latex output of non square Qobj

---

qutip/__init__.py
qutip/cy/codegen.py
qutip/cy/interpolate.pxd
qutip/cy/interpolate.pyx
qutip/interpolate.py
qutip/mcsolve.py
qutip/mesolve.py
qutip/rhs_generate.py
qutip/sesolve.py
qutip/solver.py
qutip/tests/test_interpolate.py

- Cubic_Spline objects can now be used in the me, se, and mc dynamics
solvers as a time-dependent term.
- If possible, the Cubic_Spline object will be evaluated in the
str-based format.
- I have yet to add this functionality to the collapse terms .

ENH: Use Cubic_Spline in dynamics

---

qutip/qip/qubits.py
qutip/tests/test_qubits.py

There were brackets missing in a list comprehension in the function `qip.qubit_states`. 
Additionally puting states = [0] put the qubit in the |1> state and states=[1] put the qubit in the |0> state. I have changed this so that [0] correpsonds to |0> and [1] corresponds to |1>
This pull request addresses these issues and provides a test to test the added functionality.

Fixed missing brackets in qutip.qip.qubit_states

---

qutip/cy/sparse_utils.pyx

cabs( z )**2 is too expensive. Now it is ~ 5 times faster.

ENH: optimise unit_row_norm

---

.travis.yml

Fix for recent version of cvxopt failing due to missing `umfpack.h`

BUG: Fix failing cvxopt build in travis

---

qutip/operators.py

In the case when no args were given, a sign was missing in Jy in the extra piece of code written specifically for this purpose. I propose recursive calls to the function with the respective arguments.

Fix redundancy and sign error in jmat.

---

qutip/__init__.py
setup.py

- This should (hopefully) fix any issue where *.pyx files are being compiled twice.
- Remove control module *.pyx package data.

BUG: Move pyximport to end of init.

---

MANIFEST.in
qutip/tests/test_control_pulseoptim.py

Control pulse optim tests split into more distinct functions.
This is generally a good idea, and will also help investigate #599

Qtrl split unitary tests

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

This is an attempt to solve #678. The `QubitCircuit` class now has a method to add input and ouput states to a circuit. By default, all inputs and outputs are initialised to None. A new input state can be added similar to adding a gate by using the new function `add_state`. The user can specifying the state, the list of qubits where it should be added and the `state_type` as `input` or `output`.
States can be anything provided they are entered as a string.
```
qc = QubitCircuit(3)
qc.add_state("0", targets=[0])
qc.add_state("+", targets=[1], state_type="output")
qc.add_state("-", targets=[1])
```

Adds input and output states to `QubitCircuit`

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

The `reverse_circuit` function was broken as the gates should have been added to the temporary variable's `QubitCircuit.gates`. A better way is to use the `add_gate` method.

Fixes #682: Reverse circuits

---

qutip/qip/circuit.py

Apologies for re-doing the pull request, I had to delete my other account.
qc.N should be used instead of len(qc.gates), we are checking if the added circuit (with a certain number of tracks) fits onto the parent circuit.
The number of gates don't feature.
Before:
if self.N - start < len(qc.gates):
After:
if self.N - start < qc.N:

Tiny bug-fix in def add_circuit(self, qc, start=0):

---

qutip/states.py
qutip/tests/test_states.py

Instead of calculating the alpha**n/sqrt(n!) for every entry, calculate
it recursively by x_{n+1} = x_{n}*alpha/sqrt(n), thereby avoiding the
explicit calculation of the factorial. This way it works also for
dimensions>400 where it would fail before.
This comes with a speed improvement:

Improve analytic calculation of coherent states.

---

qutip/tests/test_mesolve.py

Since NumPy 1.12, `np.linspace` raises a DeprecationWarning when its third `num` parameter cannot be safely interpreted as an integer. This method is used in the `mesolve` tests.
Fixed by feeding the calls to `linspace` 100 instead of 100.0.
The warning (in Travis CI):
The deprecation: https://github.com/numpy/numpy/releases/tag/v1.12.0

Fix deprecated call to NumPy linspace in mesolve test.

---

qutip/cy/spconvert.pyx
qutip/permute.py
qutip/tests/test_qobj.py

Better way to permute Qobj. Captured a bug where old permute didn't permute dimensions.
UPDATE: Now works for super objects (including operator-bra)
Benchmark (permute 1st and last qubits):

ENH+BUG: Improved permute

---

qutip/qip/algorithms/qft.py
qutip/qip/circuit.py
qutip/tests/test_qft.py

This fixes #688, following the suggestion by @mrcalixe.
The fix sets the swap targets to `[N - i - 1, i]`, instead of setting a target and a control separately.
The method `qft_gate_sequence` was untested: This pull request provides various test cases of varying length (1-6) and with and without swapping enabled.

Fix creation of swap gates in qft_gate_sequence (#688)

---

qutip/cy/brtools.pyx

Should be a bit faster than using memoryview indexing since it is direct on the pointer.

ENH: Use ZAXPY in BR dense_add_mult

---

qutip/cy/spmath.pyx

Tensoring of large objects can lead to crash because index runs out of int32. Now it crashes gracefully and reports the overflow problem.

BUG: integer overflow check in tensor product

---

qutip/tests/test_brmesolve_td.py

It looks like my original tolerance was stricter than the default tolerance on the ODE solver.  Oops.

BUG: Loosen tolerance on td-BR states test

---

qutip/qobj.py

There are issues where small flaoting point elements can give isherm=False, but are then removed by tidyup which should then result in isherm=True.  This does the tidyup and then isherm check.

BUG: Do tidyup before calculating isherm

---

qutip/cy/openmp/omp_sparse_utils.pyx
qutip/cy/openmp/utilities.py
qutip/cy/sparse_utils.pyx
qutip/cy/spmath.pyx
qutip/qobj.py
setup.py

It is much faster to use openmp to do the tidyup operation when NNZ > ~500.  Also, in many cases the tidyup operation does not actually result in any zero values in the sparse data, and as such, it is unnecessary to run the eliminate_zeros function.  Tidyup now returns a flag that indicates whether eliminate_zeros should be run.

ENH: Use OPENMP for tidyup if installed.

---

qutip/bloch_redfield.py
qutip/tests/test_brmesolve.py

It is possible to pass a list of Qobj to mesolve, where it is compiled into c.  This is of course not the most efficient thing to do, but it is allowed.  This pull makes the brmesolve function work in this case.

ENH: Allow for list of Qobj to be passed to brmesolve

---

qutip/control/dynamics.py

New dynamics property `phase_application` added to set whether dyn gen phase operator is applied as LHS or RHS operator. Specifically added for use with DynamicsSymplectic, as it would seem there are some cases where one might want to apply $\Omega$ as a 'prepop' rather than a 'postop'.
A bit of general tidying up of the _apply_phase function and phase caching as well

Qtrl phase application

---

qutip/bloch_redfield.py
qutip/cy/br_codegen.py
qutip/tests/test_brmesolve_td.py

The td-BR solver has about a 3-5 second compile time, regardless of system size.   Not 100% sure why it takes this long verses the other solvers, but that is what we got.  This Pull allows for passing the usual args dict of variables to the solver for use in td Hamiltonian or c-op terms.  In combination with Options(rhs_reuse=True), this should allow the user to bypass additional compilation steps when changing Hamiltonian parameters.
This trick does not work for the a_op spectrum strings, since they need to be hardcoded due to limitations in c++.

ENH: Allow td_brmesolve to use the args dict for Hamiltonian & c_op td-terms

---

qutip/qobj.py
qutip/tests/test_cqed.py
qutip/tests/test_qobj.py

This is a fix for the trace-norm bug, as reported in Issue #748.  Unlike Fix #749, this minor correction works for all operators, and does not do the sqrtm operation.

BUG: Fix for trace-norm bug

---

qutip/cy/spmatfuncs.pyx
qutip/qobj.py
qutip/tests/test_qobj.py

Routine computes matrix elements about 10x faster than previous method.  It is slightly better not to actually use a bra-vector, but use a ket-vector instead, and let the computation handle the difference internally.

ENH: Faster Q.matrix_element 

---

qutip/cy/spmath.pyx
qutip/qobj.py
qutip/tests/test_qobj.py

Compute the projector of a ket or bra Qobj via Q.proj().
This routine is ~3x faster than doing the outer product explicitly, and does not need a temp matrix.

ENH: Add projector method to Qobj class

---

qutip/cy/pyxbuilder.py
setup.py

When installing Qutip from source in an MSYS2 environment, the build flags should be set to GCC-style like in *nix installations - I updated the relevant files to do this. I just check for the existence of the MSYSTEM environment variable to check for this case.

Added exception to use GCC in Windows if running in MSYS2

---

qutip/ipynbtools.py

Hi,
As raised by someone on the mailing-list, there is a missing return in `qutip.ipynbtools.plot_animation` helper, leading to a `RuntimeError` when trying to execute the `JC-model-wigner-function.ipynb` example notebook.
This commit should address this issue.
Moreover, the previously mentionned notebook should be updated as well, but I am not sure where the source is. The `plot_result` function should read
```python
cb = None
def plot_result(result, n, fig=None, axes=None):
global cb
if fig is None or axes is None:
fig, ax = plot_setup(result)
axes.cla()
rho_cavity = ptrace(result.states[n], 0)
W = wigner(rho_cavity, xvec, xvec)
surf = axes.plot_surface(X, Y, W, rstride=1, cstride=1, cmap=cm.jet,
alpha=1.0, linewidth=0.05, vmax=0.25, vmin=-0.25)
ax.set_xlim3d(-5, 5)
ax.set_ylim3d(-5, 5) …
```

Fix a missing return in plot_animation helper

---

qutip/wigner.py

There's a bunch of warnings in the build log that indicate that scipy.special.factorial should be used in favor of scipy.misc.factorial.

qutip/wigner.py: scipy.misc.factorial is deprecated

---

qutip/hardware_info.py

lscpu is localisation dependant and breaks if the OS uses e.g. German. "Core(s) per socket" turns into "Kern(e) pro Socket" and results in a crash.
/proc/cpuinfo on the other hand remains the same same, therefore it is suited more as information source.

hardware_info(): Replacing lscpu with /proc/cpuinfo

---

qutip/bloch_redfield.py
qutip/cy/brtools.pyx
qutip/cy/openmp/br_omp.pyx

- Favor sparse matrix BR tensor for non-secular evolution.
- Build diagonal Hamiltonian directly from evals to avoid small
off-diagonal nonzeros that popup when doing a basis transformation.

ENH: BR solver updates

---

qutip/__init__.py
qutip/bloch_redfield.py
qutip/cy/br_tensor.pyx
qutip/legacy/bloch_redfield.py
setup.py

A faster version of `bloch_redfield_tensor`, using components from the time-dependent version.  About 3x+ faster for secular tensors, and 10x+ faster for non-secular tensors.  This routine is now likely limited by the time it takes to do the Python callback for the bath spectra functions.

ENH: Faster bloch_Redfield_tensor

---

MANIFEST.in
qutip.bib
qutip/about.py
setup.py

As discussed in #664 this PR is regarding citation reminders for QuTiP as it seems that many times users are unaware of the papers to cite when they use QuTiP.
I have added a bibtex file in the source now and into the MANIFEST file. We should discuss how to get this to the users attention. Creation of a cite() function which generates a bibtex entry in the working directory whenever qutip is imported could be one option. The other option is to put it in /home/qutip or print it out whenever a result class is called. We can also add a welcome message at setup which reminds users regarding the papers and points them to the bibtex file.
I am in favour of having a bibtex generator in __init__.py such that qutip.bib appears in the code folder whenever QuTiP is used.

WIP: Citation message and bibtex generator

---

qutip/_mkl/spsolve.py
qutip/steadystate.py

This Pull allows users to pick between the scipy and MKL sparse LU solvers for use in the steadystate solver.  This should also address Issue #791 by allowing for modifying the internals for the MKL solver.

ENH: Allow for picking SS solver & access MKL solver internals

---

qutip/cy/codegen.py
qutip/mesolve.py
qutip/tests/test_mesolve.py

Pull allows for passing the interpolation Cubic_Spline functions as time-dependent arguments for the collapse operators in mesolve.

ENH: Allow for Cubic_Spline td-terms for c_ops in mesolve

---

qutip/correlation.py

Finding the full power spectrum given a time-dependent Hamiltonian usually requires a 2-sided power spectrum. For convenience, it would be useful to be able to access this data in a properly ordered array.
Additionally, the majority of literature regarding cavity optomechanics uses a positive e^(i w t) Fourier convention. Passing a simple boolean parameter to this function would allow for the use of scipy's ifft function, scaled by the number of elements.

spectrum_correlation_fft edit: 2-sided spectra and Fourier conventions

---

qutip/sesolve.py
qutip/tests/test_mesolve.py
qutip/tests/test_sesolve.py

Can now give unitary operator as initial `psi0` in sesolve. This way we solve the Schrodinger operator equation.
Also added tests for all the sesolve methods.
Kind of a bit of waste of time, as `propagator` does almost exactly the same thing. However, I think it does add a bit of completeness. The tests at least should be valuable

sesolve unitary operator evolution

---

qutip/operators.py

This is a fix for #847. Since we already have a minimum requirement for Scipy, the error catching here does not make sense. It is better to leave the error returned from the scipy function `scipy.diags` untouched as the qutip version just wraps the result into a `qutip.Qobj`. 
@ajgpitch

Fixes #847 scipy requirement superceeds error catching

---

qutip/control/io.py

Use `isabs` to check if path is absolute
Was mistakenly using `abspath`

control.io fix check for path is absolute

---

qutip/simdiag.py

Code that fails with the current version of qutip  when using for python3 is listed below. 
This code runs for both python2 and python3 with the change suggested.
=======================================
import qutip as q
#consider two coupled spin L and S
Lval = 1
Sval = 0.5
[Lx,Ly,Lz] = map(lambda x: q.tensor(x, q.qeye(2*Sval+1)),q.jmat(Lval))
[Sx,Sy,Sz] = map(lambda x: q.tensor(q.qeye(2*Lval+1), x),q.jmat(Sval))
Jx = Lx + Sx
Jy = Ly + Sy
Jz = Lz + Sz
Lsq = Lx*Lx + Ly*Ly + Lz*Lz
Ssq = Sx*Sx + Sy*Sy + Sz*Sz
Jsq = Jx*Jx + Jy*Jy + Jz*Jz
q.simdiag([Lsq,Ssq,Jsq,Jz])
===========================================================

Fixed bug that stopped simdiag working for python3

---

qutip/qobj.py
qutip/settings.py

In the multiplication is a mechanism deleting 1 dimensional Systems. This can lead to problems on Systems having multiple one dimensional Subsystems. Examples are in #823.
Because I coundn't figure out in which cases this deleting mechanism needed, I didn't want to remove it, but provide an option to disable it.
Signed-off-by: Arne Hamann <kontakt+github@arne.email>

Added options auto_tidyup_dims to disable deletion of 1 dim Systems after multiplication

---

MANIFEST.in

This is the update which fixes the inclusion of .pyx files when qutip source distribution is generated by sdist in the presence of MANIFEST.in. More discussions in #894

Recursively add .pyx files in MANIFEST

---

MANIFEST.in

This is the update which fixes the inclusion of .pyx files when qutip source distribution is generated by sdist in the presence of MANIFEST.in. More discussions in #894

recursively add .pyx files with MANIFEST

---

CODE_OF_CONDUCT.md

The proposed code of conduct is copied from qutip.org/cofc.html.

create a code of conduct

---

qutip/piqs.py

In `qutip.piqs` the dok matrices should be complex valued in-general. This was pointed out by Jose and @nwlambert when trying to create the CSS state. The imaginary part of the density matrix was missing. 
@nathanshammah

Bug fix for `piqs`

---

setup.py

Due to the fact that this flag is hard-coded to the `setup.py`, I am completely unable to install QuTiP to the cluster environment. The only way to overcome it is clone the repo and remove it by hands.
Closes #920

Remove -march=native from compiler flags

---

qutip/mcsolve.py

numpy give deprecation warning in some test related to mcsolve:
```Monte-carlo: Constant H (str format) with no collapse ops (expect) ... /home/ericgig/.local/lib/python3.6/site-packages/qutip-4.4.0.dev0+7af31179-py3.6-linux-x86_64.egg/qutip/mcsolve.py:1152: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.```
I replaced the 2 np.sum causing problem by the python builtin sum. Since we are not doing the sum on a numpy array and it's in the solver setup phase, there is only a negligible effect on performance.

remove np.sum of generator

---

qutip/random_objects.py

In some rare case, the matrix obtain from random_objects.rand_stochastic would have an empty row or column. This would cause the automated test to fail (about 0.8% of the time.)
Small fix that ensure the matrix always has a least 1 element on each rows and columns.

fix rare bad random Qobj

---

README.md
qutip/operators.py

Fix typo in docstrings of `sigmap()` referring incorrectly to `sigmam()`.

Docstring sigmap

---

qutip/pdpsolve.py
qutip/stochastic.py

The docs currently refer to the nonexistent class `qutip.solver.SolverResult`. This corrects those references to the actually used class `qutip.solver.Result`.

Have docs refer to `Solver` not `SolverResult`

---

qutip/qobj.py

updated docstrings in qutip/qobj.py containing instances of qobj with hyperlinks, as per issue 71

Updated qobj docstrings with hyperlinks (Issue 71)

---

README.md
qutip/piqs.py
qutip/tests/test_piqs.py

Eliminate the function `prune_eigenstates()` as it is not correct. Not affecting any other part of code.

Piqs prune

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

This enables QubitCircuit.add_gate() to insert some gate in the middle of the circuit. This should address issue #615 .

Gates can be added to specified position in a QubitCircuit

---

qutip/metrics.py
qutip/tests/test_metrics.py

This PR suggests enhancing the `qutip.metrics` module by adding a new distance b/w quantum states: the quantum Hellinger distance (QHD), implemented as new function `qutip.metrics.hellinger_dist()`. Excellent description is provided for example in:
_Geometric measures of quantum correlations with Bures and Hellinger distances_, D. Spehner, F. Illuminati, M. Orszag, W. Roga, https://arxiv.org/abs/1611.03449
Albeit a bit less popular than already implemented Bures and trace distances, the QHD is actively studied, eg:
https://arxiv.org/abs/1903.10455
https://arxiv.org/abs/1806.10814
https://arxiv.org/abs/1510.06995
The PR contains tests of properties of the QHD as outlined in arXiv:1611.03449
I am of course keen on performing additional tests, code refactoring, documentation of this feature …

Add quantum Hellinger distance to `qutip.metrics`

---

qutip/control/optimizer.py

I updated the use of Iterable and now there is no warning for it in the tests mentioned in #1003.

Update deprecated usage of Iterable

---

qutip/qip/circuit.py
qutip/qip/models/circuitprocessor.py

Some small changes:
1. remove repetitive assignments of `self.arg_value` and` self.arg_label`
2. move the description to the definition of class so the document will show it
3. raise the corresponding error if targets is None while required or not an integer, e.g `Gate("SWAP")` or `Gate("SWAP", [0.5, 2])`

Some patches for qip.Gate

---

qutip/cy/cqobjevo.pxd
qutip/cy/cqobjevo.pyx
qutip/cy/cqobjevo_factor.pxd
qutip/cy/cqobjevo_factor.pyx
qutip/cy/openmp/cqobjevo_omp.pyx
qutip/cy/stochastic.pyx
qutip/floquet.py
qutip/propagator.py
qutip/qobjevo.py
qutip/qobjevo_codegen.py
qutip/stochastic.py
qutip/superoperator.py
qutip/tests/test_qobjevo.py

This PR is part of  PR #969 , splitting that PR in two parts.
It contains:
- `qobjevo`'s args that update with the state. (replacing rhs_with_state functionality) 
- method `norm` renamed to `_cdc` as it was not used as a norm.
- cython side of expect method no longer take `isherm` as an arguments.
- security check in propagator for `H` as a function with `batch` method.
- `propagator` uses `sesolve` capability to evolve operators.
- floquet now call `sesolve` instead of `mesolve` with no collapse.

dynamic args

---

qutip/cy/stochastic.pyx
qutip/stochastic.py

Rework photocurrent code to be more resilient and lower numerical error.
Replace #1010 
euler solver: textbook equation directly used, no more improperly supported multiple collapses.
pred-corr solver: proper support for multiple collapses with no more O(dt) error at each collapses.

Photocurrent rework

---

qutip/eseries.py
qutip/operators.py

1. `Qobj` is included separately. `qt` is not defined.
2. See Also: `func_a : Function a with its description.` As described in https://numpydoc.readthedocs.io/en/latest/format.html

Bugs leading to error in building the documentation

---

README.md
qutip/tests/test_metrics.py

Fix a docstring error prompting a segmentation fault when run on python 3.7.3 on Mac Mojave.

nosetests segmentation fault in Metrics docstrings

---

qutip/qip/circuit.py
qutip/qip/gates.py
qutip/qip/models/spinchain.py
qutip/tests/test_gates.py
qutip/tests/test_qubitcircuit.py

This is a fresh PR branching from the current master as a replacement for #1025 
1. `expand_oper`: expand a qubits operator to dim N
2. User-defined gate can be given by a python function. By passing a list of user-defined gate function to the attribute `QubitCircuit.user_gate`,   `QubitCircuit.propagators()` can return the corresponding matrices. Resolve #914 
3. MS gate and physical single qubit rotation. (Is the name `mc_gate `and `qrot `appropriate?) Resolve #819
4. Fix some bugs in resolving circuit gates. Allow more than one 2-qubits gates in the basis. This is actually already required in `spinchain.py` but covered by a bug

Add user defined gates, MS gate and fix some bugs (replacement)

---

qutip/about.py

QuTiP team members split into groupings based on role
reference to Github for list of contributors

ENH: Attribution in about

---

qutip/tests/test_metrics.py

As we don't have a fix for #963 then this PR skips those tests on the `average_gate_fidelity` on Mac for the time being

Skip avg gate fid tests on mac

---

qutip/mesolve.py

This addresses #1047 by removing the print statement

Don't print msg when mesolve falls back to sesolve

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

The decomposition in `qubitcircuit.py` was wrong.
This can be seen by running
```
qc = QubitCircuit(1)
qc.add_gate("SNOT", targets=0)
dec_qc = qc.resolve_gates()
dec_snot = gate_sequence_product(dec_qc.propagators())
print(snot())
print(dec_snot)
```

Fix wrong decomposition of snot (hadamard) gate in resolve_gates

---

qutip/correlation.py
qutip/qobj.py
qutip/qobjevo.py
qutip/tests/test_correlation.py
qutip/tests/test_qobjevo.py

Fix bug of issues #1048 and #1051:
- Sort csr_matrix after Qobj.permute.
- Corrected bug in the time shifting function in correlation. Added the shift capacity to QobjEvo.
Merge to 4.4.1?

Bugfix: permute and correlator

---

qutip/random_objects.py

Revised rand_ket, rand_ket_haar to allow specifying the ket dimensions.
Previously _check_ket_dims was broken, and definition of dims in the two functions was conflicting.
Changes here:
- removed _check_ket_dims, using the more general _check_dims instead.
- Changed the input method for the rand_ket functions to receive either int, as before, _or_ a dims specifications, rather than both. 
- If dims is specified, N is inferred from dims.
Since both functions were broken previously if dims was specified, and this is backwards compatible if only N is specified, it should be entirely backwards compatible.
Fixes #1057

Revised random ket generators for dims

---

qutip/cy/cqobjevo_factor.pyx
qutip/cy/inter.pxd
qutip/cy/inter.pyx
qutip/qobjevo.py
qutip/qobjevo_codegen.py
qutip/tests/test_mesolve.py
qutip/tests/test_qobjevo.py

Implement an option for using array-like coefficients as step-function instead of cubic-spline:
e.g. 
```
tlist = np.array([0., 1., 2., 3.])
coeff = np.array([1., 2., 3., 3.])
```
The coefficient is 1 in the time interval [0,1), 2 in [1,2) and so on. The last element in `coeff` is just a place holder and has no effect.
@Ericgig Do you think the following might be useful?
1. In `inter.pyx` many functions have two versions, one for complex input and one for float. Now there are 4 pairs of them, will it helps if I try to merge them with fused type in Cython?
2. For non-uniform `tlist`, `_binary_search` is used to find the current index inside the method such as `_spline_float_t_second`, but very often we call this method within a loop for the same `t`. It would improve the performance if …

Time-dependent coefficients without cubic interpolation in QobjEvo

---

.codeclimate.yml
qutip/correlation.py
qutip/cy/cqobjevo_factor.pyx
qutip/cy/inter.pxd
qutip/cy/inter.pyx
qutip/mcsolve.py
qutip/mesolve.py
qutip/qobj.py
qutip/qobjevo.py
qutip/qobjevo_codegen.py
qutip/random_objects.py
qutip/sesolve.py
qutip/simdiag.py
qutip/solver.py
qutip/tests/test_correlation.py
qutip/tests/test_mesolve.py
qutip/tests/test_qobj.py
qutip/tests/test_qobjevo.py
setup.py

Proposal for 4.4.1 Mostly to fix the bugs reported since 4.4.0's release but include small improvements.
Bug Fixes
-------------
- Fixed the pickling but that made solver unable to run in parallel on Windows. (Thank **lrunze** for reporting)
- Removed warning when mesolve fall back on sesolve (by **Michael Goerz**).
- Fixed dimension check and confusing documentation in random ket (by **Yariv Yanay**).
- Fixed Qobj isherm not working after using Qobj.permute. (Thank **llorz1207** for reporting)
- Correlation functions call now properly handle multiple time dependant functions. (Thank **taw181** for reporting)
- Removed mutable default values in mesolve/sesolve (by **Michael Goerz**)
- Fixed simdiag bug (Thank **Croydon-Brixton** for reporting)
- Better support of constant QobjEvo. (by …

Qutip 4.4.1

---

qutip/qip/circuit.py
qutip/qip/gates.py
qutip/tests/test_gates.py
qutip/tests/test_qubitcircuit.py

1. Generalize expand_oper to arbitrary dimensions instead of only qubits system. Together with user-defined gate, this would allow quantum circuit of n-level-system.
2. A method `expand_oper_periodic` can be used to expand gate for all cyclic permutation of the given target qubits. ([0, 1], [1, 2], [2, 0] for 3 qubits system)

expand_oper for composite system with arbitrary dimensions

---

qutip/piqs.py
qutip/tests/test_piqs.py

Addressing #993: nonlinear functions such as the Von Neumann entropy or purity of a density matrix written in the Dicke basis need to account for the identical copies of the blocks relative to non-symmetrical Dicke states. 
This can be done by cycling into the blocks and applying the correct weight accounting for degeneracy (using `piqs.state_degeneracy`). 
This PR also contains auxiliary functions to visualize and unpack the Dicke-basis density matrix into the full 2^N space still of collective spin but with degenerate blocks. 
It uses the `purity` method proposed in #1045. 
Will add info in User Guide and notebooks to highlight this features that need to be considered to correctly calculate nonlinear functions of a density matrix in the Dicke basis.

Entropy vn dicke

---

qutip/bloch3d.py

Attempting to use `add_states()` on a Bloch3d instances results in an exception delayed to when attempting to show it. The line
`cone_mapper = tvtk.PolyDataMapper(input=cone.output)`
is the culprit, as the `input` and `output` attributes were deprecated for VTK 7.x. A quick updating of the attribute names fixes this.

Fixed PolyDataMapper construction

---

.travis.yml
qutip/__init__.py
qutip/cy/br_codegen.py
qutip/cy/pyxbuilder.py
qutip/qobjevo.py
qutip/qobjevo_codegen.py
qutip/rhs_generate.py
qutip/tests/test_brmesolve_td.py
qutip/tests/test_brtools.py
qutip/tests/test_correlation.py
qutip/tests/test_graph.py
qutip/tests/test_interpolate.py
qutip/tests/test_mcsolve.py
qutip/tests/test_qobjevo.py
qutip/tests/test_stochastic_se.py

Added the option to import string to python instead of compiling to cython for QobjEvo.
This is default if no cython, or set manually if cython available. `QobjEvoInstance.use_cython = False`
Added test and updated docstring.
Work in parallel.
Did not do any benchmark yet.

QobjEvo no longer require cython for string coefficient

---

qutip/bloch.py

Fix adding points to the Bloch sphere, with `Bloch.add_points(point)`. 
This solves Issue #1027.
It was a bit tricky to pin down. In Matplotlib 3.1.0, differently from 3.0.3, `edgecolor='none'` somehow produced a broadcast error, whereas now it is set by default to `None`.

`Bloch.add_ponts` fix, edgecolor in plot_points to None

---

qutip/stochastic.py

When using the `average_states` solver option `general_stochastic` seemed to error when summing the timeslot states. This PR provides a fix for this.
Also included is some hopefully more succinct messages from the safety checks in `general_stochastic`.

FIX: sesolve average states

---

qutip/qobj.py
qutip/random_objects.py
qutip/tests/test_ptrace.py
qutip/tests/test_qobj.py

2 improvement to Qobj:
- `inv` method. (close #1102)
- faster `ptrace` using dense matrix (taken from #1076)
Both dense and sparse method are kept. Default is use sparse method when the matrix density in under 10%.
`inv` method also has a sparse and dense version, but sparse is almost always slower.
Some improvement to random Qobj to remove edge case.
Tests are updated.
(Not merge ready yet.)

Qobj inverse and inproved ptrace

---

qutip/tests/test_utilities.py
qutip/utilities.py

Rewrote `clebsch` function based on long integer fraction. Thus escaping the rounding error mentioned in #1141. Surprisingly it's a little faster than the float implementation. 
Also added tests for the function.
Closes #1141

long interger based clebsch

---

qutip/propagator.py
qutip/tests/test_propagator.py

Solves #1152, in which it is found that the `propagator` gives the wrong dimensions when it is run for `unitary_mode= single` and `parallel=False`. 
The problem was arising in line 161 of `qutip.propagator`, [here](https://github.com/qutip/qutip/blob/89ddbf4d2c238cba880bb40acdc448fc1c7c951e/qutip/propagator.py#L161), 
```
if unitary_mode == 'single':
output = sesolve(H, qeye(N), tlist, [], args, options,
_safe_mode=False)
```
the `qeye(N)` resets the dimensions of `H`, which up to then retains the correct Hilbert space structure, `dims`.  Now they are set by `H.dims[0]` in the state.

fix dims incongruence in `propagator`

---

qutip/__init__.py
qutip/cy/openmp/bench_openmp.py
qutip/testing.py

Openmp test on travis tend to hang at the calibration step.
The calibration function compute the matrix vector product with increasing size until the parallel version is faster or it give up. But on Travis, there is only 1 cpu, so the speed up is never observed and the calibration does not give up searching quickly enough. (Over 10min)
In this PR:
- Skip calibration if only 1 cpu.
- Faster calibration by skipping some of the later size and testing only up to 100000 elements. (threshold around 1000 on my cpus)
- Settings used in tests are fixed to use omp if compiled with it, even if slower. (thresh hold at 100)

Faster omp bench

---

qutip/visualization.py

removed the offset value 0.4 to center the fock state distribution on the ticks for the bar plot.

Updated plot_fock_distribution

---

qutip/testing.py
qutip/tests/test_qobj.py
setup.py

Removes the `nose` test runners found in `qutip.testing.run()` in #1158.
This isn't ready to be merged yet, I think - there's still references to `nose` in `setup.py`, and a comment in `test_qobj.py`, the context of which suggests that the tests are organised specifically for `nose`.  I'm not familiar enough with the differences between `nose`, `pytest` and `unittest` to know how much of a problem the latter is, though.

Remove duplicated test runners

---

qutip/operators.py
qutip/states.py
qutip/tests/test_operators.py
qutip/tests/test_states.py

This makes the additions referred to in #363.  As `fock`, `fock_dm` and `projection` are thin passes-through to `basis`, the automatic tensor-producting applies to them too.
`qeye` and `qzero` are reworked to remove all calls to `tensor`, and instead just build their underlying matrix and override the `dims` when converting to a `Qobj`.  The new functionality in `basis` also follows a similar form.
This deprecates my previous pull request #1157, since the recursive call is entirely removed.

Implicit tensor product for qeye, qzero and basis.

---

qutip/continuous_variables.py
qutip/wigner.py

This PR adds information in the doc-string of `wigner` so that the user can more easily identity what value of `hbar=2/g^2` they are using.
Also, the functions related to quadratures in `continuous_variables` now accept the extra parameter `g` related to the value of `hbar`.
As far as I can tell these are the only two places in qutip where the value of `hbar` matters.

Adds information related to the value of hbar in wigner and continuous_variables

---

qutip/qobjevo_codegen.py

Should fix tests/test_propagator.py::testPropHOStrTd sometime failing, ran it 100 times with the patch without error.
Cause: compiling the same string by multiple process at once resulted in them writing temp files with the same filename, resulting in a race condition and random fails. Not sure why it was not caught before.
@nathanshammah, @ajgpitch

name collision fix for parallel propagator

---

.codeclimate.yml

Made the codeclimat less strict for the complexity and code duplication.
Mostly double the accepted complexity since we don't enforce it too much anyways.
Did not disable it as it help us staying careful about the code readability.

Less strict codeclimat logic

---

.travis.yml

Python 3.8 was released awhile ago, so I thought I'd try activate its travis build and see if it passes.

Activate Python 3.8 builds on Linux.

---

qutip/graph.py
qutip/steadystate.py
qutip/tests/test_graph.py

Implements the changes mentioned in #1203.
The `qutip.graph` functions are pure mathematical functions which are beyond the purview of the package.  Most of them have already been merged into `scipy.sparse.csgraph`, so we now move to using those and mark the functions as deprecated.
Only two functions are actually used, and they're not even currently tested.  `weighted_bipartite_matching` is not present in `scipy`, but is still marked as deprecated because we can move it into being an internal-only function, or simply remove the code that depends on it since those paths are not tested.
This will allow the removal of a good amount of Cython code, and simplify maintenance.

Deprecate qutip.graph functions

---

qutip/qobj.py

Add options to fix the phase `Qobj.eigenstates` by choosing 1 element to be real positive.
The sign fix from #1118 would be obtained with:
```
N = 50
psi2 = fock(N,0)
x = create(N) + destroy(N)
eigs = x.eigenstates(phase_fix=0)[1]
```
also, in a more general form:
```
N = 50
n = 20
psi2 = fock(N,n)
x = create(N) + destroy(N)
eigs = x.eigenstates(phase_fix=n)[1]
```
Default usage not changed.

phase fixing in eigenstates (#1118)

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

In response to issue #1210 , added a quick fix for the add_1q_gates so that it now includes the "end" qubit (specified by the end argument). I also added a test in test_add_gates in test_qubitcircuit.py to cover this issue. The function now applies the 1 qubit gate to every qubit in [start, end] (0-indexed), start and end inclusive. This should resolve #1210

Fix add_1q_gates + test

---

qutip/qip/circuit.py
qutip/qip/operations/__init__.py
qutip/qip/operations/gates.py

1. Gate T and S were defined at qutip.qip.operation. Since Pauli-X, Pauli-Y and Pauli-Z exist in qutip.operators, they were imported as functions into qutip.qip.operation. All functions were tested. 
2. Each of the new gates was added to the circuit.py file. 
3. Not apply.

Add more single-qubit gates to QubitCircuit

---

qutip/qip/circuit.py
qutip/qip/circuit_latex.py

Notionally fixes #1179, #1185.  Converts the `os.system` calls to `subprocess.run` because they're now the recommended way of doing things.
I check for existence of the dependencies at import time, and emit a warning (`ImportWarning`) if they don't exist.  This is ignored by the typical warning filters, so it won't actually show up for most users.
If a dependency doesn't exist, then we don't define the relevant methods on the `QubitCircuit` class to avoid IPython introspecting the class object and thinking that it can make a PNG/SVG.
This may not be the best way of doing things, but in this delocalised setting I think it's easier to talk/discuss around a problem with an example in front of us.
In particular, I think raising `NotImplementedError` on failing to find `pdflatex` might not be …

Make LaTeX image conversion more resilient

---

qutip/qip/circuit.py
qutip/qip/operations/__init__.py
qutip/qip/operations/gates.py
qutip/tests/test_gates.py
qutip/tests/test_qubitcircuit.py

- The controlled version of the single-qubit gates
- Changes in QubitCircuit.propagator()
- Tests
fixes #1225 
**Changelog**
Added controlled version of the single-qubit gates
Added controlled single-qubit gates to Qubit.Qip.Circuit.resolve_gates()
Added controlled single-qubit gates to Qubit.Qip.Circuit.propagator()
Added controlled single-qubit gates to Qubit.Qip.Circuit.latex_code()
Added controlled single-qubit gates to Qubit.Qip.Circuit.add_1q_gate()
Added tests for controlled single-qubit gates in Qubit.Qip.Operations.Gates and Qubit.Qip.Circuit

Single qbtgates changes

---

.travis.yml

Prefixes variable names with ```_``` to clear the Travis CI warnings, as mentioned in #1133.
Before the changes, the ```travis lint``` output was:
```
Warnings for .travis.yml:
[x] [warn] on root: deprecated key: stage_generic_linux (anchor on a non-private key)
[x] [warn] on root: deprecated key: stage_linux_36 (anchor on a non-private key)
[x] [warn] on root: deprecated key: stage_linux_37 (anchor on a non-private key)
[x] [warn] on root: deprecated key: stage_linux_38 (anchor on a non-private key)
[x] [warn] on root: deprecated key: stage_linux_37_no_cython (anchor on a non-private key)
[x] [warn] on root: deprecated key: stage_linux_37_openblas (anchor on a non-private key)
[x] [warn] on root: deprecated key: stage_linux_37_omp (anchor on a non-private key)
[x] [warn] on root: …
```

Prefix variable names with _ to clear Travis CI warnings

---

qutip/qobjevo.py

Fix a typo in _shift that I though I fixed some time ago.

fix typo in QobjEvo._shift

---

qutip/mcsolve.py
qutip/stochastic.py

Fix a bug seen on qutip google group:
`np.random.randint(0,2**32)` used to generate seeds for trajectories fails on system where the default int is 32bits. Set the used data type to unsigned int32 which correspond to accepted seed data type.

Fix dtype for randint

---

qutip/stochastic.py

There was an error in line 613 of qutip/stochastic.py as the measurement operators for heterodyne detection in the implemented stochastic master equation should be `c + c.dag()` and `1j (c - c.dag())` as explicitely presented in equation (5.64) and the following 2 paragraphs in https://arxiv.org/abs/1710.09523. The same measurement operators can also be drawn from equation (4.108) of Milburn & Wiseman _Quantum Measurement and Control_.
**Changelog**
Fixed error in m_ops definition for heterodyne detection in smesolve.

Fix error in definition of m_ops for heterodyne detection in smesolve()

---

qutip/tests/test_brtools.py
qutip/tests/test_cavityqed.py
qutip/tests/test_metrics.py

The segfault on mac is not fixed yet. @nathanshammah found 3 tests that fails because of it.
Since we don't have a solution comming soon, we are simply skipping these tests for 4.5.1.
This is the error in #1197.
In common with these 3 test is the computation of eigenvalues, 2 of them do it directly with scipy, the last one compare the cython version to the scipy one.

Test skip for 4.5.1 release

---

qutip/lattice.py
qutip/qobjevo.py
qutip/scattering.py
qutip/utilities.py
qutip/visualization.py

Corrects some fragile usage of `is` to compare strings and types.  This may have worked so far, but it's fragile and liable to break (e.g. strings with the same contents will always `==` each other, but they won't always satisfy `string1 is string2`).

Remove incorrect use of 'is' in comparisons

---

setup.py

Removes a duplicate line in `setup.py`, possibly introduced in the merging of #1074.
**Changelog**
too minor to mention

Remove duplicate line in setup.py

---

qutip/mesolve.py

Fix misleading documentation which said that `c_ops` could be a callback function.  It currently cannot, though all functionality that could be achieved through that can be emulated by passing a callback function returning the full time-dependent Liouvillian as the `H` parameter.
See #1254, fixes #1260.

Correct documentation in mesolve

---

qutip/tests/conftest.py
qutip/tests/pytest.ini
qutip/tests/test_brmesolve.py
qutip/tests/test_brmesolve_td.py
qutip/tests/test_brtools.py

This is the base PR for the split-up of #1181.  This one puts in all the helper functions and updates to previously converted files that are present in that PR, and needs to be merged first before any of the others can be merged.  The commits are tidied up and rebased onto `master`.
This is the base PR for #1250, #1251 and #1252.
**Changelog**
Add pytest helper functions for large-scale test refactoring

Add pytest helper functions and fixtures

---

qutip/tests/conftest.py
qutip/tests/pytest.ini
qutip/tests/test_brmesolve.py
qutip/tests/test_brmesolve_td.py
qutip/tests/test_brtools.py
qutip/tests/test_cy_structs.py
qutip/tests/test_dimensions.py
qutip/tests/test_eigenstates.py
qutip/tests/test_expect.py
qutip/tests/test_fastsparse.py
qutip/tests/test_interpolate.py
qutip/tests/test_lattice.py
qutip/tests/test_mcsolve.py

These are the files that Eric (@Ericgig) was checking in #1181, but the commits are tidied up and rebased onto `master`.  I'll copy over the review comments in that PR that haven't been actioned yet.  The potential merge conflict with `test_mcsolve.py` is fixed.
This is based on #1249, and that one needs to be merged first.
**Changelog**
Major test refactor into a pytest style.

Convert tests to pytest (solvers and internals)

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

The SWAP gates couldn't be added to circuits with `add_circuit`. The function handles the `controls` of the gates while SWAP gates only take the argument `targets`

Fix function `QubitCircuit.add_circuit`

---

README.md

Minor change in README to link to the [new index of notebooks in qutip-notebooks](https://github.com/qutip/qutip-notebooks/pull/105)
Fixes #1279 
**Changelog**
README now links to the index of notebooks in Binder

Update README to link to new index of notebooks

---

qutip/tests/test_brtools.py

The new test explicitly checks the eigenvalue equation for each generated eigenvalue/vector pair, and tests (via the determinant) that all eigenvectors are linearly independent, as they must be since they are eigenvectors of a Hermitian matrix.
The previous test relied on the implementation of `zheevr` producing _exactly_ the same result as `scipy.linalg.eigh`, which was very fragile, and indeed broken by scipy 1.5.
Fixes #1299.
Deprecates PR #1300, since this actually turned out to be a much easier fix than I had feared.  Intermittent segfaults on Mac persist, unfortunately, so this still requires #1288.

Fix brtools zheevr test

---

.travis.yml

There are "breaking" changes within the scipy private code which various parts of QuTiP depended on (see gh-1298, gh-1301 and commits 46e04a1, 6c85261 and 663d7d2).  We ensure that at least one test on Travis uses a scipy version before 1.5 so that we always maintain support for it - the other tests will typically install scipy>=1.5.
This particular test is chosen by elimination:
- we want the "default" case testing against the newest versions of Python to use the newest versions of the libraries available
- we want the Cython parts to be tested against both versions of scipy, since we link against their versions of LAPACK/BLAS.
- the Mac tests (at the time of writing) skip some tests which are problematic because of intermittent segfaults, including at least one which has issues with …

Enforce a CI test with scipy<1.5

---

qutip/cy/stochastic.pyx

Index error in stochastic `smesolve` made `milstein` solver with `heterodyne` method converge only O(0.5) instead of the O(1) expected. This fix it.
**Changelog**
Fixed typo in stochastic code affecting `heterodyne` detection efficiency.

Milstein's heterodyne index fix

---

qutip/cy/spmath.pyx

Due to the CSR format, it is possible for a bra to have unsorted indices (though really you'd try very hard to contrive a situation where this was the case), but it is not possible for a ket.
Sorting is (worst case) O(nnz lg(nnz)), whereas the projection itself is O(nnz**2), so there's very little runtime penalty for doing things the right way.  Also, projection of a bra is pretty uncommon - most users will have a ket, and this path wasn't broken.
Previous broken behaviour:
```python
In [1]: import qutip
...: n = 100
...: b = qutip.rand_ket(n).dag()
...: b2 = b.copy()
...: # Rearrange the indices of the b2 bra.
...: b2.data.data = b2.data.data[np.arange(n-1, -1, -1)]
...: b2.data.indices = b2.data.indices[np.arange(n-1, -1, -1)]
...: b.proj() == b2.proj()
Out[1]: False
```
New unbroken …

Fix zcsr_proj for bras with unsorted indices

---

qutip/cy/spmath.pyx

The bra--ket inner product had an unnecessary loop when looking up the row in the ket, where we already knew which element we needed to lookup.
This function does not check the shapes of the inputs are valid and can therefore segfault on improper input, but it's a low-level Cython function, so that's expected behaviour. The previous version could segfault only in the ket--ket product, not the bra--ket product, but now it's both.
This only affected `qutip.overlap` when neither input was a ket.  Original timing:
```python
In [1]: import qutip
...: b, k = qutip.rand_ket(1000).dag(), qutip.rand_ket(1000)
...: %timeit b.overlap(k)
233 µs ± 214 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
New timing:
```python
In [1]: import qutip
...: b, k = qutip.rand_ket(1000).dag(), …
```

Fix quadratic complexity in zcsr_inner

---

qutip/tests/conftest.py
qutip/tests/test_fileio.py

Windows does not allow opening a tempfile.NamedTemporaryFile more than once, so it's not really suitable for a lot of uses.  We just remove this fixture and use `in_temporary_directory` instead.
Fix #1311 
**Changelog**
Fix fileio tests on Windows

Fix fileio tests on Windows

---

qutip/lattice.py

`f16` does not exist on Windows. Use `np.longdouble` instead, which is `f16` on Mac/Linux and `f8` on Windows.
On windows one gets
```python
>>> np.dtype([('f', np.longdouble)])         
dtype([('f', '<f8')])
```
On Ubuntu
```python
>>> np.dtype([('f', np.longdouble)])
dtype([('f', '<f16')])
```
**Changelog**
fix the dtype error in the lattice module

fix the wrong dtype in the lattice module on windows

---

MANIFEST.in

Trailing slashes aren't allowed in directory patterns on Windows, and have no effect otherwise.
Probably doesn't affect us very much, since I don't think anyone's building the PyPI package on Windows?

Remove trailing slash in MANIFEST.in

---

pyproject.toml

Add `pyproject.toml` to specify build-system as standardized in PEP 518. This enables building qutip in an emtpy environment i.e. without `setuptools`, `Cython`, `numpy` and `scipy` being pre-installed.
If you have a new minimal debian install you sould be able to install this version with
```
$ pip3 install $PATH_TO_QUTIP
```
I only veryfied this in WSL so please test :)
This solves #1246 and #1174 and makes CI for packages that depend on qutip a lot easier.
**Changelog**
Add `pyproject.toml` so qutip can be built without prerequisites

Add pyproject.toml to specify build-system as standardized in PEP 518

---

setup.py

Fail with a more descriptive message when trying to install from source without numpy. Hopefully will not be used with #1309
Discussion in dev-core

fail earlier when installing without numpy

---

qutip/qip/device/processor.py

Spotted the `solver` in `Processor.run_state` was set but not used, so it would always use `mesolve` even if `mcsolve` was specified, so I fixed it.
Not sure if this fixes any issues - I doubt it? - I guess no one had tried to use the `mcsolve` option here yet.
**Changelog**
Ensured `solver` kwarg of `Processor.run_state` correctly sets the solver to `mesolve` or `mcsolve` (`mesolve` was hardcoded in before).

make sure the specified solver in Processor.run_state is used (not always mesolve)

---

qutip/configrc.py
qutip/core/__init__.py
qutip/core/coefficient.py
qutip/core/options.py
qutip/installsettings.py
qutip/optionsclass.py
qutip/settings.py
qutip/solve/solver.py

Rename `optionclass` to `optionsclass` (plural), and `childs` to `children`.  No meaningful changes, though.

Correct spelling in new options classes

---

qutip/core/data/add.pyx
qutip/core/data/csr.pxd
qutip/core/data/csr.pyx

This relaxes the amount of sorting required in the `add_csr` operation.  In the current version in `dev.major`, both the left and right matrices are sorted in all cases.  This PR makes `add_csr` an `Accumulator` operation, which straight away reduces the number of sorts required to one.  Second, I add a track inside `scatter` to know whether the scatters were in sorted order; if so, there's no need to sort within `gather`, which removes the other sort from `add_csr`.
Effectively, this means that `add_csr` is O(n) when both input matrices are sorted (the most common) and O(n lg(n)) when either isn't, and we don't actually have to perform a separate test to decide between them.  In practice, this is around a 2x speedup for most common sparse matrices, and goes up from there.
I have also …

Speed up add_csr

---

qutip/cy/spmath.pyx
qutip/tests/test_spmath.py

In certain cases in matrices containing values smaller than the tolerance for Hermicity, a matrix can be considered Hermitian even if its transpose does not have the same sparsity pattern as itself.  The previous version of this function would give false negatives in these circumstances, whereas now we fall back on the more computationally and memory intensive version of constructing the transpose completely, and comparing element-wise.
We offset some of this slowdown by optimising the floating-point comparisons to avoid calls to `sqrt` (via `abs`), and by removing a redundant test of the sparsity pattern in the inner loop.
Fixes #1350 for the `master` branch, but still to do for `dev.major`.

Fix zcsr_isherm for matrices with small values

---

.coveragerc
.travis.yml

In #1339 I pointed out that the test files were being incorrectly counted in the coverage statistics when running on Travis.  This transpired to be because `coverage.py` wasn't able to find our `.coveragerc` file correctly when `pytest` was called in the manner it is on Travis.
This PR then does a couple of things:
1. correctly locates the `.coveragerc` file
2. excludes the Cython bootstrapping code from being part of the coverage
3. correctly locates the pytest configuration file `pytest.ini` (although now we have a `pyproject.toml`, we could move that configuration there)
4. completely reorganises `.travis.yml` to remove dead configs, properly share common setups, and generally make it a bit easier to read and see what's going on
5. fixes file reporting in Coveralls (look at the "tree" …

Fix coverage reporting on Travis

---

.travis.yml

Fix a testing set-up regression made in #1348 - the version of SciPy was meant to be constrained to <1.5 to test compatibility with the older version of the sparse matrices, but the version constraint got omitted when I rewrote the `.travis.yml` file.
The specific bugs that that test is meant to catch (errors handling `scipy.sparse.csr_matrix` matrix multiplication) can't be present in this branch anyway, because the new data types don't use scipy internals.  Still, it's good to test against older versions of scipy as well - in 1.5 they changed some numerics in the eigenvalue solvers, which caused a whole bunch of our tests to break because we relied on the gauge and order of the vectors returned remaining constant.

Re-add scipy<1.5 test constraint

---

.travis.yml

#1347 changed the setup of the tests, but it went unnoticed (sorry!) that the Python version wasn't set correctly; we've been silently testing everything against python-latest since then.  That wasn't an issue as long as Python 3.8 was the latest, but the release of Python 3.9 (and the fact we haven't rebuilt a binary distribution of QuTiP for 3.9) caused all Linux builds to break.  Mac builds were unaffected because they set `$_PYTHON_VERSION` to a string literal.
The Linux Python version was not set correctly because it attempted to set it to the definition of `$TRAVIS_PYTHON_VERSION` _as defined during the `env` stage of the Travis build_.  Unfortunately, this environment variable isn't defined until after that stage, which caused us to pass an empty constraint on the Python version to …

Fix setting of Python version in .travis.yml

---

qutip/_mkl/utilities.py
qutip/continuous_variables.py
qutip/control/dynamics.py
qutip/correlation.py
qutip/floquet.py
qutip/hardware_info.py
qutip/lattice.py
qutip/mcsolve.py
qutip/operators.py
qutip/orbital.py
qutip/propagator.py
qutip/random_objects.py
qutip/three_level_atom.py
qutip/wigner.py

Minor changes to correct invalid string literals and close files opened by `hardware_info.py`.
This removes warnings that currently appear when importing quTiP with non-standard warnings settings (for instance when testing a code that import quTiP).
**Changelog**
Give a short description of the PR in a few words. This will be shown in the QuTiP change log after the PR gets merged.
For example: 
Fixed invalid string literals and proporly close opened files.

Fixed invalid string literals and unclosed files

---

qutip/core/data/permute.pyx

First remove the completely unnecessary triplicated calls to `_Indexer.single()` by caching the results.  An otherwise sensible use of the sparse code would get ruined by vastly over-using the call, which is exactly what the special-case is trying to avoid.
Second, fix a buggy line: in `_dimensions_csr_sparse` there used to be the lines (229--230) that's hard to spot in the diff because of the release of the GIL in this commit:
```python
if n:
out.row_index[index.single(row) + 1] = len
```
where the assignment should have been `n`, not `len`.  `len` is the longest row seen before now, so the first row seen would also be zeroed out by this function.  Also, a matrix with some rows having more elements in that others would set the wrong values in later short rows, probably causing a …

Fix bug in permute.dimensions_csr

---

qutip/hardware_info.py

and compatible with previous syntax
Operating System: MacOS Big Sur 11.0.1
CPU: Apple M1
The syntax of output of command 
```
sysctl -n machdep.cpu.brand_string
``` 
has been changed.
The output for previous MacOS: 
```
$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz\n
```
The updated output
```
$ sysctl -n machdep.cpu.brand_string
VirtualApple @ 2.50GHz processor\n
```
Therefore, the function [`_mac_hardware_info`](https://github.com/qutip/qutip/blob/cb201690a2ca3a9c904bc642ef6600f2ef54f763/qutip/hardware_info.py#L48)  of file `hardware_info.py` cannot parse the frequency of CPU correctly.
The popped error information is attached below.
```
ValueError: could not convert string to float: ' 2.50GHz proces'
```
This pull request fix this problem …

fix parsing hardware information problem for Macbook Pro (M1 CPU/Big Sur)

---

qutip/cy/ptrace.pyx
qutip/qobj.py
qutip/tests/test_ptrace.py

1. _Non-compound Hilbert spaces_: For state `A` on a simple non-compound Hilbert space, we should have `A.ptrace(0) == A` always.  This has appeared as something useful in a few users' scripts (see #1239, #1413).  This patch fixes the underlying bug in `_ptrace_dense` which caused this to fail (even though the logic should have supported it), and adds fast-paths to the dense and sparse partial trace functions to avoid doing work if all subspaces are being kept.
Fix #1239
Fix #1413
2. _Unsorted selections_: the tracing logic already ignores the order of the selection terms, this just fixes sparse ptrace's `dims` output.
Fix #1325

Fix ptrace for unusual index selections

---

qutip/core/data/dense.pyx

Add missing flag `Dense._deallocate = True` in `Dense.copy()`; the copy operation invariably owns its own data (otherwise what's the point of a copy!).  I imagine I probably just missed this when the `_deallocate` flag was born in the midst of segfault and exception handling woes.
Fix #1415

Fix memory leak in Dense.copy()

---

qutip/core/data/csr.pyx
qutip/core/operators.py
qutip/tests/core/data/test_csr.py

Adds custom `csr.diags` and swaps `qdiags` over to use it to avoid using the `scipy` version with its large overhead.  Constructing a tridiagonal matrix of dimension 100 gets approximately a 7x speed up (320µs to 45µs on my machine) and it's better for small dimensions - the `scipy` overhead has a constant component something around 280µs compared to a constant ~20µs in the new `csr` one.  Not a big deal since it's hardly ever going to be a bottleneck, but it's just part of my work speeding up general QuTiP operations.

Fast qdiags

---

.gitignore
qutip/core/coefficient.py
qutip/core/cy/coefficient.pyx
qutip/core/cy/cqobjevo.pxd
qutip/core/cy/cqobjevo.pyx
qutip/core/data/add.pxd
qutip/core/data/add.pyx
qutip/core/data/expect.pxd
qutip/core/data/expect.pyx
qutip/core/data/matmul.pxd
qutip/core/data/matmul.pyx
qutip/core/data/mul.pxd
qutip/core/data/mul.pyx
qutip/core/data/project.pyx
qutip/core/qobj.py
qutip/core/qobjevo.py
qutip/core/qobjevofunc.py
qutip/core/superoperator.py
qutip/core/tensor.py
qutip/optionsclass.py
qutip/solve/_stochastic.pyx
qutip/tests/core/data/test_mathematics.py
qutip/tests/core/test_expect.py
qutip/tests/core/test_qobjevo.py
qutip/tests/solve/test_mesolve.py
qutip/tests/solve/test_sesolve.py

First part of rework of solver for dev.major. It allows QobjEvo to support any data types for both itself and the state. And reuse the QobjEvoFunc of #1123 so function can be used in any solver. 
- Update `cQobjEvo` to use `Data` object instead of `CSR` matrices only.
- Split `cQobjEvo.matmul` and `expect`: used to accept only `Dense` state, now accept any data type and use Jake's dispatcher. But added `matmul_dense` and `expect_dense` to do operation inplace when possible. Dispatche on `inplace` out parameter is not possible and such operation are mostly limited to `Dense`.
- Compiling string coefficients will now create the build directory in `.qutip` folder instead of current active directory.
- array coefficients addition will add array when possible.
- `scipy.special` …

Core update for solver in v5

---

qutip/qip/circuit.py
qutip/qip/scheduler.py
qutip/tests/test_scheduler.py

A gate (pulse) scheduler for quantum circuits (instructions). It schedules a `QubitCircuit` or a list of instructions to reduce the total execution time by exciting them parallelly. It uses heuristic methods mainly from https://doi.org/10.1117/12.666419. The scheduler aims at pulse schedule and therefore does not consider merging gates to reduce the gates number. It assumes that the input circuit is optimized at the gate level (e.g. has a minimal number of CNOT gates) and matches the hardware topology.
The scheduler includes two methods, "ASAP", as soon as possible, and "ALAP", as late as possible. The later is commonly used in quantum computation because of the finite lifetime of qubits.
**Methods**
- The scheduler first generates a quantum gates dependency graph, …

A quantum gate(pulse) scheduler

---

qutip/mesolve.py
qutip/tests/test_mesolve.py

In the result from `qutip.mesolve(..., c_ops=[...])`, the attribute `num_collapse` would always be 0 no matter how many `c_ops` were actually passed.  This was correct in `mcsolve`, but missing in `mesolve`.  This is likely because the result is mostly created within `_generic_ode_solve()`, but at this point the `c_ops` list has already been consumed in the creation of the Liouvillian.  There is no need to set `col_times` and `col_which` (compare mcsolve) because mesolve tracks the full density matrix, rather than following the quantum trajectory approach.
Noticed by @nathanshammah during @quantshah's talk on Twitch.
@Ericgig: to check - I assume this wasn't by design?

Correctly set num_collapse in mesolve output

---

qutip/qip/circuit_latex.py

Catch and raise the error message of the subprocess.
See https://github.com/qutip/qutip/issues/1426#issuecomment-770080582
This should fix #1426 
**Changelog**
Improve the error message of circuit plotting

Improve the error message of circuit plotting

---

qutip/tests/test_gates.py

If
```python
qutip.testing.run()
```
was called twice in the same Python session, then cases where a consumable iterator (such as `itertools.permutations` or `itertools.chain`) was used in the test parametrisation would fail on subsequent runs.  This is because the iterator is consumed when the module is loaded, and cannot be re-run after.
This was not caught in CI because naturally CI only runs the testing suite once in a session.

Fix consumable iterator in test parametrisation

---

qutip/_mkl/spmv.py
qutip/lattice.py
qutip/operators.py
qutip/piqs.py
qutip/qip/circuit.py
qutip/qip/device/processor.py
qutip/random_objects.py
qutip/states.py
qutip/tests/test_piqs.py
qutip/tests/test_qubitcircuit.py

Numpy 1.20 officially deprecated use of `np.int` and other things like `np.complex`.  These were just thin aliases to Python types anyway, so that replacement is safe.  Swap `float` and `complex` to `np.float64` and `np.complex128`; these still match Python precision (and standard double-precision floats), but more importantly we assume at all points in Cython code that we're dealing with double-precision arithmetic.  Anything else would be a larger problem for us.
In cases where `np.int` was used as a type check, we actually care more about checking for Integral typing, rather than specifically the int class; super weird constructs like
```python
isinstance(np.int64(1), int) == False
```
so taking indices out of an ndarry may lead to incorrect results when this sort of test is used. …

Remove use of deprecated numpy type aliases

---

qutip/configrc.py
qutip/settings.py

- Add the `reset` function to `qutip.settings` that is described in the documentation but was never implemented. 
- Add `save`, `load` to `qutip.settings`, allowing to save in alternate files.
- The list of configuration that can be saved in qutiprc is generated when loading the module.
- Ungraded the `configrc` functionalities to allow other filenames and support more than a few hard coded `qutip.settings`'s keys.
- Reading `qutiprc` will raise warning instead of errors when unknown keys. So if we remove keys in v5, old file will not cause crashes when importing qutip for the few that use qutiprc. 
**Changelog**
Add `reset` to `qutip.settings`

Settings reset

---

qutip/cy/brtools.pxd
qutip/cy/brtools.pyx
qutip/cy/openmp/br_omp.pxd
qutip/cy/openmp/br_omp.pyx
qutip/cy/spmath.pxd
qutip/cy/spmath.pyx

The function _safe_multiply was meant to raise a Python exception if the
integer arithmetic overflowed.  However, neither it nor several of its
call sites had the full exception-handling mechanisms enabled.
In addition, extremely large tensor products such as
tensor([basis(2, 0) for _ in [None]*31])
would segfault when using 32-bit integer arithmetic, because the size
calculation was not checked with _safe_multiply.
Fix #1406: turns the segfault into an exception.

Catch integer overflow segfault in zcsr_kron

---

pyproject.toml
qutip/continuous_variables.py
qutip/control/dynamics.py
qutip/control/pulseoptim.py
qutip/eseries.py
qutip/essolve.py
qutip/lattice.py
qutip/operators.py
qutip/propagator.py
qutip/qobj.py
qutip/simdiag.py
qutip/states.py
qutip/tests/test_three_level.py
qutip/three_level_atom.py

Fix #1433, see further discussion of points there.
- sets `Qobj.__array_ufunc__ = None` to prevent implicit usage with ufuncs
- change use of `np.array(dtype=object)` with `Qobj` into either raw Python lists (when only used internally), or sets `out = np.empty(shape, dtype=object); out[:] = ...` to force object-array creation
- fix version of numpy build version to `1.16.6 <= x < 1.20` to prevent cross-version ABI incompatibility (see also comments in #1429)
- change default of `dims` and `shape` in `Qobj` constructor to `None`, rather than dangerous lists (also helps avoid numpy calls on ragged sequences)

Fix QuTiP interaction with numpy 1.20

---

qutip/qobj.py

When called on a superoperator, the output from `Qobj.eigenstates()` would set the `dims` of the eigenstates to `[in_dims[0], [1, 1]]` rather than the correct operator-ket form `[in_dims[0], [1]]`.  This largely didn't have any knock-on effects because nothing ever used the second element, but it was still a little inconsistent with the rest of the library.

Fix dims output from Qobj.eigenstates

---

MANIFEST.in

QuTiP 4.5.3 fails to build from source distribution on PyPI, e.g. on Windows:
```
c1xx: fatal error C1083: Cannot open source file: 'qutip/cy/openmp/src/zspmv_openmp.cpp': No such file or directory
```
**Checklist**
Describe here the proposed change.
**Related …

Fix zspmv_openmp.cpp missing in srcdist

---

qutip/cy/piqs.pyx

Required due to changes in scipy 1.6.1. Using an explicit dtype will make matrix construction more robust.
Fixes qutip Issue #1451.
Tested on Debian unstable, with this patch tests/test_sparse.py now passes with scipy 1.6.1.
scipy 1.6.1 changed the API for constructing sparse matrices with `scipy.sparse.csr_matrix` (affecting the COO format). This caused qutip TestDicke tests in test_piqs.py (test_lindbladian, test_lindbladian_dims, test_liouvillian)  to fail. 
This patch avoids the problem by setting the dtype explicitly to np,complex128. 
fixes #1451
**Changelog**
Provide explicit dtype=np.complex128 when constructing sparse matrixes with csr_matrix. Required for working with scipy 1.6.1.

set explicit dtype=np.complex128 in csr_matrix

---

qutip/cy/spmatfuncs.pyx

Apparently I missed a line in a Cython file when merging #1432.

Fix old np.complex type alias in spmatfuncs.pyx

---

qutip/qip/device/processor.py
qutip/qip/noise.py
qutip/qip/pulse.py
qutip/tests/test_noise.py

The internal processing of noise is simplified. instead of adding Pulse object to the pulse list, Noisy dynamics are added to a dummy pulse object called systematic noise.
Update the test. The test was not correctly collected by `pytest`, because the name was `Test` with capital T.
**Changelog**
Improve noise processing in qutip.qip

Improve the noise module

---

qutip/qip/device/processor.py

- The plotting method is made more robust.
- Add `pulse_mode` as a wrapper for spline_kind, for discrete and continuous pulses. They are more friendly names for experimentalists.
- Add `num_qubits` as a replacement for `N`. In QuTiP capital letter are used for operators, like `H` for Hamiltonian. Due to historical reason, `N` is used in `qip` for the number of qubits. We would like to replace it with `num_qubits` in `qutip_qip`. Start from this wrapper and promoting the usage of this in notebooks guide.
**Changelog**
Minor

Improve plotting and add pulse_mode

---

.travis.yml
qutip/__init__.py
qutip/cy/pyxbuilder.py
qutip/steadystate.py
qutip/tests/test_sp_eigs.py

This fixes the calls to the `qutip.configrc` module in `qutip/__init__.py` when setting up OpenMP.
Also, this tidies up a lot of very old code out of `__init__.py` that was testing for ancient versions of SciPy and Numpy.  Since we have hard requirements at installation time for those, it's fine for us not to test their versions at initialisation.  We still should check the version of Cython because it's an optional dependency, so isn't always constrained by the package manager.
Some of the changes deliberately make `qutip/__init__.py` less forgiving of exceptions, especially when it comes to loading up `pyximport`.  This is deliberate, even though it may make a couple more errors surface that have previously gone undetected.  As it stands right now, the file will causes several errors to …

Fix OpenMP calibration and tidyup __init__

---

qutip/tests/test_brtools.py

This test would fail approximately 1 in 10 times.  I have parametrised the test case so pytest sees the different dimension runs as separate elements, which gives us better information on what's going on.
I have only seen the test fail on CI on Mac, as best as I remember, and after a bit of experimentation, I was able to reproduce the issue on my Mac at approximately the same frequency as we saw it on Travis, if I was using OpenBLAS.  I couldn't reproduce the failures with MKL, so I'm fairly sure this is to do with our use of `eig` instead of `eigh` on Mac/OpenBLAS to avoid segfaults (see #1197, #1288).  This makes some sense - the tolerances of `eig` are effectively slightly more permissive than `eigh` when dealing with real numbers, because there's more scope for an eigenvalue to be …

Fix diag_liou_mult tests

---

qutip/qobj.py

The first step of calculating the trace norm is to do `A @ A.dag()`, which we did internally in Qobj.norm.  This creates a temporary `Qobj`, and those created from `Qobj.__mul__` are subject to tidyup by default, so this temporary structure may incorrectly get tidied to the zero matrix.
For example, the code
```python
qutip.qdiags(1e-7 * np.random.rand(10), 0).norm()
```
would previously give 0, as clearly all elements of `A @ A.dag()` would be less than 1e-14, and subject to tidyup.
We avoid the call that may be tidied up by jumping straight to CSR-CSR matrix multiplication, and set `isherm=True` without going via Qobj, since the operation is Hermitian for any matrix.
Fix gh-952

Avoid matrix tidyup in trace norm

---

qutip/core/__init__.py
qutip/core/coefficient.py
qutip/core/cy/coefficient.pyx
qutip/core/cy/cqobjevo.pxd
qutip/core/cy/cqobjevo.pyx
qutip/core/cy/inter.pxd
qutip/core/cy/inter.pyx
qutip/core/data/base.pxd
qutip/core/data/base.pyx
qutip/core/data/mul.pxd
qutip/core/data/mul.pyx
qutip/core/data/norm.pxd
qutip/core/data/norm.pyx
qutip/core/qobjevofunc.py
qutip/installsettings.py
qutip/tests/core/test_coefficient.py
qutip/tests/core/test_qobjevo.py

As proposed by @hodgestar, I am splitting #1409 into smaller PRs. This is part 1/3, but contain some change in core that would come later in the Solver PR:
- Add manual cython dispatched function. Used by vern ODE method.
- Add `to` to `QobjEvoFunc` and some check. Used by brmesolve rework.
- Add a version to string Coefficient, a 'try_parsing' options, partial arguments update and basic cleaning function.
This comes mostly from talk with @jakelishman.
When updating coefficient with new argument, it no longer require all coefficient to be given, but will simply update those available. 
Since those change must overwrite old version of the coefficient, a version tag is added to the coefficient folder and a function to erase the old version. It use it's own `COEFF_VERSION`, …

Core update for solvers.

---

qutip/core/__init__.py
qutip/core/coefficient.py
qutip/core/cy/coefficient.pyx
qutip/core/cy/cqobjevo.pxd
qutip/core/cy/cqobjevo.pyx
qutip/core/data/base.pxd
qutip/core/data/base.pyx
qutip/core/data/mul.pxd
qutip/core/data/mul.pyx
qutip/core/data/norm.pxd
qutip/core/data/norm.pyx
qutip/core/qobjevofunc.py
qutip/installsettings.py
qutip/optionsclass.py
qutip/solver/__init__.py
qutip/solver/options.py
qutip/solver/parallel.py
qutip/solver/result.py
qutip/tests/core/test_coefficient.py
qutip/tests/core/test_qobjevo.py
qutip/tests/solve/test_mesolve.py
qutip/tests/solver/test_parallel.py
qutip/tests/solver/test_results.py
qutip/ui/progressbar.py

Splitting #1409, part 2/3.
Contain the non Integrator/Evoler part of the PR.
Add move some options around and add a class for ODE options. 
parallel_map and progress_bar will become options, not arguments to the `solve` function.
`store_states` default is None so that `store_states=False` is not overwritten when no e_ops given. (#1437)
With this version, the `Result` object is responsible to know if states are stored and to compute expectation values, in the method `add(t, state: Qobj)`. The solver will be responsible to create the `Qobj` for the state.
(#1460): The type of the expectation value [float, complex] is set by the `expect` function, `QobjEvo.expect` or user provided expect function. 
(#1238): Multiple callback function can be given as expectation: …

Support class for solvers

---

setup.py

The latter had the potential to cause problems when moving to cross-compilation for macosx-arm64 on conda-forge.  See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/ for more details.

Change sys.platform to sysconfig.get_platform in setup.py

---

qutip/tests/test_brtools.py

I did this previously a handful of commits ago in b7df1b5, but the
tolerances chosen there weren't ideal.
This is only especially relevant for cases where we have to use generic
eigenvalue solvers in place of Hermitian ones (e.g. when the Hermitian
ones have temperamental segfaults).  I ran test_diag_liou_mult for all
dimensions from 2 to 99 inclusive 2000 times, and measured the maximum
absolute and relative tolerance for each case.  I found that 3 times out
of 2000 the absolute tolerance exceeded 1e-10, and 12 times out of 2000
the relative tolerance exceeded 1e-7.  The max values seen were 4.24e-10
and 3.12e-7 respectively.
This updates the tolerances to 1e-9 (absolute) and 1e-6 (relative),
which still seem like reasonable tolerances, and should ensure that
we're testing correctly.
See …

Update diag_liou_mult test tolerances

---

qutip/qip/compiler/cavityqedcompiler.py
qutip/qip/compiler/gatecompiler.py
qutip/qip/compiler/instruction.py
qutip/qip/compiler/scheduler.py
qutip/qip/compiler/spinchaincompiler.py
qutip/qip/device/cavityqed.py
qutip/qip/device/modelprocessor.py
qutip/qip/device/optpulseprocessor.py
qutip/qip/device/processor.py
qutip/qip/device/spinchain.py
qutip/qip/noise.py
qutip/qip/pulse.py
qutip/qip/scheduler.py
qutip/tests/test_compiler.py
qutip/tests/test_device.py
qutip/tests/test_noise.py
qutip/tests/test_processor.py
qutip/tests/test_scheduler.py

- Integrate scheduler into the compiler. The compiler can now schedule quantum gates to reduce the duration of the compiled pulses.
- Improve the structure and readability of the `Compiler` class. The compiler class was separated for clarity when the `Processor` class was built upon old code in `qutip.qip`. But it has never been opened as a public API. This PR improves the readability and, most importantly, makes it easier for users to customize the compiler class.
- Add a map `pulse_dict` between the pulse label and the indices in `Processor`, so that customizing class becomes much easier.
**Files description**
- `scheduler.py` is moved to compiler folder and split to two files : `instruction.py` and `scheduler.py` for clarity.
- Changes in `gatecompiler.py`, …

Integrate scheduler into the compiler

---

.travis.yml
qutip/metrics.py
qutip/tests/test_metrics.py
setup.cfg

dnorm tests have historically been very flaky, and for as long as we're using random tests (which we possibly shouldn't be), we always run the risk of temperamental failures.  In particular, the semidefinite solvers used in dnorm fail every now and again on random states; we historically haven't treated this as a bug, since it's pretty similar to an integration failing to converge because the system was too stiff.  It means that the user has to adjust some settings and try again.
To prevent this sort of error from failing our test suite, however, we can mark the tests as being allowed to rerun twice on a failure.  We had a relatively small sample to judge the test failure rate by, but my very very approximate guess is that we'd have a failure about 1 in 10 runs on Travis.  We counter this …

Allow rerunning of dnorm tests, refactor test_metrics.py

---

qutip/correlation.py
qutip/eseries.py
qutip/essolve.py
qutip/tests/test_qubit_evolution.py

These are to be removed in QuTiP 5.0.  We use `FutureWarning` rather than `DeprecationWarning` because a lot (most?) QuTiP users run interactively in notebooks, which generally filter out the latter.  *edit*: changed to `DeprecationWarning` after review.
The "es" solver options in correlation gain warning filters, because they aren't being removed in 5.0; the small parts of functionality they need is just being folded into private helpers within the module.
The legacy correlation API had its deprecation warnings issued in 2014...  But nonetheless, we shouldn't actually remove functionality until a major release.
See fe5ef7d, d9ea79a for more details around the removals that have already been merged into `dev.major`.
Fix #1281

Issue DeprecationWarning for eseries, essolve and ode2es

---

qutip/correlation.py
qutip/mesolve.py
qutip/tests/test_correlation.py
qutip/tests/test_mesolve.py

The function mesolve was not including the complex part of the expectation value when the initial state was a not Hermitian. This led to an error in `correlation_2op_1t()` which uses an initial state that is not Hermitian to compute the correlation.
I also fixed an error in the documentation where `tlist` was referenced instead of `taulist` (`tlist` is not an argument in `correlation_2op_1t()`) and included a test for `correlation_2op_1t()`.
Fix #1460
**Changelog**
Fixed error where complex expectation value for non Hermitian initial state was not being included in results when using mesolve.
Fix doxumentation error in `correlation_2op_1t()`.
Added test for `correlation_2op_1t()`.

Issue#1460

---

qutip/bloch.py
qutip/control/dump.py
qutip/control/dynamics.py
qutip/control/optimizer.py
qutip/control/propcomp.py
qutip/control/pulseoptim.py
qutip/eseries.py
qutip/essolve.py
qutip/lattice.py
qutip/measurement.py
qutip/nonmarkov/heom.py
qutip/piqs.py
qutip/qip/device/optpulseprocessor.py
qutip/qip/device/processor.py
qutip/qip/pulse.py
qutip/qobj.py
qutip/qobjevo.py
qutip/random_objects.py
qutip/sesolve.py
qutip/solver.py
qutip/states.py
qutip/steadystate.py
qutip/stochastic.py
qutip/visualization.py

This isn't a complete "fix" of every piece of bad formatting in the API documentation that we're building, but it does fix every warning that Sphinx produces in both the `html` and `latexpdf` targets.
It's quite a big patch, but there's no meaningful changes, only formatting ones - I haven't attempted to actually change the meaning of any of the writing, only to reformat it.  If we want to make any changes to any of the docstrings, we can do that in separate patches.  My intent is to merge this in as the very final patch in the 4.6 release, since it's useful for doing the documentation release.
See also qutip/qutip-doc#136

Fix improperly formed docstrings

---

qutip/bloch.py

Matplotlib stopped to stretch the plot to fit it in a square box from 3.3.0. We do it manually. See https://matplotlib.org/3.3.0/users/whats_new.html#d-axes-improvements
To reproduce 
```python
import numpy as np
from qutip import Bloch
b = Bloch()
xp = [np.cos(th) for th in np.linspace(0, 2*np.pi, 20)]
yp = [np.sin(th) for th in np.linspace(0, 2*np.pi, 20)]
zp = np.zeros(20)
pnts = [xp, yp, zp]
b.add_points(pnts)
b.show()
```
before:
after:
fix #1385
**Changelog**
Fix Bloch sphere distortion

Fix Bloch sphere distortion

---

qutip/__init__.py
qutip/tests/test_sp_eigs.py
qutip/tests/test_superop_reps.py
requirements.txt
setup.cfg

Setting eigh_unsafe on sipy<1.5 and  MKL
#1495
**Changelog**
- Changed init to set eigh not safe in case scipy<1.5 and mkl backend
- Added the correct pytest breaking test from issue #1491 to check the solution

Scipy<1.5 and mkl eigenh problem solved

---

qutip/correlation.py
qutip/nonmarkov/memorycascade.py
qutip/nonmarkov/transfertensor.py
qutip/piqs.py
qutip/wigner.py

There were a few invalid escape sequences and scipy imports that somehow escaped being fixed #1493, so this fixes those.
Also, in #1480 we issued deprecation warnings for user-facing uses of `eseries`, `essolve` and `ode2es`, however we are not deprecating the correlation and spectrum methods (in QuTiP 5.0 the necessary components are just absorbed into private functions inside `correlation.py`), so these should not generate warnings.  Simon (@hodgestar) and I briefly discussed whether we needed a special warnings filter inside those functions, but we thought we didn't need it because default Python filters would prevent `DeprecationWarning` from being shown, since it is triggered by library code and not code in `__main__`.
The problem is that not everything uses the default filters; both …

Fix more warnings in documentation build

---

.travis.yml
qutip/control/optimizer.py
qutip/cy/pyxbuilder.py
qutip/essolve.py
qutip/fastsparse.py
qutip/fileio.py
qutip/floquet.py
qutip/metrics.py
qutip/piqs.py
qutip/qip/operations/__init__.py
qutip/qip/qasm.py
qutip/qobj.py
qutip/random_objects.py
qutip/semidefinite.py
qutip/sparse.py
qutip/steadystate.py
qutip/subsystem_apply.py
qutip/superop_reps.py
qutip/tests/test_device.py
qutip/tests/test_piqs.py
qutip/tests/test_qasm.py
qutip/tests/test_qobj.py
qutip/tests/test_rand.py
qutip/tests/test_subsys_apply.py
qutip/tests/test_superop_reps.py
qutip/tests/test_superoper.py
qutip/visualization.py

This PR fixes every warning reported in `pytest`, and then makes `pytest` treat warnings as errors to hopefully make sure we stick to this state of affairs.  (Or at least it fixes all the ones that appear on my particular machine...)
The reason this is desirable is that it means we cannot ignore deprecation warnings in dependencies or even in our own code.  It also helps us not let certain parts of the codebase get lost in the sands of time, or at least compels us to do something about potential problems before they actually become catastrophic.  This is _somewhat_ of a trial, though I hope we can stick to it; warnings usually indicate that something's wrong.
Tests can still test run code that generates warnings, but you now have to mark it explicitly in `pytest`.  This doesn't mean you …

Fix test warnings

---

setup.cfg

This makes a `qutip[full]` target for pip, to make it easier to install qutip and all its optional dependencies.

Add [full] target to get all optional dependencies

---

qutip/random_objects.py
qutip/tests/test_random.py

Fixes #1504 and changes signature of `rand_ket` as [requested](https://github.com/qutip/qutip/issues/1504#issuecomment-823455134). 
Added tests to check behavior of `rand_ket` by checking shape of output when -  both N and dims are specified,  only dims is specified and finally only N is specified. 
**Changelog**
Fixes typo in random objects and changes signature of rand_ket

Changes signature of rand_ket

---

doc/changelog.rst

This is the changelog for 4.6.1 that we forgot to merge when we made the actual release.

Changelog for 4.6.1

---

qutip/piqs.py

Using integer-like floats in `math.factorial` is deprecated as of Python 3.9.
Glancing over the rest of the code, I'm fairly sure `math.factorial` is only called on floats formed by (e.g.) `N / 2 + 0.5`, which is guaranteed be an integer for all odd `N` integers, but to be safe I inserted the same test that `math.factorial` will do as well.
By the way: depending on how accurate you actually want/need to be with your degeneracy calculations, a common way to deal with these binomial quantities is to work in the logarithmic space --
```python
def factln(x):
return scipy.special.gammaln(x + 1)
def energy_degeneracy(N, m):
return int(np.exp(Decimal(factln(N) - factln(N/2 + m) - factln(N/2 - m))))
```
This is pretty much guaranteed to be faster, but a little less precise; double-precision …

Enforce int types in math.factorial

---

doc/development/release_distribution.rst

Simon managed the 4.6.1 release using the current version of the release documentation, and we identified lots of places where it wasn't as clear as it could have been.  This is a new pass at the same documentation trying to improve it.
There are points of the website and documentation procedures that we want to update as well, but at the moment we're just trying to document what you do _right now_.

Rewrite entire git procedure for release

---

CONTRIBUTING.md

This file has been added and removed a few times, but GitHub likes it if
we have it.  The main contributing guidelines remain in the actual
documentation, so this just replicates the readme and points to the main
version.
I think the UnitaryHack guidelines say we should have it, too.

Re-add contributing file

---

doc/apidoc/functions.rst
qutip/entropy.py
qutip/tests/test_entropy.py

Re-implement entropy_relative.
This function was implemented in March 2012, but then removed a month later. After some digging, it appears that the reason the function was removed is that it assumed the eigenvectors of the density matrices were identical (and in the same order).
After some reading of Nielsen & Chuang, I have re-implemented it to address the issue.
**Still todo**
**Changelog**
Re-implement entropy_relative which returns the quantum relative entropy between two density matrices.

Re-implement entropy_relative.

---

doc/guide/guide-bloch.rst

Description
Fixes TypeError: 'Axes3D' object is not iterable when running the code from the tutorial.
Related issues or PRs
#1557 
Changelog
Fixed runtime error in http://qutip.org/docs/latest/guide/guide-bloch.html#generating-images-for-animation

Fix Axes3D object is not iterable [unitaryHACK]

---

doc/guide/guide-bloch.rst

This PR attempts to solve the error in the `ffmpeg` command from the user guide. Specifically, the bitrate parameter (-b) is applied to the output file `bloch.mp4`. Additionally, a one line change to use `Bloch` from `qutip` has been made which otherwise returns an error.
Thanks!
Fix #799 
**Changelog**
Fixed error in the `ffmpeg` command from the user guide.

Fix ffmpeg error [unitaryHACK]

---

doc/guide/guide-bloch.rst
qutip/bloch.py
qutip/visualization.py

This PR attempts to add version checks for resolving deprecation warnings for `matplotlib` in the `bloch` and `visualization` modules. Specifically, it attempts to resolve warnings related to `matplotlib>=3.4` and `matplotlib>=3.3`.
Places where the change has been made:
- `proj3d.proj_transform`
- `Axes3D`
Thanks!
Fix #1503 and #1502.
**Changelog**
Added a version checking condition to handle specific functionalities depending on the `matplotlib` version.

Version checks for `matplotlib` [unitaryHACK]

---

qutip/core/cy/cqobjevo.pyx
qutip/core/data/__init__.py
qutip/core/data/_creator_utils.py
qutip/core/data/convert.pyx
qutip/core/data/csr.pyx
qutip/core/data/dense.pyx
qutip/core/data/dispatch.pyx
qutip/core/data/make.py
qutip/core/operators.py
qutip/core/qobj.py
qutip/core/qobjevo.py
qutip/core/states.py
qutip/core/superop_reps.py
qutip/random_objects.py
qutip/tests/core/data/test_convert.py
qutip/tests/core/data/test_csr.py
qutip/tests/core/data/test_dense.py
qutip/tests/core/test_operators.py
qutip/tests/core/test_qobjevo.py
qutip/tests/core/test_states.py
qutip/tests/core/test_superoper.py
qutip/tests/test_random.py

Qobj support Dense representation, but there are still no easy way to create dense matrix. So this add a keyword only `dtype` options to most function of qutip.states, qutip.operators and qutip.random_object.
To make them, I made 2 new dispatched function: `diag` and `one_element`. `diag` has the same use than @jakelishman #1419 function, but I fall back on scipy quickly... So I will switch to his version as soon as it is merged. 
To make the `dtype` more user friendly than seeking the type in `qutip.core.data`, I changed `to` to accept the string representation of the name (case insensitive). Only `to` accept string, `dispatch` is not really user facing so there is no reason to touch it.
I also updated the `create` to use `add_creators` and make `Dense` out of `numpy …

Add type choice in Qobj creation function.

---

doc/guide/guide-states.rst

The word "then" is mistyped in the sentence "If the operator is Hermitian, **than** the output will always be real".
None.
**Changelog**
Corrected typo in Guide / Manipulating States and Operators.

Correct typo in guide-states.rst

---

qutip/control/pulsegen.py
qutip/mcsolve.py
qutip/random_objects.py
qutip/stochastic.py

Some minor pep8 fixes in files I might touch soon with regards to moving to the Numpy 1.17 random-number generation.  There's a bunch of seemingly dead code in `mcsolve` about a "diagonal" system?  Seems to have a few logic bugs in it at the very least, and no way to access it.  I fixed one about `e_ops`, but looking at the log, seems like the whole system might not be needed.
**Changelog**: pep8 changes.

Tidy up pep8 and minor logic bugs

---

.codeclimate.yml

The plugin was already enabled by default, so this does not turn it on. However, it also defaults to Python 2, which means it produces a lot of syntax errors, and the run (silently) failed every time.
This may cause our CodeClimate score to drop, not because we actually got worse, but because we suddenly start seeing a load of duplication that was previously hidden.  I'm hoping that getting these parser errors fixed will mean that the "Progress report" tab on CodeClimate will start getting populated.
**Changelog**: (developer changes) fixed Python version for duplication detection in CodeClimate

Fix CodeClimate duplication parser version

---

README.md

We don't use Travis CI any more.
**Changelog**: change README badge to point to GitHub Actions, not Travis

Convert README CI badge to GitHub Actions

---

qutip/qip/circuit_latex.py

This file included GPL'd code, which is incompatible with QuTiP's 3-clause BSD licence.  Instead, we rely on the user to have a functional install of the file (it's been included in TeXLive since at least 2014).
See qutip/qutip#1579
**Changelog**: removed vendored version of LaTeX package `qcircuit`

Remove vendored Qcircuit.tex

---

qutip/_pyxbuilder.py

`pyximport` raises a deprecation warning due to importing `imp` instead of `importlib`. I silenced it.  It was causing some problem in qutip-tensorflow testing as all warnings are treated as errors. Let me know if I should have proceeded in a different way. 
**Changelog**
Silenced deprecation warning from `pyximport`.

Silenced deprecation warning from pyximport.

---

qutip/core/data/base.pyx
qutip/tests/core/data/test_convert.py

Being unable the set the shape is the main constrain in making a new python only data layer.
This allow `Data.__init__` to set it.

Data.__init__ set shape

---

qutip/propagator.py
qutip/tests/test_propagator.py

A lot of the code in `propagators.py` is quite old and manipulates `Qobj` shapes directly and unnecessarily converts backwards and forward between numpy arrays and `Qobj`s. This PR attempts to address two important bugs in dimension checking -- the one reported in #1585 (when calculating propagators for collapse operators) and another I found while reading the nearby code. A more thorough rework of the code should probably happen on `dev.major` for QuTiP version 5.
The `propagator` method could do with more input sanity checking for QuTiP version 5, e.g.
* rename `c_op_list` to `c_ops` for consistency with the solver
* complain if `c_ops` are supplied along with a superoperator (?)
* perhaps remove the `single` or `batch` unitary_mode option, or at least complain if the …

Fix dimensions in calls to mesolve when calculating propagators for superoperators or with collapse operators present.

---

qutip/random_objects.py

`seed` is no longer ignored when `pure=True` for `rand_dm`
fix #1598

Seed is no longer ignored when pure=True for rand_dm

---

qutip/operators.py

The algorithm used in `enr_destroy` was extremely inefficient, with a triple loop. This PR replaces it with a much simpler algorithm with only a single loop. For `dims = [3,8,2,4,6,1,3]` and `Nexc = 6`, on my computer `enr_destroy(dims,Nexc)` took almost 4 s, with the new algorithm it takes 20 ms. I've checked that the output is identical.
**Changelog**
Made enr_destroy significantly faster.

faster algorithm for enr_destroy

---

qutip/qip/device/processor.py
qutip/tests/test_processor.py

In the analytical calculation of the circuit unitaries in `Processor`, the drift Hamiltonian was missing. Add it and add a test accordingly. Also fix a wrong docstring.
fix #1602 
**Changelog**
Add the missing drift Hamiltonian to the method `run_analytically` of `Processor`

Add the missing drift Hamiltonian to the method `run_analytically` of `Processor`

---

qutip/states.py

When the number of excitations in `state_number_enumerate` is limited, instead of iterating over all states and discarding the ones with too many excitations, directly choose the limits to only iterate over allowed states. As a small additional optimization, do not redo the same sum every time, but keep track of the sum within the algorithm. For the tests I've made, this is a factor of ~4-10 faster than the current version. Together with #1593, this reduces the runtime of `enr_destroy` (which uses `state_number_enumerate`) from almost 4s to 15 ms for the case I just treated, and another much bigger case takes 2.5 s now, while it hadn't finished after more than an hour with the previous version.
Note that since the two PRs (this one and #1593) are somewhat related, it might …

faster state_number_enumerate

---

qutip/states.py
qutip/tests/test_enr_state_operator.py
qutip/tests/test_operators.py
qutip/tests/test_states.py

Add tests for previously untested function in states and operators and parametrize some of the existing tests.
Should improve the coverall by about 100 lines.
**Changelog**
Improve test coverage of states and operators functions.

Improve coverage of states and operators tests

---

qutip/core/cy/cqobjevo.pyx
qutip/core/qobj.py
qutip/core/superoperator.py
qutip/tests/core/test_qobj.py
qutip/tests/core/test_superoper.py

Set `operator-ket`'s `superrep` to `'super'`.
`operator-ket` are the states of super operators, ie. `super @ operator-ket` make sense but `oper @ operator-ket` does not. So it is natural that they have an attached `superrep`. This will make `choi_super @ operator-ket` error unless care is taken in making the `superrep` match.
TODO? Have `to_choi`, etc. work for operator-kets?
closes #1586

Set `superrep` for operator-ket and operator-bra.

---

qutip/control/dynamics.py
qutip/core/data/__init__.py
qutip/core/data/eigen.py
qutip/core/data/linalg.py
qutip/core/data/reshape.pyx
qutip/core/qobj.py
qutip/tests/core/data/test_mathematics.py

Change `data.eigs` evecs output to a Data object instead of a `ndarray`. This will be useful for `tensorflow` for which `eigh` output is a tensor. `Qobj.eigenstate` have been reworked to use the dispatcher or `eigs_csr`. `eigs_csr` do not have the same signature s `eigs.data`, so it is still called directly.
This had side effect in `Qobj.sqrtm` which was rewritten to work with `Data` instead of `ndarray`.
2 new dispatched functions are added:
`split_columns`: Used in `Qobj.eigenstates`, split each cols into a list of ket shaped Data.
`inv`: matrix inverse.

Change eigs eigenvector output to Data instead of ndarray

---

doc/apidoc/classes.rst
doc/guide/guide-visualization.rst
qutip/tests/test_wigner.py
qutip/wigner.py

This is a tidied up and completed version of #934.  The first commit is credited to the original author (although I fixed up some little concerns in the PR and rebased it), because it's logically built off that PR, although in the end it's a complete reimplementation.
This is a complete rewrite of the Husimi Q calculations, to make a more formal split between the iterative (low-memory) and precomputed (faster) algorithms, giving full access to both of them.  It's a bit easier to use from a user's perspective, and it's faster than #934 as well.
The concept of the precomputed matrix is encapsulated into a class with a cached tensor, so that the same precomputed system can be used for many states of different sizes, and autoexpands (up to the memory limit) to accommodate larger states.  This …

Faster Husimi Q with saved state

---

qutip/core/qobj.py
qutip/tests/core/test_qobj.py

Qobj's copy argument was not being passed to create dispatcher. This resulted in a copy of `data` regardless of the `copy` argument when `data` was not an instance of `data.Data` or `Qobj`.
Example (I am using here qutip-tensorflow as I do not know how this translates into numpys ndarray, see comment below):
```python
tfconstant = tf.constant(np.random.random((2,2))) # random tensor
qobj = qutip.Qobj(tfconstant, copy=False) 
print(qobj.data._tf is not tfconstant) # True but should be False
```
**Changelog**
Copy argument is now handled correctly.

Fixed bug where copy argument was not being passed to create dispatcher.

---

qutip/core/data/properties.pyx
qutip/tests/core/data/test_properties.py

Fix a couple of incorrect attribute accesses in `_isherm_csr_full`, which were incorrectly merged up from `master` - they refer to the old SciPy names for the fields, rather than the new `CSR` type names.  This wasn't caught at the time because the tests hadn't been merged up yet, so I've written those as well.
**Changelog**
- Fix typos in `isherm_csr`
- Add tests of `isherm` for all data types.

Fix bad attribute accesses in isherm_csr

---

qutip/operators.py
qutip/states.py

Speed up and simplify `state_number_enumerate`, `state_number_index`, `state_index_number`, `state_number_qobj`, and `enr_state_dictionaries`. I've changed quite a few functions in states.py, but all the changes are small. It seemed easier to combine this into a single pull request instead of splitting it up into many smaller ones (but this could be done).
The changes in more detail:
- `state_number_enumerate` and `state_index_number` now always return tuples. Before, `state_number_enumerate` returned arrays for `excitations is None` and tuples otherwise, and `state_index_number` returned a list. For `excitations is None`, I realized that a simple call to `itertools.product` is enough, and is about 20x faster for a (relatively big) test case. It would be trivial to keep …

improvements in state_number handling

---

qutip/core/data/eigen.py

Added clarification for what `low` and `high` mean when sorting eigenvalues.

Added clarification in eigen docstring.

---

qutip/core/data/expect.pyx
qutip/tests/core/data/test_expect.py

Added tests for expect specialisations. The tests follow the structure in `test_mathematics` which helps developing new data 
**Notes**
I changed the logic in `expect.pyx` to also raise `ValuError` when op is not a square matrix. `expect_csr` was crashing with a segment fault when passing a nonsquare matrix as `op`.  I am not sure why this error was not being caught by the tests for `qutip.expect`. I guess this function does some check to the Qobj given as argument.

Added expect tests for data layer.

---

qutip/core/data/pow.pyx
qutip/tests/core/data/test_mathematics.py

Added tests for pow specialisation. I also changed the raised error to `ValueError` to be consistent with the rest of the specialisations (and in particular with trace that also raises `ValueError` if input matrix is not square). 
The tests do not contemplate the cases where:
- n is not an integer (float): Float is cast to integer so: `pow_csr(matrix, 0.1) == pow_csr(matrix, 0)`. We may want to raise `TypeError` instead.
- n is not positive: `OverflowError` is raised instead of `TypeError`. This is due to how Cython works but we may want to raise TypeError for consistency with the rest of the code.
For instance, raising `TypeError` in these cases is what NumPy does. What should we do?
None
**Changelog**
Give a short description of the PR in a few …

Pow tests for data layer.

---

qutip/visualization.py

`matrix_histogram` is much more eye-catching and has more options for syling:
1- zticks: ticks for z-axis
2- cmap: used colormap
3- cmap_min and cmap_max: truncating a portion of a colormap is now possible
4- bars_spacing: spacing between bars can be changed
5- bars_alpha: alpha channel of bars can be changed
6- bars_lw: bars' linewidth can be changed
7- bars_edgecolor: bars' color can be changed
8- shade: it's possible to turn on and off the shading
9- azimuthal and elevation angles can be changed
10- stick: bars can stick to xz and yz planes (z values can be read more easily)
11- cbar_pad: padding between the figure and the colorbar can be changed
12- proj_type: projection type can be changed to either 'perspective' or 'orthogonal'
13- xticks and yticks are now perfectly …

matrix_histogram updated - imporved the styling options

---

qutip/visualization.py

#1573 introduced a bug in matrix_histogram. If no styling options are passed it raises a ValueError. After this change, matrix_histogram uses the default options instead.
Fixes a bug introduced in #1573.
**Changelog**
Fixed handling of style options=None (the default) in matrix_histogram.

Fix handling of options=None in matrix_histogram.

---

qutip/control/dynamics.py
qutip/control/propcomp.py
qutip/tests/test_control_pulseoptim.py

Currently qutip.control.optimize_pulse supports four formats for `oper_dtype` (i.e. its internal representation of propagators and intermediate states). The four formats and their statuses before this PR are described below:
- `numpy.ndarray`: Working.
- `Qobj`: Working, except that some dimensions were lost in Qobj construction and using sparse eigenvector decomposition was broken.
- `scipy.sparse.csr_matrix`: Broken. There was an undefined variable referenced in the code to construct the propagators. Many code paths had no explicit support for them and assumed they worked the same as ndarrays in cases where they didn't.
- `anything matrix-like`: Broken for the same reasons as `csr_matrix` above.
This PR removes support for last two oper_dtypes and fixes the `Qobj` one, leaving the …

Clean up pulse optimization sparse solving support.

---

qutip/core/qobj.py
qutip/tests/core/test_qobj.py

I changed __mul__ behaviour following the discussion of issue #1607. However, the implementation details differ slightly from what was discussed there. The current behaviout of `__mul__(self, other)` is:
- If other is a `Qobj`: dispatch to `__matmul__`
- If not try dipatching to mul and return `NotImplemented` if `TypeError` is returned.
- The dispatcher now gets `other` instead of `complex(other)`. This is more flexible and allows specialisations to handle arbitrary scalar like objects (something extremely useful for qutip-tensorflow).
- Infer hermiticity and unitarity when possible trying complex(other)
`__rmul__` now directly dispatches to `__mul__`. Any necessary check (casting to complex included) is done in `__mul__`.
_No_ changes were required to `mul_dense` and …

Changed __mul__ behviour to be more flexible and consistent.

---

qutip/core/data/expm.py
qutip/core/data/project.pyx
qutip/tests/core/data/test_mathematics.py

This adds a few more tests to the specialisations. I also found a Bug in expm and changed `TypeError` to `ValueError`.
- Expm: 
- Added tests for its specialisations.
- There was a _bug_ in expm where if the matrix was csr and diagonal, zero values where not being exponentiated as they did not appear in scipy's data attribute. This case is now handled properly with the same scaling in resources (O(N) where N is the non-cero diagonal elements in the matrix).
- Incorrect shape now raises ValueError.
- UnaryOpMixin: 
- It did not check for bad shapes. It now does have a function that checks for them (this avoids code duplication in `trace`, `expm` and some others). 
- As a result of this change a hidden bug emerged: even though `TestProject` had a non-empty `bad_shapes` …

Expm and  project tests.

---

qutip/tests/core/data/test_mathematics.py
qutip/tests/core/data/test_reshape.py

**Changelog**
Added tests for reshape specialisations.
Added tests for columns_stack specialisations.
Added tests for columns_unstack specialisations.
Moved tests for split_columns from test_mathematics to test_reshape.
PEP 8 clean test_mathematics.

Test reshape specialisations.

---

qutip/tests/core/data/test_mathematics.py

Remove unnecessary use of scipy.sparse in test_mathematics.
* Fixes the small issue raised by @jakelishman in https://github.com/qutip/qutip/pull/1630#pullrequestreview-723426389 post merge.
**Changelog**
Remove unnecessary use of scipy.sparse in test_mathematics.

Remove unnecessary use of scipy.sparse in test_mathematics.

---

qutip/tests/test_interpolate.py

In `test_interpolate`, `qzero` was used as `mcsolve`'s collapse operator. Due to numerical error in the interpolation method, `mcsolve` can detect a collapse, but a collapse for a null operator cause a a division by zero. This sometime made our tests fails.
By changing the collapse operator to `qeye`, the evolution, thus the test is unaffected, but it no longer randomly fail.

Fix test_interpolate mcsolve use.

---

qutip/tests/test_processor.py

Close figure plots explicitly during tests so that the test suite passes when run headless under Xvfb.
* fixes #1639
* see https://github.com/The-Compiler/pytest-xvfb/issues/11 for the discussion of this situation when using pytest-xvfb
**Changelog**
Close figure plots explicitly during tests so that the test suite passes when run headless under Xvfb.

Close matplotlib figure windows cleanly in tests.

---

qutip/qip/circuit.py

The `num_cbits` wasn't documented in the QubitCircuit docstring. This adds it.
Took me a second to figure out what it was (as a novice in quantum computing), so I figured I'd save some other novice that second.
FWIW: `reverse_states` isn't documented either, but I'm not confident I can write an accurate description of what that is, otherwise I would have put it here too.
This library is really neat! Thanks to all who are developing and maintaining it! 
**Changelog**
Add docs for `num_cbits` in QubitCircuit docstring

Minor doc fix in QubitCircuit

---

qutip/core/data/csr.pyx
qutip/core/data/dense.pyx
qutip/core/operators.py
qutip/core/qobj.py
qutip/core/superop_reps.py
qutip/core/superoperator.py
qutip/random_objects.py
qutip/solve/_mcsolve.pyx
qutip/solve/countstat.py
qutip/solve/mcsolve.py
qutip/solve/mesolve.py
qutip/solve/nonmarkov/heom.py
qutip/solve/sesolve.py
qutip/solve/steadystate.py
qutip/tests/core/data/test_properties.py

We presently support operator in data layer including binary operators with themselves (`CSR + CSR`). But we use them sometime without confirming that both data object are of the same type, which will eventually cause bugs.
Here I remove this support and fixed many places were we used them, but there are probably some uses remaining in place not covered by tests.
This is an alternative solution to the issue from #1647.

Remove operator in data-layers

---

qutip/tests/test_qubitcircuit.py

Fix the test breaking dev.major by adding the tolerance in the test itself.
This is an alternative to #1656, merge only one.

fix failing circuit test

---

qutip/tests/test_wigner.py
qutip/wigner.py

- Fixed some errors in the transcription of the husimi Q and Wigner W functions for spins into code.
- Ensure Q and W functions are normalized over (theta, phi).
- Add tests for correctness and normalization of spin Q function.
- Add tests for normalization and real-ness of spin W function. Correctness is established by comparing the overlap of two states and the overlap of their Wigner functions.
- Spin Q function tests take ~11s to complete, spin Wigner tests take ~10s to complete on my laptop.
**To do**
This issue was raised in another PR #1195 which didn't resolve this issue as intended. The original issue this fixes was #1128.
**Changelog**
Fixed error for calculation of Husimi `spin_q_function` and `spin_wigner`.
Added tests to …

Fix bugs in spin_q_function and spin_wigner, add test cases

---

qutip/tests/solve/test_stochastic_me.py
qutip/tests/solve/test_stochastic_se.py

Some tests in stochastic evolution passes only most of the time.
The problematic tests are comparison of different step length, normally error should be smaller with smaller step length. Since the evolution use random number, this is not true for all seeds.
By fixing the test, we should not have the tests randomly failing.
I am adding _improving stochastic tests and having them use pytest_ to my to-do.
Ps. tests fail due to the error fixed in #1656

fix seeds in stochastic tests 

---

qutip/core/coefficient.py
qutip/core/cy/_element.pxd
qutip/core/cy/_element.pyx
qutip/core/cy/coefficient.pyx
qutip/core/cy/qobjevo.pyx
qutip/core/options.py
qutip/tests/core/test_coefficient.py
qutip/tests/solve/test_correlation.py
qutip/tests/solve/test_mesolve.py

Allow function-based Coefficients and QobjEvo elements to support functions with more natural argument signatures like `f(t, w)` or `f(t, **kw)` in addition to the old `f(t, args)` signature. The old style signature is used if the arguments to the function are exactly `(t, args)`. Otherwise the new calling convention is used.
This PR also limits the arguments stored to those accepted by the function, potentially reducing some extra copies of functions when `.replace_arguments()` is called.
This is an alternative implementation of #1609. This implementation retains single FunctionCoefficient and _FuncElement classes and simplifies the logic for deciding whether the old or new-style calling convention is used.
**Changelog**
Allow function-based …

Allow f(t, **args) as coefficient function alternative (alternative approach)

---

doc/guide/dynamics/dynamics-floquet.rst

Fix the parameters in the call to fsesolve in the floquet guide. The fsesolve parameters were updated at some point, but the guide wasn't.
Fixes #1663 
**Changelog**
Fixed the parameters in the call to fsesolve in the floquet guide.

Fix parameters in call to fsesolve.

---

qutip/cy/mcsolve.pyx

Presently `mcsolve` always save the final state of all trajectories, needed or not.
With this PR, it will only save them when needed.
closes #1667
**Changelog**
Improve mscolve memory efficiency when states are not needed.

Make mcsolve more memory efficient

---

doc/guide/dynamics/dynamics-monte.rst

The mcsolve guide incorrectly describes how random numbers are generated when determining jump locations and collapses.
* Fixes #1666
**Changelog**
Fix the description of random number usage in the Monte Carlo solver guide.

Improve description of random number generation in mcsolve guide.

---

doc/contributors.rst
qutip/mesolve.py
qutip/sesolve.py
qutip/solver.py
qutip/tests/test_expect.py

I propose to make it possible to have callable functions inside of the `e_ops` list, not only operators. This becomes useful if we want to measure energy or if we want to have time-dependent measurements just like time-dependent Hamiltonian.
Changes are pretty straightforwards, mostly making sure types match. Important design choice is, if measurement is not an operator but a function, the data type is complex by default (to handle the general case).
Feedback and suggestions for changes are welcome. I will be happy to contribute more!
Suggested in https://github.com/qutip/qutip/issues/1238
**Changelog**
1. Modified `mesolve` and `sesolve` objects to handle callable function inside of the `e_ops` list.
2. Prepared `solver` to create empty measured …

implemented a possibility of mixing measurement operators and callback functions in e_ops list

---

qutip/core/data/eigen.py
qutip/core/data/norm.pyx
qutip/tests/core/data/test_norm.py

**Changelog**
Added specialisations for norm.
`TraceNorm` now uses `scipy.linalg.norm` with `ord='nuc` by default (sparse=False).
Fixed bug for `eigs_sparse` where if the shape was less than 4 it called with wrong arguments to `eigs_dense`.

Norm tests for specialisations.

---

doc/apidoc/functions.rst
qutip/tests/test_utilities.py
qutip/utilities.py

Update tests in `test_utilities.py` to `pytest` and add test for previouly untested function.
I removed 2 functions:
`linspace_with`: never used, almost equivalent to `np.linspace`.
`view_methods`: supposed to print methods of a `Qobj`, but broken...
**Changelog**
Update tests in test_utilities.py to pytest.
Remove broken qutip.utilities.view_methods.
Remove qutip.utilities.linspace_with (use numpy.linspace instead).

Change test_utilities to pytest

---

qutip/steadystate.py
qutip/tests/test_steadystate.py

Update tests in `test_steadystate` to use pytest.
Improve coverage by adding tests for previously untested method and options and tests for raised errors.
It will not reach full coverage: no tests use `debug=True`, `pinv2` is deprecated on `scipy` side, some checks are redundant, etc. Some work on `steadystate.py` will be needed, but this is for another time, possibly for dev.major.
**Changelog**
Update steadystates tests to pytest for better coverage.

Update steadystates tests to pytest

---

qutip/core/data/matmul.pxd
qutip/core/data/matmul.pyx
qutip/tests/core/data/test_mathematics.py

Add `element_wise_multiply`, the equivalent to `numpy * numpy` to the dispatched function.
This function is needed to create the Bloch-Redfield tensor working in `Data` object.
The name is willingly long to discourage it's use as it is rarely a valid operation on quantum objects.

Add `element_wise_multiply`

---

qutip/core/data/dense.pxd
qutip/solver/__init__.py
qutip/solver/integrator.py
qutip/solver/ode/__init__.py
qutip/solver/ode/scipy_integrator.py
qutip/tests/solver/test_integrator.py

Introduce a common ODE integrator interface for qutip's solver.
Presently qutip's solver use `scipy.integratre.ode`'s zvode ODE solver, which support `adams` and `bdf` methods.
These are great method in most case, but not always optimal.
This PR introduce, a common interface to allow other ODE method to be used by solvers.
It also add 2 new scipy ODE solvers: `lsoda` and `dop853`.
`lsoda` detect if the system is stiff and switch between `adams` and `bdf`.
`dop853` is a 8th order Runge-Kutta method.
The `Integrator` use `Data` as state and return the state as a pair `(t, state)`.
Often solver's run only compute the expectation values, so there is no need to create a `Qobj`.
Returning the time with the state is for `mcsolve` which have the integration advancing with one internal step and …

Swappable ODE integrators.

---

qutip/tests/core/data/test_mathematics.py
qutip/tests/core/data/test_norm.py
qutip/tests/core/data/test_reshape.py

I added the option to specify `rtol` in the tests. The default value is the same as for `numpy.testing.all_close` which was being used 'silently' (tests for the exponential pretty much ignored the absolute tolerance specified by us). I also made the tests more consistent. Now the assertion for scalar outputs also use `rtol` in the same way `numpy.testing.all_close` does. 
This is useful for qutip/qutip-tensorflow#34 where I plan to add support for complex64.
**Changelog**
Aded rtol for specialisation tests.
Changed comparison of scalars to be consistent with `numpy.testing.all_close`

Rtol for tests

---

qutip/tests/test_metrics.py

Previously, all tests in `test_metrics.py` were skipped if cvxpy or cvxopt were not installed.
Addresses part 1 of https://github.com/qutip/qutip/issues/1703.
**Changelog**
Only skip the dnorm tests if cvxpy is not installed (previously all metrics tests were skipped).

Change tests/test_metrics.py so that only dnorm tests are skipped if cvxpy is not installed

---

qutip/core/metrics.py
qutip/tests/core/test_metrics.py

This PR implements and tests a new version of `process_fidelity`.
The new version follows the definition in Gilchrist et al., Physical Review A 71, 062310 (2005).
Discussion at https://github.com/qutip/qutip/issues/1703.
I previously submitted a similar PR at https://github.com/qutip/qutip/pull/1708, targeting `master`. 
This PR targets `dev.major` rather than `master` because existing functionality is changed, and contains improvements following @Ericgig 's suggestions. I have also adapted the tests to match the style of the tests in `dev.major`.
Addresses part 2 of https://github.com/qutip/qutip/issues/1703.
**Changelog**
Implement and test a new version of `process_fidelity` (https://github.com/qutip/qutip/issues/1703)

Implement and test process fidelity

---

qutip/nonmarkov/bofin_baths.py
qutip/nonmarkov/bofin_solvers.py
qutip/nonmarkov/heom.py
qutip/tests/test_bofin_baths.py
qutip/tests/test_bofin_solvers.py
qutip/tests/test_heom.py

Add Matsubara and Padé expansion Lorentzian baths for the HEOM solver.
**Todo**
* #1601
* #1724
**Changelog**
Add Matsubara and Padé expansion Lorentzian baths for the HEOM solver.

Add Matsubara and Padé expansion Lorentzian baths for the HEOM solver.

---

qutip/solver/ode/scipy_integrator.py
qutip/tests/solver/test_integrator.py

Make our integrator re-entrant. Scipy'ode is can only have one active instance active for some of the methods. This cuased no issue when the whole integration is done at once as when used in `mesolve`. But with solver as class, this mean using them will have side effect on other solver instances.  This PR make the check for concurrent integrator usage before scipy does and force a reset if needed. Switching between system will be inefficient, but will return the expected results.
In lsoda's integrator's `_backstep` we are catching a warning before acting on it, but catching the warnings still printed them at the end of tests, bloating the output. In this PR, I also do the check before scipy does so the warning is never raised.
Point raised in …

Better handling of scipy ode in integrator

---

qutip/states.py
qutip/tests/test_states.py

Raise an error instead of silently ignoring the offset when attempting to generate coherent states or density matrices with method 'operator' and non-zero offset.
* Small fix post #1469
**Changelog**
Fix silent ignoring of offset in coherent and coherent_dm when offset is non-zero. A ValueError is now raised instead.

Fix silent ignoring of offset in coherent and coherent_dm when offset is non-zero.

---

qutip/core/data/ptrace.pyx
qutip/tests/core/data/test_ptrace.py
qutip/tests/core/test_ptrace.py

**Checklist**
Added ptrace specialisation tests. While adding these tests a bug came out with `ptrace_dense` which is now fixed. The problem was it did not work for `sel=[]`, that is, no selection and hence the full trace was required. The bug comes from how `numpy` works as the output of np.prod([]) is float instead of integer. 
I wonder though what should be the behaviour for `qobj.ptrace([])`. Should it not be the same as `qobj.trace()`?  `qobj.ptrace([])` currently returns a `Qobj` of shape 1x1 whereas `qobj.trace()` returns a complex number.
**Changelog**
Fixed error with ptrace when the input and output are dense and `sel=[]`.
Added specialisations tests for ptrace.
Improved `ptrace` tests to test for edge cases (trace all and trace none).
Added a few more checks to …

Added ptrace specialisation tests and fixed a bug for ptrace_dense.

---

.github/workflows/build.yml
.github/workflows/build_documentation.yml
.github/workflows/tests.yml
doc/requirements.txt
pyproject.toml
setup.cfg

Currently QuTiP's build requirements specify `numpy>=1.16.6<1.20` but this was really a guess at the correct numpy to build with and importantly, is the wrong guess for Python 3.10 which is only supported by numpy 1.20 and later. Instead we now depend on the `oldest-supported-numpy` package, which is maintained by the numpy and SciPy folk and should always provide the correct version of numpy to build with on a given platform.
A previous version of this PR #1735 attempted to simultaneously add support for Python 3.10, but that turned out to be tricky because conda did not yet provide a pre-compiled SciPy for Python 3.10. This PR should allow QuTiP to be built locally for Python 3.10, but does not yet add official Python 3.10 builds.
* Fixes #1732 …

Build with oldest supported numpy

---

qutip/core/metrics.py
qutip/tests/core/test_metrics.py

This is a refactor of the changes from https://github.com/qutip/qutip/pull/1712. Previously, the logic which extracts the dimensions of the input and output Hilbert spaces of the involved quantum channels was spread out throughout `process_fidelity` and `_process_fidelity_to_id`. This PR collects it in a new private function `core.metrics._hilbert_space_dims`.
This will also allow reducing `average_gate_fidelity` to `process_fidelity` (in a future PR) as explained in https://qiskit.org/documentation/stubs/qiskit.quantum_info.average_gate_fidelity.html, without having to re-implement extracting the dimensions.
Part of the work on https://github.com/qutip/qutip/issues/1703.
**Changelog**
refactor process_fidelity using new function …

refactor process_fidelity using new function _hilbert_space_dims

---

qutip/utilities.py

In the recently released numpy 1.22.0 the `__config__` attribute for the
published wheels (at least on the linux platforms I'm using) have
removed the `blas_opt_info` attribute and are instead publishing
identical information in the `blas_ilp64_opt_info` attribute. Running
qutip with the latest numpy release on these platforms was causing an
attribute error when `_blas_info()` is called as
`numpy.__config__.blas_opt_info` doesn't exist in the installed numpy.
This commit fixes this by first checking if the new name exists and
using that to get the blas opt info, and then trying the name available
in previous releases. This should maintain compatibility with older
numpy releases but fix the issue when running with 1.22.0.
**Changelog**
Fix compatibility with numpy …

Handle change in configuration attributes for numpy 1.22.0

---

qutip/hardware_info.py
qutip/tests/test_hardware_info.py

Fix reading the CPU frequency on Apple M1.
Currently Mac OS does not provide the CPU frequency via sysctl (see discussion in this psutils bug -- https://github.com/giampaolo/psutil/issues/1892).
It seems that the only way to obtain the CPU frequency currently is to measure it -- see https://github.com/BitesPotatoBacks/osx-cpufreq/blob/fb82fd7afcffe9d76d98ad7af76217d7a9d34f38/M1cpufreq/M1cpufreq/main.cpp#L7-L35. I don't know what this measures exactly (e.g. is there clock scaling of some sort so that the measured CPU frequency might not be the maximum CPU frequency?) and it seems a lot of work to get a piece of information that isn't used directly by QuTiP, so I just fixed the result to 3.2 GHz for now (which according to Wikipedia is the clock speed for current M1s). …

Fix reading the CPU frequency on Apple M1.

---

qutip/visualization.py

This PR adds thresholding and phase color styles to `qutip.visualization.hinton`.
- #1595
**Changelog**
Hinton diagrams now support threshold, scaled, and phase color styles.

Add new color_style argument to hinton() (#1595).

---

qutip/mcsolve.py
qutip/mesolve.py
qutip/sesolve.py
qutip/solver.py
qutip/stochastic.py
qutip/tests/test_mcsolve.py
qutip/tests/test_mesolve.py
qutip/tests/test_sesolve.py
qutip/tests/test_stochastic_me.py
qutip/tests/test_stochastic_se.py

Dimension checks was not done for `e_ops` for most solvers, which could result in segfault, (#1776).
Add checks and tests for these checks for `sesolve`, `mesolve`, `mcsolve`, stochastic solvers. 
`brmesolve` and `floquet` are safe.
fixes #1776
**Changelog**
Add dims check for e_ops in main solvers

Add dims check for e_ops in main solvers

---

doc/guide/guide-settings.rst

**Changelog**
Fixed a typo in docs (guide-settings.rst)

Fix typo in guide-settings

---

.github/workflows/tests.yml
qutip/steadystate.py
setup.cfg

Add a numpy 1.22 and Python 3.10 build to the CI test matrix.
* If test pass consistently with numpy 1.22, we can close #1694
**Changelog**
Add a numpy 1.22 and Python 3.10 build to the CI test matrix.

Add a numpy 1.22 and Python 3.10 build to the CI test matrix.

---

qutip/tests/test_lattice.py

A change in `test_k`. In commit 7173a0d `L` was changed, but this was not reflected in `dim_H`. This commit aims to rectify that.
**Changelog**
Changed `dim_H` to include `L` in its definition in lattice tests.

Fixed dim_H in test_k

---

qutip/cy/cqobjevo.pyx
qutip/qobjevo.py
qutip/tests/test_qobjevo.py

Add check for shape at the cython level. While these checks should be done before entering cython in QobjEvo or the solvers, as seen in #1782, some bad shape can slip through. 
**Changelog**
Add check for shape in cython qobjevo.

Cy.shape.check

---

qutip/qobj.py
qutip/tests/test_bofin_solvers.py

Extra check in `Qobj` constructor to make sure that the underlying data behaves as expected.
The PR is a fix to #1782, where the `Qobj` would be constructed in a way subsequent code (i.e. `mesolve`) did not expect causing a segmentation fault.
**Changelog**
Added a check in `Qobj` constructor that the respective members of `data.shape` cannot be larger than what the corresponding `dims` could contain.

Extra check for shape in Qobj to fix #1782

---

.github/workflows/tests.yml

Since yesterday, our tests hangs for both `master` and `dev.major` and never finish. It seen only a few tests are affected.
I am adding a timeout so the tests that hangs result in a localized error.

add timeout

---

.github/workflows/tests.yml

Ignore deprecationg warnings from SciPy 1.8.0 scipy.sparse.X imports in CI tests.
- None
**Changelog**
Ignore deprecationg warnings from SciPy 1.8.0 scipy.sparse.X imports in CI tests.

Ignore deprecationg warnings from SciPy 1.8.0 scipy.sparse.X imports in CI tests.

---

qutip/core/data/csr.pyx

Fix for scipy 1.8 with dev.major:
One class is now in a private file, but still present.
**Changelog**
Fix for scipy 1.8

Fix for scipy 1.8 in dev.major

---

qutip/steadystate.py
qutip/tests/test_steadystate.py

Improve weighting in steadystate solver. Previously the default weighting did not match the documented behaviour and the sparse and dense solvers applied the weighting in different ways. Now the default matches the documentation and the sparse and dense solvers apply the weighting in the same manner.
- Supersedes #1275
- Fixes #1512
**Changelog**
Improve the weighting in steadystate solver, so that the default weight matches the documented behaviour and the dense solver applies the weights in the same manner as the sparse solver.

Improve weighting in steadystate solver.

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

Remove the wrong check on the initial state dimension. It assumes a qubit state. However, we also support multilevel systems such as qudits.
fix #1803 
**Changelog**
Remove the wrong check on the initial state dimension in QubitCircuit.

Remove the check on the initial state dimension

---

qutip/core/superoperator.py
qutip/tests/core/test_superoper.py

**Checklist**
The behaviour of the `liouvillian` seemed to be wrong. For a `TfTensor` as input it returned a `Dense` as oupu. This is mainly because the identity matrix created within the function was not a `TfTensor`. 
_Testing The tests that I included where would pass without the fix!_ 
Reproducing this behaviour within QuTiP seems to be challenging. This is because of how things are automatically converted from one data type to another. In particular, `liouvillian` worked as expected for both `Dense` and `CSR` but not for `TfTensor`. However, since `TfTensor` is not part of qutip I am not sure how to make it to reproduce this error. 
The issue seems in fact to be related to an inconsistency in how data is automatically transformed. The following code summarises the …

Linblad fix

---

qutip/fileio.py
qutip/tests/test_fileio.py

- Adds support for pathlib.Path objects in qsave/qload.
- Adds tests for those functions.
- Suffix is optional, if given it won't be appended again.
- Removes prints in qload
fix #1184
**Changelog**
`qsave` and `qload` now support `pathlib.Path` objects.

Support Pathlike objects in fileio

---

qutip/bloch.py
qutip/tests/test_bloch.py

Add do_3d_projection to Arrow3D for matplotlib 3.5 to fix the rendering of vectors on the Bloch sphere.
This PR also adds tests for rendering vectors and adds support for passing vectors as tuples.
- fix #1817
- builds on #1690
**Changelog**
Fixed rendering of vectors on the Bloch sphere when using matplotlib 3.5 and above.
Allowed vectors to be passed as tuples to Bloch.add_vectors.
Added tests for rendering vectors on the Bloch sphere.

Add do_3d_projection to Arrow3D for matplotlib 3.5

---

qutip/tests/test_superop_reps.py

Update the superop reps tests to use pytest and parameterized tests. Thank you for contributing these @MrRobot2211.
- Originally submitted as part of #1491 which also added support for rectangular superops.
**Changelog**
Update the superop reps tests to use pytest and parameterized tests. Contributed by @MrRobot2211)

Update test_superop_reps to parameterized pytest format

---

.github/workflows/tests.yml
qutip/fastsparse.py

Fix scipy.sparse deprecation warnings raised by qutip.fast_csr_matrix by:
- importing functions from the public interface where we can (i.e. from the `scipy.sparse` module)
- explicitly importing functions from the internal interface otherwise (i.e. from `_sputils`)
We already import methods from `_sparsetools` so our reliance on the internal interfaces is not a new thing.
This PR ensures we don't implicitly rely on the internal interfaces via the deprecated public interfaces.
- fixes #1823
**Changelog**
Fix scipy.sparse deprecation warnings raised by qutip.fast_csr_matrix.

Fix scipy.sparse deprecation warnings raised by qutip.fast_csr_matrix.

---

doc/biblio.rst

Documenation-Bibliography: Watrous (Theory of Quantum Information) link updated, as the old one is not working anymore.
**Changelog**
Documenation-Bibliography: Watrous link (Theory of Quantum Information) updated

Documenation-Bibliography: Watrous link updated

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

There was a bug for plotting a QC with `reversed_states = False`, that caused a problem when plotting a measurement with classical storage. This PR fixes this bug.
#1842 
**Changelog**
Fix circuit index used when plotting circuits with non-reversed states.

insert sign for plotting with non reversed states

---

doc/apidoc/classes.rst
qutip/bloch.py
qutip/bloch3d.py
qutip/tests/test_bloch.py

Adding an option to set the transparency of points and vectors on the Bloch sphere.
fix #1287 
**Changelog**
Added transparency parameter to the add_point, add_vector and add_states methods in the Bloch and Bloch3d classes.

Set point transparency on Bloch sphere

---

.github/workflows/tests.yml

Disable mcsolve tests on windows.
- See #1202
**Changelog**
Disable mcsolve tests on windows. The mcsolve solver uses multprocessing under the hood to simulate many trajectories at once and this can deadlock on Windows.

Disable mcsolve tests on windows.

---

qutip/tests/solve/test_krylovsolve.py

Tests related to krylovsolve take a lot of time, close to 1/3 of the whole test suite.
I kept all the tests, but reduced the size of the systems used.

Shorter krylov tests

---

qutip/core/data/properties.pyx
qutip/tests/core/data/test_properties.py

`isherm_csr` did not fully tested the structure, it only checked that each line had as many elements in it than the corresponding column. So 
```
[[1, 1, 0],
[0, 1, 1],
[1, 0, 1]]
```
was seen as hermician.
This added a second layer of structure check for such cases and a test that would previously fail.
Fixes #1865

Fix `isherm_csr` wrongly detecting structure

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

The `add_circuit` function in `QuantumCircuit` class used to copy the names of all gates without add the definition of user gates to the target circuit. Hence the user gates cannot be recognized by the new circuit. I made the copy of the definition automatic.

quantum circuits inherit user gates from `add_circuit`

---

qutip/nonmarkov/transfertensor.py
qutip/tests/test_transfertensor.py

The nonmarkov transfer tensor method (TTM) fails in an example notebook (see below). I tracked down the error to the *ttmsolve* method, where None is used to fill an array. I replaced None with an empty Qobj to fix the bug occuring from adding a Qobj and None.
The related issue is in the qutip-notebooks repo: https://github.com/qutip/qutip-notebooks/issues/122
**Changelog**
Replace placeholder in ttmsolve with empty Qobj

Fix ttmsolve bug with addition of Qobj and None

---

qutip/solver/ode/scipy_integrator.py
qutip/tests/solver/test_integrator.py

`IntergratorScipylsoda.mcstep` read the integration range from the scipy solver's `rwork`. However `rwork` is initialized to 0 when initializing the state and only take the expected value when the first step in done. Therefore it would fail when starting from time other than `0`. `IntergratorScipyZvode` also used `rwork` in an unsafe way.
Fix that and add a test. 
Similar improvement where first made in https://github.com/qutip/qutip/pull/1710, splitting it to made that PR simpler.
**Changelog**
`IntergratorScipylsoda` safe for starting at any time.

Fix bug in `IntergratorScipyZvode` when starting integration at time other than `0`

---

qutip/solver/solver_base.py
qutip/tests/solver/test_sesolve.py

`Solver` create the integrator at `__init__` instead of in `run` and `start`.
`step` and `run` no longer take an `options` parameter.  `solver.options = new_options` will now reset the integrator to use the new options. However changing options will always reset the integrator.
Similar improvement where first made in #1710, splitting it to made that PR simpler.
**Changelog**
Sovlers manage options as a property instead of method's parameter.

Solver contain unique integrator 

---

README.md
qutip/about.py

Added Asier Galicia to the QuTiP adim team list.
**Changelog**
Added Asier Galicia to the QuTiP adim team list.

Added Asier Galicia to the qutip admin team list.

---

qutip/tests/solve/test_correlation.py

Lower the dims and length of the `tlist` used by `test_correlation_solver_equivalence[mc]`. Since we added a maximum time for the tests, this one test would fail from time to time. This make the test about 20% faster, which hopefully should be enough to have tests consistently passing.
**Changelog**
Faster `test_correlation_solver_equivalence` test.

Faster correlation test

---

qutip/solver/options.py
qutip/solver/parallel.py

Parallel map options' defaults are set in both options.py and parallel.py. As remarked by Asier in #1710, they should be defined in only one place.
The default are now set in parallel.py. Everywhere else can set the value to `None` or not set the key to use the default.
Also the default number of cpus is obtain with `utilities.available_cpu_count` instead of `multiprocessing.cpu_count`.
Originally in #1710
**Changelog**
Single definition for map_kw defaults.

Single definition for map_kw default

---

qutip/core/data/src/intdtype.h
qutip/core/states.py
qutip/random_objects.py
qutip/tests/core/test_coefficient.py
qutip/tests/core/test_states.py
qutip/tests/solve/test_mcsolve.py
qutip/tests/solve/test_qubit_evolution.py
qutip/tests/test_entropy.py

Fix some of the warnings in the tests in order to restore the `-Werror` flag later.
- Remove test for `state_number_qobj`: (function replaced by `basis`.)
- scipy.sparse matrix operation replaced by `data.CSR` operation.
- Fix passing generator to `hstack`.
- Add some `filterwarnings` for `mcsolve` fallback to `sesolve` and coefficient parsing warning.
TODO in #1850
**Changelog**
Fix some warnings in tests.

Fix some warnings in tests

---

qutip/core/cy/qobjevo.pyx
qutip/core/data/src/intdtype.h
qutip/tests/core/test_qobjevo.py

We updated the signature for arguments in coefficient from dict to keyword format, changing call from `coeff(t, args)` to `coeff(t, **args)`. However `QobjEvo`, which have a similar call taking time and argument still took the new args as dictionary instead of keyword. Added keywork support for `QobjEvo.__call__` and `QobjEvo.arguments` . The `__init__` still take argument as a dict since it already takes a lot of parameters.
Follow up to #1633 
**Changelog**
QobjEvo call accept keywords for new args.

QobjEvo's call take kwargs

---

qutip/qip/circuit.py
qutip/tests/test_qubitcircuit.py

The fix pertains to `add_gate` behaviour when multiple insertion indices are supplied. Prior to the proposed fix, the insertion loop doesn't take into account the fact that inserting an element in the gates list, modifies the indices in the original list, whereas the caller of `add_gate` supplies a list of indices, with positions with respect to the indices in the original list.
Additionally, the PR removes unused variables and unused function (that has also not been imported).
Fixes #1497.
**Changelog**
Fixed add_gate behavior when inserting a gate at multiple indices.

Fix add_gate behavior when inserting a gate at multiple indices

---

qutip/core/data/eigen.py
qutip/tests/core/test_eigen.py
qutip/tests/core/test_eigenstates.py

There are some edge cases with the eigen solver that are bugged in `dev.major` that tests missed:
- `_eigs_dense` : It would not compute the proper eigen states when not all eigen states are required and the matrix is non-Hermitian.
- `_eigs_csr` : When all but one eigen values / vectors are needed: the smallest eigen values would always be removed, even when `sort='high'`. Also one element of the eigen vector matrix was removed, not one column.
I rewrote the tests with pytest to catch more cases.
**Changelog**
Fix some edges cases in `eigs`.

Fix bug in eigen solver

---

.github/workflows/build_documentation.yml
.github/workflows/tests.yml

pip 22.1 broke support for `oldest-supported-numpy` when using `--no-build-isolation` by complaining that oldest-supported-numpy was not installed. Later versions of pip fixed this check.
- #1897 was the equivalent PR for dev.major
**Changelog**
Build documentation with latest pip version.

Build documentation with latest pip

---

qutip/nonmarkov/bofin_solvers.py
qutip/tests/test_bofin_solvers.py

While working on the [heom-tls notebook] I discovered two wrong behaviors of the `HEOMSolver`. 
1. Running `hsolver.run()` does not return the states if `e_ops=None`, but the documentation says that it should do so. I added the missing if condition to `HEOMSolver`. 
2. If passing a progress bar like `qutip.ui.progressbar.TextProgressBar()` to `HEOMSolver` it results in an error, because internally it only checks for `None` or `True`. The documentation says it should also work if I pass an instance of `BaseProgressBar` (or a subclass). I added the checks and a test in the testfile for this.
None
**Changelog**
Fix HEOMSolver state return and progress bar

HEOMSolver return states and progress bar

---

qutip/bloch.py

I removed some of the imports from numpy. I favored the writing style of `np.linspace` vs `linspace` in most cases except for `outer`, `ones`, `cos` and `sin`. I kept these for readability in lines 706-708 but could be changed to `np.outer` and so on.
**Changelog**
Clean-up imports Bloch.

Removed unused imports.

---

doc/guide/dynamics/dynamics-master.rst

I found the description for unitary, non-dissipative time evolution a bit confusing as the text always referred to `mesolve` while the examples used `sesolve`. I adapted the text to `sesolve` for that section and introduced `mesolve` only in the next section.
understanding the docs
**Changelog**
Improve documentation on solving for unitary dynamics by making the use of sesolve and mesolve in the code examples more consistent with the text, and by making the text clearer.

clarify docs of sesolve and mesolve

---

qutip/qip.py
qutip/tests/test_qip.py

- Allow imports of `qutip.qip` seamlessly as imports of `qutip_qip`
- Test the import behaviour when `qutip_qip` is installed and when not.
Incorporates the ideas in the discussion of #1500.
Fixes #1893.
**Todos and questions**
I have a draft of these changes locally, but they fail due to a dependency conflict: `qutip_qip` currently requires `qutip<5 and >=4.6 ` while these changes are being implemented in `v5.0.0.dev`, ie `>5`. This will cause the unit test where `qutip_qip` is installed to be skipped. Any ideas on how to get around this?
**Edit**: Uses a stub for the `qutip_qip` package in the units tests instead, which removes the need of having `qutip-qip` installed.
**Changelog**
Allow imports of `qutip.qip` seamlessly as imports of …

Setting qutip-qip as an optional plugin for qutip-5 [unitaryhack]

---

MANIFEST.in

Installing `dev.major` is raising warnings because of errors in MANIFEST.in:
```
...
reading manifest file 'qutip.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'qutip.bib'   <=====
warning: no files found matching '*.qasm' under directory 'qutip/tests/qasm_files'   <=====
adding license file 'LICENSE.txt'
writing manifest file 'qutip.egg-info/SOURCES.txt'
running build_ext
...
```
qutip.bib was renamed to CITATION.bib in #1662 
qasm files were removed in #1890 and are now only included with qutip-qip
**Changelog**
Update MANIFEST.in to reflect changes in #1662 and #1890

Fix warning at installation from broken link in manifest.in

---

qutip/bloch.py
qutip/tests/test_bloch.py

Clean-up of the methods `add_vectors` and `plot_vectors`.
- raise ValueError when wrong values on inputs for vectors and colors.
- fixes issue #1916 
- colors argument was bugged as it was not being taken into account when plotting. I kept the colors argument behaving as it was first intended, although we may want to change it later to match the behavior of points.
- Added tests for new ValueErrors and for the colors argument.
#1913.
**Changelog**
Clean-up of the methods `add_vectors` and `plot_vectors`.
Now add_vectors raises ValueErrors for wrong vectors and colors argument
Fix issue #1916 
Fix colors argument
Improve test coverage

Bloch vector methods

---

qutip/bloch.py

Remove unused feature in `Bloch.plot_vectors`. This feature was bugged and undocumented
#1916
**Changelog**
Remove unused feature in `Bloch.plot_vectors`.

Removed unused feature in Bloch.plot_vectors

---

doc/guide/dynamics/dynamics-time.rst

The guide for time-dependent dynamic includes plots fro the guide before (stochastic dynamics) because it fails to reset its context and properly close figures. This PR fixes that.
The same goes for many other uses of `.. plot::` in the guides and other documentation, but I will leave fix those for when someone has time to go through them more carefully.
See https://qutip.org/docs/latest/guide/dynamics/dynamics-time.html for the issue.
None
**Changelog**
Fix spurious plots that appear after many code blocks in the dynamics-time guide.

Reset and clear up figures more correctly in dynamics-time guide.

---

qutip/core/qobj.py
qutip/tests/core/test_qobj.py

Allow `qobj +/- 0` for `Qobj` of any shape and type to allow the use of `sum(kets)` as discussed in #1841.
Addition and subtraction of any other number will still raise an error if the object is not square as before.
Issue raised in #1841
**Changelog**
Allow `ket + 0`.

Allow `sum(kets)`

---

doc/guide/dynamics/dynamics-time.rst

This fixes typos I was able to find in the documentation for "Solving Problems with Time-dependent Hamiltonians"
None
**Changelog**
Some typos in the documentation for solving problems with time-dependent Hamiltonians have been corrected

Fix typos in docs for time-dependent Hamiltonians

---

.github/workflows/tests.yml
qutip/solve/mcsolve.py
qutip/solver/parallel.py
qutip/tests/solver/test_parallel.py

Activate the mcsolve tests in QuTiP 5.
Changes:
- Continues work from #1853 and #1854 in v4
- #1202 (maybe already resolved in QuTiP 5)
- #1190 (hopefully already resolved in QuTiP 5)

Activate mcsolve tests on Windows in QuTiP 5

---

doc/changes/1951.feature
qutip/core/blochredfield.py
qutip/tests/core/test_brtools.py

The function `bloch_redfield_tensor` required the spectra given in `a_ops` to be `qutip.Coefficient`. For compatability with `brmesolve` I added support for strings and callables in `bloch_redfield_tensor`.

`bloch_redfield_tensor` support different spectra types

---

doc/changes/1952.bugfix
qutip/solve/floquet.py
qutip/tests/solve/test_floquet.py

I have added a missing transformation call in the Floquet-Markov Master Equation Solver. The function returned the results in the wrong basis and calculated expectation values in the wrong basis. With the transformation the correct basis should be chosen.

Add missing transform to Floquet-Markov Solver in v5

---

doc/changes/1950.doc
doc/guide/dynamics/dynamics-bloch-redfield.rst

.**Description**
Some changes to the Bloch-Redfield Solver documentation. 
It was not clear from the documentation that `bloch_redfield_tensor` returns the eigenstates of the Hamiltonian ( and not the eigenstates of the tensor itself). And some minor equation mistake was fixed.

Docs brmesolve

---

doc/changes/1964.bugfix
qutip/metrics.py

The previous code converted both states to density matrices, which is both inefficient and numerically inaccurate. We propose to use the reduced fidelity formula for pure states, given by the modulus of their inner product.
Related to #361 and #925.
Reusing @lucainnocenti example (https://github.com/qutip/qutip/issues/925#issuecomment-542318121):
```python
import numpy as np
A = qt.Qobj(np.array([
0.867314655330313 - 0.4576338188944636j,
0.17267952805615244 - 0.09111291375544905j,
0.013020232894921149 -0.006875138252288391j
]))
B = qt.Qobj(np.array([
0.9806443568092577, 0.19524328915024022, 0.014720852555238875
]))
fid1 = np.abs(np.vdot(A.full(), B.full()))
fid2 = np.abs((A.dag() * B)[0, 0])
fid3 = np.abs(A.overlap(B))
fid_qt = …
```

Fix fidelity for pure states

---

doc/changes/1962.feature
qutip/solve/floquet.py
qutip/tests/solve/test_floquet.py

Introducing support for multiple coupling operators in `fmmesolve`. Additionally, I fixed the bug with the rate integration as described in #1961. 
#1961

`fmmesolve` multiple c_ops and rate integration fix

---

doc/changes/1965.bugfix
qutip/bloch_redfield.py
qutip/tests/test_brmesolve.py

For constant systems, when the ODE solver is not successful, `brmesolve` returned an incomplete result without telling the user something failed.
With this PR. an exception is raised in these situations.
#1965

`Brmesolve` properly raise error when ode fails.

---

qutip/core/coefficient.py
qutip/solver/parallel.py
qutip/tests/core/test_coefficient.py
setup.cfg

Add a lock for creating string coefficient. This allow to use the coefficient inside a parallel loop without issues.
The lock use `filelock` which works across processes, so it's safe to use with parallel coming from outside python.
The lock is per file, so different coefficient can compile in parallel. If there is a conflict, the first process will create and compile the coefficient and the other will use it (raising a hash collision error if not actually the same string.)
`filelock` is a new requirement for runtime compilation.
#1963

Protect compilation of coefficient using filelock

---

qutip/core/coefficient.py

A change in setuptools (pypa/setuptools#3521) raise a warning when compiling coefficient using absolute path, which breaks our tests for `dev.major`:
```
DeprecationWarning: Absolute path '/home/runner/.qutip/qutip_coeffs_1.1/qtcoeff_8208be2129365a87dda9c12028c457' is being replaced with a relative path 'home/runner/.qutip/qutip_coeffs_1.1/qtcoeff_8208be2129365a87dda9c12028c457' for outputs. This behavior is deprecated. If this behavior is desired, please comment in pypa/distutils#169.
```
This changes the path to be relative.
I change the path before creating the lock files, which otherwise were polluting the active directory.

Have coefficient compilation use relative path

---

.github/workflows/tests.yml
setup.py

- Ignore DeprecationWarnings raised by pyximport on Python 3.10.
- Explain (after much digging) how to pass `--with-openmp` to `python -m build`.
- https://github.com/cython/cython/issues/4985
- https://github.com/pypa/distutils/issues/169

Ignore DeprecationWarnings raised by pyximport on Python 3.10.

---

.github/workflows/tests.yml
doc/changes/1970.bugfix
qutip/bloch.py
qutip/tests/test_bloch.py
setup.cfg

Backport the fix for #1912 to master.
The issue was that previously the print_figure function returned byte code, but since https://github.com/ipython/ipython/pull/5452 (in 2014) it returns a Unicode string.
- #1912 (original issue)
- #1918 (fix for dev.major)
- #1943 (previous attempt at a fix for 4.7.X)

Backport fix for IPython helper _repr_svg_ from dev.major.

---

doc/changes/1979.bugfix
qutip/correlation.py
qutip/tests/test_correlation.py

Fix the bug in correlation where it would not properly detect that the system were time-dependent when only the c_ops were.
fix #1808
replace #1929

Correlation support time dependent c_ops

---

doc/changes/1981.feature
qutip/control/dump.py
qutip/control/grape.py
qutip/control/optimconfig.py
qutip/core/semidefinite.py
qutip/solve/steadystate.py

This PR reduced the qutip import time by setting the logger names explicitly. 
See #1980 for more details.

Draft: Reduce qutip import time by setting logger names

---

qutip/solver/parallel.py
qutip/tests/solver/test_parallel.py

`parallel_map` did not propagate error of sub-procceses:
```
def f(i):
raise Exception
return i
out = qutip.solver.parallel.parallel_map(f, range(5))
```
would print: 
```
ERROR:concurrent.futures:exception calling callback for <Future at 0x7fcdfb9b8e50 state=finished raised Exception>
concurrent.futures.process._RemoteTraceback: 
...
raise Exception
```
but it would return normally with `out = [None, None, None, None, None]`.
This mean we can't use a `try` block to catch error coming from sub-process and only when the output is used, an error is risen.
This change `parallel_map` so it raise the first error it encounter.

parallel map raise subprocess error.

---

qutip/solver/mcsolve.py
qutip/solver/multitraj.py
qutip/solver/parallel.py
qutip/solver/result.py
qutip/tests/solver/test_mcsolve.py
qutip/tests/solver/test_results.py

Rewrite `mcsolve` as a class for dev.major.
Main addition:
- `MultitrajSolver` class as a base class for solver computing trajectory from a seed: it uses custom 
- It uses custom integrator using a generator which `MultitrajSolver` provide. 
- Stepping run one trajectory at a time.
- Use numpy.random new interface with `SeedSequence` and `Generator`.
- `run` can end on number of trajectories reached, timeout reached, or error bars on expectation values under a certain tolerance.
- `McSolver` class for mcsolve class interface.
- Support closed and open system. For open systems. `H` must be a Liouvillian. The `c_ops` are computed stochasticly and are used for collapse. Dissipation terms to be used in a deterministic way can be added as Lindblad dissipators to the …

McSolver class for dev.major

---

doc/changes/1991.feature
qutip/core/dimensions.py
qutip/core/tensor.py
qutip/entropy.py
qutip/tests/core/test_tensor.py

Swap `dims` and `targets`. The new parameters (oper, dims, targets) better match with the ones in v4 (oper, N, targets, dims=None), which makes it easier to add deprecation warnings.
Remove `__all__ = ['expand_operator']` from `dimensions.py` which was probably a mistake from a previous PR.

Swap the parameters `dims` and `targets` for expand_operator

---

qutip/core/qobj.py
qutip/tests/core/test_qobj.py

Similar to what happened with expect (#1636), we can not ensure that everything returned by the data dispatcher has a real attribute.
qutip/qutip-tensorflow#37
#1636

Ensure that tr can return objects that do not have the real attribute.

---

qutip/core/qobj.py
qutip/tests/core/test_qobj.py

Fix issue part of the issue with qutip/qutip-tensorflow#37.
We rely on `__mul__` to decide what to do with other instead of making it complex in `__truediv__`.
This fix was already discussed in #1620.

Added division by scalar to be more flexible.

---

qutip/core/data/linalg.py
qutip/core/data/reshape.pyx

Fix some mistakes in dispatch signatures:
- Typo in `inv`.
- `inv` dispatch on output.
- Wrong `rehape` name

Fix dispatch signatures errors

---

qutip/core/cy/qobjevo.pyx
qutip/tests/core/test_qobjevo.py

In solvers, we often wrap `Qobj` into `QobjEvo` to remove code duplication while allowing support for time-dependant operators even when constant case are the norm (`e_ops`). Doing so we lose the `isherm` flag, which can sometime be nice to have. 
This PR allow the flag to be kept when calling the `QobjEvo` in such case:
```
>>> QobjEvo(qeye(N))(0)._isherm
True
```
This will be useful for the `diag` integration method which need compute the eigenstates of a constant `QobjEvo`.

Keep isherm flag in constant QobjEvo

---

doc/changes/2011.bugfix
qutip/visualization.py

Fix the hinton visualization method to plot the matrix instead of its transpose.
Fix #2009.

Fix hinton plot displaying rho.T instead of rho

---

doc/changes/2012.bugfix
qutip/visualization.py

Fix the hinton visualization method to take into account all the matrix coefficients to set the squares scale, instead of only the diagonal coefficients.
Fix issu #2010. Cascading PR #2011.

Fix hinton plot scaling

---

.github/workflows/tests.yml
qutip/core/coefficient.py
qutip/core/cy/coefficient.pyx
qutip/core/cy/qobjevo.pxd
qutip/core/cy/qobjevo.pyx
qutip/tests/core/test_coefficient.py
qutip/tests/core/test_qobjevo.py

With the update of correlation to v5 in #1997, the need for  `shift` in `QobjEvo` and `Coefficient` disappeared.
`ShiftCoefficient`, `QobjEvo._insert_time_shift` and related tests are removed.
I also restored the correlation tests on windows hoping they are now fast enough to not timeout.
#1997

Remove shift in coefficient and qobjevo after 

---

.github/workflows/build.yml
.github/workflows/build_documentation.yml
.github/workflows/tests.yml
qutip/solve/steadystate.py

Mac tests have been failing for a while because of MKL. 
Set the mac test to run with openblas, skipping failing tests.
Added `rcond=None` to `linalg.lstsq` to remove a warning.
I also updated versions of github action as some where raising warnings.

Run mac tests without mkl

---

.github/workflows/build.yml
.github/workflows/build_documentation.yml
.github/workflows/tests.yml
qutip/steadystate.py

Run mac test with openblas instead of MKL to skip the tests failing with pardiso.
Update github action version since they are raising deprecation warning.
#2019

Run mac test without MKL

---

qutip/solver/correlation.py

Fix an error in 1 time correlations function's equations.
Make clearer that 2 times correlation functions always return 2D array even when `tlist` is `None`.
Add the `:class:` descriptor to `Qobj`,  `QobjEvo` in docstrings.
Remove `HEOMSolver` from the list of supported input of `correlation_3op`.
Fix #2018

Correlation documentation

---

.github/workflows/tests.yml

Explicitly define matplotlib backend for Windows tests.
- #2013 (equivalent change for master)
- Cherry pick of 123163f4

Explicitly define matplotlib backend for Windows tests (v5).

---

doc/guide/guide-settings.rst
qutip/core/options.py

Update the guide for setting to list options still available in v5 and add an example with the using newly added context.
Removed the `auto_herm` options which was removed with `Qobj.isherm` being a property.
`auto_tidyup_dims` is not used anywhere but I left if since it could be useful with the dimensions class.

Update `guide-settings` with v5's options

---

doc/guide/guide-basics.rst
doc/guide/guide-random.rst

Update the documentation of guide-random to fit the next interface with `seed`, `dtype`, `distribution` etc.
Remove some method no longer existing for `Qobj` listed in guide-random.

Update guide-random/basic for v5

---

qutip/qobj.py

Changes the string generated by `_repr_latex()` in `qobj.py` so that it plays nicely with VSCode jupyter notebooks. 
Specifically, changes the output to be encased in `$...$`, and changes from `\begin{equation} \begin{array}...` to `\begin{matrix} ...`
This lets matrices be output nicely in VSCode.
fixes #1887

edits for working latex renders in vscode

---

qutip/core/data/__init__.py
qutip/core/data/eigen.py
qutip/core/data/solve.py
qutip/tests/core/data/test_linalg.py

Add data layer functions needed to update `steadystate` to use qutip's data layer.
Most of `steadystate`'s methods solve the system `L(rho_ss) = 0` using different solver from numpy, scipy, mkl.
This add the `solve` dispatched function to wraps this operation at the data layer level.
For the `CSR` version, it gives access to all methods available in `scipy.sparse.linalg` and our mkl version.
For the `Dense` version, `solve` and `lstsq` from `numpy.linalg` are made available.
Options supported by numpy / scipy for each function are pass through:
`qutip.data.solve(A, B, method, options)` call `scipy.sparse.linalg.method(A, B, **options)`.
Other methods of `steadystate` decompose the Liouvillian with either `eigen` or `svd`.
`svd` was added as a dispatched function, but only …

Add `solve` and `svn` to dispatched function

---

qutip/core/data/constant.py
qutip/core/data/dispatch.pyx
qutip/core/data/inner.pyx
qutip/core/data/matmul.pyx
qutip/core/data/permute.pyx
qutip/core/data/pow.pyx
qutip/core/data/project.pyx
qutip/core/data/properties.pyx
qutip/core/data/ptrace.pyx
qutip/core/data/reshape.pyx
qutip/core/data/tidyup.pyx
qutip/tests/core/data/test_mathematics.py
qutip/tests/core/data/test_properties.py
qutip/tests/core/test_qobj.py

`Dense` was missing some dispatch specialisations:
`isherm`, `isdiag`, `inner`, `inner_op`, `pow`, `indices` and `dimensions`.
Some of them are quite commonly used:
- `isherm` is called in a few method of `Qobj` like `eigenstates`.
- `inner` is used in `Qobj.__matmul__` between `bra` and `ket`.
Tests for new functions are added.
For `isherm`, it was already tested for Dense, but relied on the automatic conversion of the dispatcher.
Also fix some docstings which used `Arguments` instead of `Parameters`.

Add missing Dense specialisations

---

doc/guide/dynamics/dynamics-data.rst
doc/guide/dynamics/dynamics-options.rst
doc/guide/dynamics/dynamics-time.rst
qutip/solver/result.py

Update the guides for solver options, results and time-dependent system.
In `dynamics-data`, I added example of the `e_data` property and explained the difference between results for one and multiple trajectories.
`dynamics-time` as been mostly rewritten to explain how to use `QobjEvo`. It explain most features needed to use them in solvers, but it's quite dry.

Update dynamic documentation for dev.major

---

doc/changes/2032.bugfix
qutip/core/operators.py
qutip/tests/core/test_operators.py

The momentum and position did not have the _isherm attribute set to True. Setting it by default to True means hamiltonians created with those operators only will also have the attribute set to True and, for example, eigenvalues computed will, by default, return a real value (and I think be computed faster but I am not completely sure if we take this into account in our algorithms).

Momentum and position default isherm values.

---

qutip/solver/brmesolve.py
qutip/solver/heom/bofin_solvers.py
qutip/solver/propagator.py
qutip/solver/solver_base.py
qutip/tests/solver/heom/test_bofin_solvers.py
qutip/tests/solver/test_propagator.py

Allow `Propagator` to take a `Solver` instead of an Hamiltonian, this allow to make propagator work with brmesolve or HEOM.
To help with that, I made the system's solver dimensions accessible through `sys_dims` and whether they represent super dims in `evolve_dm`.

Allow propagator to accept Solver input

---

.github/workflows/tests.yml
doc/changes/2037.bugfix
setup.py

Fix parsing of package versions in packaging 22.
- #2036
- https://github.com/pypa/packaging/issues/631

Fix parsing of package versions in packaging 22.

---

doc/changes/2040.bugfix
qutip/qip/device/processor.py
qutip/tests/test_device.py
qutip/tests/test_processor.py

**Checklist**
Add a default max_step to processors using the smallest gate time.
fix #2003

Add a default max_step to processors using the smallest gate time

---

doc/changes/2043.misc
setup.py

Calling Version directly has given the strict parsing we require since the Version class was created and the class predates the parse(...) function itself. This simpler code should give the correct behaviour on all versions of packaging since 2014.
- See #2037
- See #2036

Simplify version parsing.

---

doc/apidoc/classes.rst
doc/apidoc/functions.rst
doc/guide/dynamics/dynamics-master.rst
doc/guide/dynamics/dynamics-monte.rst
doc/guide/dynamics/dynamics-options.rst
qutip/solver/correlation.py
qutip/solver/mcsolve.py
qutip/solver/mesolve.py
qutip/solver/propagator.py
qutip/solver/result.py
qutip/solver/sesolve.py
qutip/tests/solver/test_correlation.py
qutip/tests/solver/test_integrator.py
qutip/tests/solver/test_mcsolve.py
qutip/tests/solver/test_mesolve.py
qutip/tests/solver/test_options.py
qutip/tests/solver/test_propagator.py
qutip/tests/solver/test_sesolve.py

- In `SeSolver`,   `MeSolver`,   `McSolver`, only capitalized 2 letters while `BRSolver` and `HEOMSolver` capitalized all abbreviated terms. Changed it use the same capitalization everywhere: `SESolver`,   `MESolver`,   `MCSolver`.
- Update dynamics-master for v5. Only changing a few links is needed. No reference to the class interface is added since it comes before the explanation to time dependent system.
- Updated dynamics-monte: Add description for new results, with photocurrent, average and runs version of expect and state. The class interface was quickly introduced in the `Reusing Hamiltonian Data` section.

Documentation for v5 mcsolve

---

doc/QuTiP_tree_plot/qutip-structure.py
doc/apidoc/functions.rst
doc/guide/guide-parfor.rst
qutip/ipynbtools.py
qutip/solve/parallel.py

We officially removed `parfor` in v5. This remove it's mentions in the using qutip in parallel documentation page.
Also removed it the the namespace of `ipynbtools.py` and `solve.parallel.py` (the later only exist until the stochastics solver are migrated to the class interface).

Remove example using parfor in the documentation.

---

qutip/solver/brmesolve.py
qutip/solver/floquet.py
qutip/solver/mcsolve.py
qutip/solver/multitraj.py
qutip/solver/solver_base.py

Options in solver are usually set in `Solver.__init__`, but solver that needed options at the building of the rhs needed to initiate them themselves and it was more complex than needed.
Allow to use `self.options = options` at anytime without having to set `_options` and filter `None` first.

Simplify initiating options in solver

---

.github/workflows/build.yml

- Added a job that update to testpypi when the "test" is entered as the branch name.
- Removed the check that stopped release with `dev` in the version number.
- Added a token for testpypi.
While it's a draft PR, the action will only print, not run the upload command.

Update the release action to push to testpypi and allow dev release.

---

doc/changes/2082.bugfix
qutip/cy/spmath.pyx
qutip/tests/test_spmath.py

This was solved in dev.major #1865.  Thanks Eric for pointing out the solution :).
fix #1998

Fixed issue #1998.

---

.github/workflows/tests.yml

- Remove disabling of cvxpy warnings. These were fixed in cvxpy 1.3.
- Remove disabling of pyximport absolute path warnings (QuTiP 5 no longer uses pyximport).
- None

Re-enable all cvxpy and pyximport warnings on Python 3.10 and 3.11 tests.

---

qutip/tests/core/data/test_linalg.py

`svd`'s states are defined up to a sign.
We used both numpy and scipy for the tests and that difference in sign could make the tests fail randomly.
This makes the tests independent of the signs.

Test for `svd` more robust

---

doc/changelog.rst

Fix formatting of quotes around qutip-jax in changelog for 5.0.0a1
- None

Fix formatting of quotes around qutip-jax in changelog for 5.0.0a1

---

qutip/tests/test_bloch.py
setup.cfg

Test for the bloch sphere require matplotlib and ipython to pass, but these were not installed with `qutip[tests]`.
These tests are now skipped when these packages are missing instead of failing.
Also add `loky` and `tqdm` to extra require as they can now be used in solvers.

Fix test requirement

---

doc/changes/2112.misc
qutip/ipynbtools.py
qutip/ui/progressbar.py

**Checklist**
Moved HTMLProgressBar from `qutip/ipynbtools.py` to `qutip/ui/progressbar.py`
Fix #2108

Move html progressbar

---

qutip/core/data/csr.pyx
qutip/core/data/dense.pyx
qutip/core/data/matmul.pyx
qutip/tests/core/data/test_dense.py

`OrderEfficiencyWarning` was not properly imported in matmul.pyx since `dense` was cimported.
Removed unused import in csr.pyx and dense.pyx that were causing circular import when importing from dense.py at the top of the file.

Enable warning in matmul_csr_dense

---

qutip/core/data/mul.pyx

Update `imul_csr` and `imul_dense` to use blas instead of a loop.
blas is faster and it makes a visible difference when timing the stochastic integration.

`imul` using blas

---

doc/changes/2128.feature
qutip/core/data/csr.pxd
qutip/core/data/csr.pyx
qutip/solver/heom/bofin_solvers.py
qutip/tests/core/data/test_csr.py

Adds a `_from_csr_blocks` constructor to speed up the construction of the HEOM RHS by a factor of ~4x.
What allows `from_csr_blocks` to be fast is that we can order the blocks in a way that makes it possible to write the rows of the output one after the other without a lot of work, and we never have to add a new non-zero element into a row or make a copy of the big output matrix.
The implementation in Python was slow just because there is a lot of Python looping and arithmetic when the number of operators being combined becomes large.
`_from_csr_blocks` is a private constructor for now. If use cases emerge we can consider making something similar part of the public interface later.
- None

Speed up the HEOM RHS construct

---

setup.py

Add options to annotate the cython files at installation.
I used it when updating the stochastic solvers, but do not what to include it in that PR.

Add annotate cython files options when installing the module

---

qutip/core/data/matmul.pyx

We use `imatmul_data_dense`  for cython only, in-place `matmul` operation since the dispatcher can't handle in-place operation but they can't have nice impact on performance.
`imatmul_data_dense` had a bug that when data is not `Dense` or `CSR` it would use a wrong specialization of `matmul` and raise an error. 
It work fine with all data layer in qutip/qutip so we can test it here, but some tests fails in qutip-jax (qutip/qutip-jax#14) because of it.
Blocking qutip/qutip-jax#14

Fix dtype in `imatmul`

---

doc/changes/2138.misc
qutip/core/metrics.py
qutip/core/operators.py
qutip/core/semidefinite.py
qutip/tests/core/test_operators.py

Did some cleaning in `semidefinite.py`:
- Renamed functions that should be private: `kron` -> `_kron`, `conj` -> `_conj`, etc.
- Removed `dag`, and `bmat`: never used.
- Moved `qudit_swap` as `swap` in operator.py and added tests.
- Use `functools.lru_cache` instead of re implementing a memoize decorator. This used to be done in `dnorm`, comments were still present, removed.
- Merged `herm` `pos_noherm`, `pos` and `dens` into `_make_constraints`.
- Removed the logger call. 
- black the file.
@hodgestar Now only qutip-ctrl use the logger, can we move logging_utils.py there?

Clean semidefinite.py

---

qutip/tests/core/test_superop_reps.py

The test `test_random_iscptp` would sometime randomly fail.
This increase the tolerance of the test, lowering the fail rate from 0.35% to less than 1 in 10000 tries.

Increase `iscptp` tolerance

---

qutip/core/data/solve.py
qutip/solver/countstat.py
qutip/tests/core/data/test_linalg.py

In #2120, `countstat` was updated to use `data.solve`.
`countstat` would sometime try to solve a system with singular matrix and has a fallback for it using `try: ... except:`
However, while numpy raises an error when the matrix is singular, `scipy.sparse` raises a warnings, thus the tests only pass because we use the warnings as error flags... Without it, the singular matrix would not be caught and the solution from `countstat` would contain a `NaN` and the tests would fail...
- Redirect the warning from scipy sparse and numpy's `LinAlgError` to a `ValueError`to allow easy catching of these case.
- Add the small `1e-15` in `countstat` with `auto_tidyup` turned off.
- Add support for the method `lstsq` and `solve` for `data.solve_csr`. These methods are supported by numpy, …

Make `data.solve` more robust to singular matrices for `countstat`

---

doc/changes/2135.misc
qutip/core/data/add.pyx
qutip/core/data/adjoint.pyx
qutip/core/data/dispatch.pyx
qutip/core/data/eigen.py
qutip/core/data/expect.pyx
qutip/core/data/expm.py
qutip/core/data/inner.pyx
qutip/core/data/kron.pyx
qutip/core/data/linalg.py
qutip/core/data/matmul.pyx
qutip/core/data/mul.pyx
qutip/core/data/norm.pyx
qutip/core/data/permute.pyx
qutip/core/data/pow.pyx
qutip/core/data/project.pyx
qutip/core/data/properties.pyx
qutip/core/data/ptrace.pyx
qutip/core/data/reshape.pyx
qutip/core/data/solve.py
qutip/core/data/tidyup.pyx
qutip/core/data/trace.pyx

I optimized the dispatched by only supporting positional arguments for matrix to dispatch on:
The dispatcher was supporting any signature for dispatched functions.
Since each dispatchers is an instance of the `Dispatcher` class and cython does not support patching methods, it had to find the inputs matrix to convert from `__call__(*args, **kwargs)` and re-implemented the `_bind` method to do so.
But all our dispatched functions have the matrix as the first positional argument, by embracing this we get a nice speed up for small matrices.
Also when the specialization existed, it would not call it directly, but call  a `_constructed_specialisation` that called ti. Adding another unneeded layer to each calls. This was changed so it would call the function directly.
For a 2x2 …

Optimize dispatcher by using positional only arguments

---

doc/changes/2150.misc
qutip/ipynbtools.py
qutip/solve/parallel.py
qutip/solve/pdpsolve.py
qutip/solve/stochastic.py
qutip/solver/correlation.py
qutip/solver/floquet.py
qutip/solver/parallel.py
qutip/solver/solver_base.py
qutip/tests/test_progressbar.py
qutip/ui/progressbar.py

- Add a test for progress bars.
- Make `start` private. `start` was mostly used right after the initialization. The docstring indicated that it was not needed, but it was for most bars. #2148
- Remove the iteration argument in update.
- Have `HTMLProgressBar` import ipython.
Fix the issue #2148 for master.
Replace #2127

Add a test for progress bar

---

doc/changes/2153.feature
qutip/core/data/constant.py
qutip/core/operators.py
qutip/tests/core/data/test_mathematics.py
qutip/tests/core/test_operators.py

`qeye_like`, `qzero_like` and the data layer version, `identity_like` and `zeros_like` came up as useful in multiple conversation.
I added them with tests, but I did not go through the code to use them.

Add `qeye_like` and `qzero_like`

---

qutip/core/cy/qobjevo.pyx
qutip/core/gates.py
qutip/core/metrics.py
qutip/core/operators.py
qutip/core/qobj.py
qutip/core/superoperator.py
qutip/solver/correlation.py
qutip/solver/countstat.py
qutip/solver/propagator.py
qutip/solver/result.py
qutip/solver/steadystate.py
qutip/tests/core/test_gates.py
qutip/tests/core/test_operators.py
qutip/tests/solver/test_propagator.py

Change `qeye` to `qeye_like` and `qzero` to `qzero_like` when appropriate.
`qeye_like` is now able to accept `QobjEvo` to use it in propagator etc.
Fix the bug in propagator with super-operator input found in #2152...

Use `qeye_like`

---

doc/guide/dynamics/dynamics-time.rst
qutip/core/coefficient.py
qutip/tests/conftest.py
qutip/tests/core/test_coefficient.py
qutip/tests/solver/test_integrator.py
qutip/tests/solver/test_mesolve.py
qutip/tests/solver/test_sesolve.py

- Add a mention that filelock is needed for string coefficient compilation in the guide.
- When a string coefficient is used, a warning will be raised (once) if either cython or filelock is missing.
- Skip string coefficient compilation test when cython is present by filelock is not instead of only checking for cython.
fix #2162

Add warning for missing Filelock

---

qutip/core/tensor.py
qutip/tests/core/test_qobj.py
qutip/tests/solver/heom/test_bofin_solvers.py
qutip/tests/test_wigner.py

Fix for the numpy 1.25 release.
- `np.product` deprecated, `np.prod` suggested instead.
- Single elements array can no longer be implicitly converted to scalar: `a[i] = bra @ ket` raise a warning since `bra @ ket` is a one elements array.
- Some tests where removed since they expected one element array to be used as a scalar.

Update for numpy 1.25 deprecations

---

.github/workflows/tests.yml
doc/changes/2083.misc
qutip/fastsparse.py

Fix for scipy 1.11.
`cvxpy` does not work yet with the latest scipy version. I changed one of the test to run with the latest scipy but no `cvxpy` to confirm the fix is working.
Close #2182 
(Nothing to fix for v5)

scipy 1.11 fix

---

doc/changes/2118.bugfix
qutip/mesolve.py
qutip/tests/test_mesolve.py

Fix a bug where `mesolve` would fail when it's `e_ops` were a list containing callable(s).
fix #2118

mesolve e_ops list can mix callable and Qobj

---

doc/changes/2129.misc
qutip/qobj.py
qutip/tests/test_ptrace.py

`ptrace` tracing nothing with ket input will return a density matrix.
fix #2129

ptrace always return density matrix

---

doc/changes/2181.bugfix
qutip/visualization.py

Increase missing colorbar padding for matrix_histogram_complex() from 0 to 0.05.

matrix_histogram_complex() colorbar pad to 0.05

---

qutip/legacy/rcsolve.py

Move `rcsolve` ot legacy.
`rcsolve` does not have any tests, has little documentation and can fail for not obvious reasons...
It also seems that most groups create their own flavour of the solver instead of using the one we provide.

Move `Rcsolve` to legacy.

---

qutip/core/cy/_element.pxd
qutip/core/cy/_element.pyx
qutip/core/data/norm.pxd
qutip/core/data/norm.pyx
qutip/solver/integrator/explicit_rk.pxd
qutip/solver/integrator/explicit_rk.pyx
qutip/solver/sode/_sode.pyx

In cython code, signals (Keyboard Interrupt) are not automatically checked.
And when checked, if error are not properly passed (`expect *`) the signal can be last.
This happened in the Runge Kutta integrator, which did not properly passed errors and only when back to python space at time in `tlist` which can be far apart.
The stochastic solver stop on (Keyboard Interrupt), the `except` are not needed since the output is a class. I made it explicit for clarity.
Doing a few tests, I saw that the error was often caught in the `Qobj.data` property called by `QobjEvo.matmul`. This means more back and forth between python and cython was done than needed.

Add signal check in vern integrator

---

doc/changes/2192.misc
qutip/tests/test_visualization.py

**Checklist**
pytest for #2170

pytest for visualization.py

---

pyproject.toml
requirements.txt
setup.cfg

Cython 3 has been released, but has a bug that stop us from using it. See #2151.
This fix the version to 0.29.X

Set version requirement to exclude cython 3

---

doc/changes/2204.misc
pyproject.toml
requirements.txt
setup.cfg

Couldn't make #2202 work...
There are segfault in brmesolve with cython 3.0.0 and the new compilation method does not work properly on windows. 
This replace the PR with a simple limitation to not use cython 3.0.0.

Fix cython version to pre 3.0.0

---

doc/changes/2208.bugfix
qutip/qobj.py
qutip/tests/test_qobj.py

Adding ket to scalar work by adding the scalar to all non-zero entries.
This operation is not well defined and modify the original object, (see #2208).
This fix by having the operation raising an error instead.
Fix #2208

Fix adding non-square `Qobj` to scalar

---

.github/workflows/tests.yml

Python 3.6 tests fail to build cvxopt, there was a new version released last week.
This simply run these tests without it.

py3.6 tests run without cvxopt

---

doc/changes/2216.bugfix
qutip/stochastic.py
qutip/tests/test_stochastic_me.py
qutip/tests/test_stochastic_se.py

Fix a few issues with the stochastic solver state output:
- States were stored even when `options.store_states = False`.
- `options.average_states` needed `options.store_states` to be also set to take effect.
- `ssesolve` would average ket directly instead of using density matrices.
With this, `result.traj_states` will only be set when `options.store_states` is and `result.avg_states` is always set when `options.average_states` is.
fix #2216

Fix for 2216

---

doc/changes/2219.misc
qutip/animation.py
qutip/tests/test_animation.py
qutip/tests/test_visualization.py
qutip/visualization.py

**Checklist**
sphereplot and plot_spin_distribution accepts a matrix of values, theta and phi, but the order of them is different and not intuitive to users.
```
def sphereplot(theta, phi, values, ...
```
```
def plot_spin_distribution(P, THETA, PHI, ...
```

sort args of sphereplot

---

doc/changes/2222.feature
qutip/solver/parallel.py
qutip/tests/solver/test_mcsolve.py
qutip/tests/solver/test_nm_mcsolve.py
qutip/tests/solver/test_parallel.py

When making #1710, we had the capacity for multi trajectory solvers to end up early when a certain precision is reached.
But when splitting it into 2 PRs: #1889 and #1972. `parallel.py` changes where forgotten... Thus even if `MultiTrajResult.add` properly sent the signal to stop, it did not...

Add early termination in map functions according to reduce_map output

---

doc/changes/2224.bugfix
qutip/core/data/add.pyx
qutip/core/data/csr.pyx
qutip/core/data/dense.pyx
qutip/core/data/dia.pyx
qutip/core/data/kron.pyx

When allocating memory in cython, we did not check if the memory was allocated or not due to lacking RAM.
`kron_dia` was particularly inefficient for `bra & ket` combination., which caused a segfault in the `steadystate` benchmarks.

Add insufficient memory checks

---

qutip/bloch.py
qutip/tests/test_bloch.py
qutip/tests/test_visualization.py
qutip/visualization.py

Fix warnings and errors coming from matplotlip 3.8 release.
- Close figure in errors tests. Lot of empty figures were created and never closed.
- `plt.contourf` can be used as an artist instead of extracting the artists list from it.
- `color` cannot be a numpy array anymore, convert the arrays to list.

Fix for matplotlib 3.8

---

qutip/tests/core/data/test_linalg.py

Tests are using numpy's svd but the dispatched function is using scipy's svd.
They use different algorithms and can give different result causing error in the tests.
With this PR, scipy is used in test also.

Use scipy's svd in tests.

---

doc/changes/2234.bugfix
qutip/solver/mcsolve.py
qutip/solver/nm_mcsolve.py
qutip/tests/solver/test_nm_mcsolve.py

The `improved_sampling` option was recently added to the `MCSolver`. `NonMarkovianMCSolver` extends `MCSolver` and can therefore be called with `improved_sampling=True`. Without this PR, it would then silently return wrong results.
The technical reason is that `nm_mcsolve` calculates the value of an influence martingale, which is factored into the calculation of expectation values in the custom result class `NmmcResult`. If `improved_sampling` is enabled, `McResultImprovedSampling` is used instead.
I here only disable the `improved_sampling` option for `nm_mcsolve` and print a warning if a user tries to use it. I have created a new issue to discuss ways to implement the improved sampling for `nm_mcsolve`.
**Related issue**
https://github.com/qutip/qutip/issues/2235

Disable improved sampling for nm_mcsolve

---

qutip/core/coefficient.py

Add `build_dir` to set the cythonize build location to the `CompilationOptions`.
Fix #2230 for v5

Add `build_dir` to compilation options.

---

qutip/core/data/csr.pyx
qutip/core/data/solve.py
qutip/solver/steadystate.py
qutip/tests/solver/test_steadystate.py

Speed up `steadystate`, mainly for the `direct` method with the `dia` method, but some of the optimization affect most calls.
- liouvillian(H) + lindblad_dissipator(c_ops) is slower that liouvillian(H, c_ops) by about 2x.
-  Dia are bad with vectors, the `kron(bra, ket)` in `_steadystate_direct` alone was ~90% of the compute time. Using `CSR` instead is much faster.
- Dia to CSR conversion are about made 100x faster.
Overall, the timing for `Dia` is about 20x faster and 10% faster for `CSR`

Faster steadystate, mainly for Dia

---

doc/changes/2262.bugfix
qutip/solver/result.py

Currently, result objects store a reference to the solver object that created them. I think this is an accident. The options field of a solver is an instance of `_SolverOptions` (see [here](https://github.com/qutip/qutip/blob/454b61529d7bf3c37f74c17925a749fcb046c364/qutip/solver/solver_base.py#L312)), which gets stored in the result [here](https://github.com/qutip/qutip/blob/454b61529d7bf3c37f74c17925a749fcb046c364/qutip/solver/solver_base.py#L147). `_SolverOptions` has a `_feedback` field which is assigned an instance method of the solver and thus keeps a reference to the solver.
I noticed this issue when I called `qsave` on a result object and the resulting file was ~100 MB instead of the expected ~100 KB. Setting `result.options._feedback = None` before calling `qsave` …

Make sure result objects don't store references to corresponding solver objects

---

doc/changes/2269.bugfix
qutip/simdiag.py
qutip/tests/test_simdiag.py

Use `scipy.linalg.eigh` instead of `scipy.linalg.eig` for `qutip.simdiag` in order to ensure returned eigenvectors are always orthonormal. Since `simdiag` requires operands to be commuting and hermitian, this change should be justified.
I did not add any new tests as this bug only occured in very rare circumstances. If desired, I could add the reproducing code from the related issue as a test case.
Fixes issue #2268

fix simdiag not returning orthonormal eigenvectors

---

doc/changes/2172.bugfix
doc/changes/2272.bugfix
qutip/core/qobj.py

When a `Qobj` is present in the output of a Jupyter cell, e.g. when running:
```python
qt.fock(2, 0)
```
the output, which contains LaTeX code, is displayed in Markdown. The aim of this PR is to display the LaTeX output correctly. Replacing the `equation` environment in the LaTeX code with `$$...$$` and changing the `array` environment alignment from `*{11}c` to `cc` causes the vectors and matrices to display in the expected mathematical typeface. A test has not yet been provided, because the change was to a stored raw string; if a test is needed then the presence of this syntax in the string could be detected.
Fixes #2172

Fix LaTeX display of Qobj state in Jupyter cell outputs

---

doc/changes/2280.bugfix
qutip/solver/mcsolve.py
qutip/solver/multitraj.py
qutip/solver/nm_mcsolve.py
qutip/solver/parallel.py
qutip/solver/solver_base.py
qutip/solver/stochastic.py
qutip/tests/solver/test_parallel.py

**Background**
Since I am planning to add an mpi_parallel_map to the parallel module, I had a detailed look at the current implementations of parallel_map and loky_pmap. In the case of timeouts, errors or interrupts, I found surprising behavior. I will first summarize the current behavior in these situations, and then the behavior if my changes are included. It seems difficult to write better unit tests for such timing-sensitive behavior, but I have tested in detail on both Linux (WSL) and Windows.
**Current behavior**
&nbsp; | `parallel_map` | `loky_pmap`
---|---|---
Timeout | Finishes currently running tasks, <br> then returns results of all finished tasks. | If `fail_fast`, behaves similarly to `parallel_map`. <br> Otherwise, completes all tasks but only returns <br> results of those …

Parallelization fixes

---

.github/workflows/tests.yml
doc/changes/2287.bugfix

Over the holidays a new versions of cython and setuptools came out resulting in pyximport raising a deprecation warning.
For v4.7, I just set it to ignore the warning in tests.

Ignore deprecation warnings from pxyimport in tests

---

.github/workflows/tests.yml
doc/changes/2288.bugfix

Cython 0.29 is raise a deprecation warning when used with the newest setuptools.
Ignore these warnings in tests.

Ignore deprecation warnings from cython 0.29

---

doc/changes/2283.misc
qutip/superop_reps.py

`np.tensordot` is faster than a triple loop. On my applications the function became up to 100 times faster.
Also, the way to handle `dims` of the Choi matrix was incorrect (or I misunderstood something). It is explained in the comments.
This was coded in collab with [Rafael Haenel](https://github.com/rafaelha).
Also, please, could you make a release of the qutip 4 with all the new changes after this PR passes?

Make `kraus_to_choi` faster by using numpy

---

qutip/core/cy/qobjevo.pyx
qutip/core/dimensions.py
qutip/core/qobj.py
qutip/tests/core/test_dimensions.py

Looking at the [historical benchmarks](https://qutip.org/qutip-benchmark/ops/matmul.html), Qobj operations got slower last November, which correspond to when we merged the dimensions PR. This PR is to improve those graph. Usually, when a lot of matrix operations are done, we use the data layer object directly. So the overhead of the Qobj should not be that critical.
Adding QobjEvo support to `isbra`, `isket`, etc, slowed them down quite a lot. The import of QobjEvo in the function can easily be slower than the matrix operation. (0.7us for the import which is the same as a 32x32 CSR@ket product.) This is the biggest culprit in the jump in the matmul benchmark graph. I added properties for each `is_type_` to Qobj and QobjEvo.
The `Qobj` and `QobjEvo`'s `issuper` where not …

Faster Qobj matmul (less overhead from dimensions)

---

qutip/tests/solver/test_steadystate.py

Scipy 1.12 rename a variable in linalg solver: `tol` to `rtol` and raise a deprecation warning with the old name.
Scipy 1.11 does not accept `rtol`. This parameter is passed thought `**kwargs` in steadystate and is not used elsewhere, so only the test need to be updated.

Fix for scipy 1.12 in tests

---

doc/changes/2300.bugfix
doc/changes/2305.bugfix
qutip/parallel.py

Remove use of scipy.array in parallel.py, which is incompatible with scipy==1.12
Fix #2300

fix: import array from numpy instead of scipy

---

.github/workflows/build.yml
.github/workflows/tests.yml
pyproject.toml
requirements.txt
setup.cfg

Updated the test matrix, removing test using older version of python, scipy and numpy to add new versions.
Matrix include all python versions from 3.9 to 3.12, all scipy from 1.8 to 1.12, all numpy from 1.22 to 1.26.
I keep test with no cython, cython 0.X and 3.X. With and without mkl and all 3 os.
Added python 3.12 to the list of build wheels, but removed 3.8.
Increase minimum version of scipy and numpy in requirement to match those we actually tests.

Update test matrix to include python 3.12

---

qutip/cy/stochastic.pyx
qutip/steadystate.py

Scipy 1.12 changed parameter `tol` to `rtol` in sparse solver, with a deprecation warnings.
We already filter parameters for these function in steadystate, so I added another layer.
Also fixed it in stochastic implicit methods.

Update to fix scipy1.12 deprecation warnings

---

doc/changes/2311.misc
qutip/tests/test_animation.py
qutip/tests/test_ipynbtools.py
qutip/tests/test_visualization.py

Tests would fail to run if `matplotlib` or `ipython` were not installed.
This add `pytest.importskip` to skip instead or failing the the packages are missing.

Ensure tests can pass without ipython and matplotlib

---

doc/changes/2313.misc
qutip/solver/sode/rouchon.py
qutip/solver/sode/sode.py
qutip/tests/solver/test_stochastic.py

Fix failing `test_stochastic.test_deprecation_warnings`.
It used to catch the first warnings, the one we tested for, and stop.
An update in pytest, made it continue to catch another warning (step rounded to 0) later and failing.
This PR fix the test to raise only the desired warnings.
It add a warnings for when the step in rounded to 0 and a test for that warning.

Bug.warnings stochastic

---

doc/changes/2303.feature
qutip/solver/heom/bofin_solvers.py
qutip/solver/mcsolve.py
qutip/solver/result.py

**Checklist**
Add a new store_density_matricies option to Result
Fixes #2299

Add new store_density_matricies Result option

---

doc/changes/1974.bugfix
qutip/bloch.py

Allow V5 to accept customization of point colors as it did in V4. To keep the changes implemented in V5, I have created a new variable to store the colors that are applied to the points (_inner_point_color_), so in total we now have three variables:
_inner_point_color_: Defined as an argument in the _add_points_ function, this variable takes precedence over the others.
_point_color_: This variable stores a list of colors, reminiscent of V4, and is utilized when _inner_point_color_ is not specified.
_point_default_color_: A list of colors that serves as the default when neither of the other variables is defined
fix #1974

Add the possibility to customize point colors as in V4

---

.github/workflows/build_documentation.yml
doc/rtd-environment.yml
setup.cfg

Removed `mpi4py` from `full`. 
It is hard to install locally (for the users) and in readthedocs, where it is not actually used (#2317).
I am not sure what it is the best practice for this. `full` should normally include every optional dependency, but mpi4py is too specialized and not useful for most users. If it makes qutip harder to install since `pip install qutip[full]` would fail for most, maybe it's better to leave it out.
Also updated some versions.

Remove mpi from full and update versions

---

qutip/core/operators.py
qutip/core/states.py

In #2314, it was found that Qobj creation functions could return an unexpected dtype for incomplete data layers.
For example if `mul` specialization is missing `scale * basis(..., dtype)` would not return a Qobj using dtype.
I reviewed functions in states.py, operators.py and random_object.py.

Ensure dtype in Qobj creation functions.

---

doc/changes/2323.bugfix
qutip/countstat.py

`countstate` sometime add a small value to stabilize the linear equation solver.
But this value was too small and rounded off by the tidyup step.
In most case, the solver (with the fall back) would still be able to find the solution, but not always.
#2316 is one such case.
fix #2316

Make countstate more stable

---

doc/changes/2325.misc
qutip/core/cy/_element.pyx
qutip/core/cy/qobjevo.pyx
qutip/core/data/constant.py
qutip/core/operators.py
qutip/core/qobj.py
qutip/tests/core/test_operators.py
qutip/tests/core/test_qobj.py
qutip/tests/core/test_qobjevo.py

`qzero_like` used on `QobjEvo` would call it (it needed `qevo(0).data`), which is both slow and could break `jax.jit`.
I added `Qobj.dtype` and `QobjEvo.dtype` to be used instead of accessing the data directly.
For `QobjEvo`, the `dtype` property still call the object when the type is unclear (mixed or function based), but it should be faster otherwise.
Tested that the example in qutip/qutip-jax#33 works.

Add dtype to QobjEvo and use it in `qeye_like`

---

doc/changes/2331.misc
qutip/core/expect.py

Fix typos caught in #2331.
fix #2331

Fix typos in `expect` documentation

---

qutip/tests/solver/test_floquet.py
qutip/tests/test_random.py

Increase the tolerance of tests that could randomly fail.
`testFloquetBasis` would fail 1/2000 of the time. The error has a std of 1.2e-5 , but does not follow a gaussian distribution. Fat tails made 4 std not enough.
`test_rand_super` failed once recently in #2919 ( I reran the test). I can't reproduce the failure locally, but it is ran a few hundred of times in each actions, so even a small probability of failure will eventually happen.

Increase test reliability

---

doc/changes/2333.bugfix
qutip/solver/heom/bofin_solvers.py
qutip/tests/solver/heom/test_bofin_solvers.py

Two small bugs crept in in the conversion of the steady_state solver in the HEOM method to QuTiP v5.   Firstly, the system state was returned without Fortran ordering (so it was effectively returned transposed), and the line which was supposed to enforce hermiticity used a conj() instead of an adjoint() so it just deleted the imaginary parts of the off-diagonals instead.  
I think none of the notebooks or tests were sensitive to these two compounding issues, but it is fairly easy to make an example which is. This is also added as a rudimentary test, comparing output of the long-time dynamics to the steadystate. I didn't include any parameters to change in that test, but can do so if its useful.
As a comment, the steady-state solver could probably be written to be more like …

Fix heom steady state

---

doc/changes/2342.misc
qutip/__init__.py
qutip/measurement.py
qutip/tests/test_measurement.py

Measurement functions did not take into account degenerate states of the operator. (#1800, #2054)
Also the returned probabilities could be negative. (#2265)
I added a tolerance to these function for the minimal probability. Smaller / negative probabilities are rounded to `0`.
I also changed `measurement_statistics_observable` to support degenerate operators: It always return the projectors, with projectors and probabilities of degenerate sub-systems summed. It also only return the (eigenvalues, projector, probability) set for cases where the probability is greater than `tol`.
fix #1800, #2054, #2029, #2265

Makes measurement support degenerate states

---

qutip/bloch.py
qutip/tests/test_bloch.py

In #2308, the default for `point_color` was changed from `[]` to `None`, but `clear` still set it to an empty list.
This broke a notebook in qutip-tutorial: tutorials-v5/visualization/bloch-sphere-animation.

Fix `bloch.clear` breaking `point_color`

---

qutip/tests/solver/test_mcsolve.py

`test_super_H` can randomly fail, as seen in https://github.com/qutip/qutip/actions/runs/8112849659/job/22174928821.
Trying it locally, it fail with a probability of `~1/500`.
Which is very close to what is expected with the tolerance used in the test.
I loosen the test `atol` for an expected rate of failure of about ~1/100000.

Improve mcsolve's `test_super_H` test tolerance.

---

qutip/core/cy/qobjevo.pyx
qutip/core/qobj.py
qutip/core/superoperator.py
qutip/solver/mcsolve.py
qutip/solver/solver_base.py
qutip/solver/stochastic.py
qutip/tests/test_enr_state_operator.py

With the inclusion of the new dimensions class, stored in Qobj()'s _dims property, the properties of ENR states are described by ENRspace().  However, when using ENR states with mesolve, Liouvillian, sum() and other functions these _dim properties would be discarded.  This PR is a draft attempt to get things working, largely by subbing in _dims instead of dims in various places, and a test to check ENR+mesolve() works for a simple case.
All tests pass, but since this is just some bodging to get things working, and messes a little bit with some core functions maybe its also good to check the tutorial notebooks also pass.
edit: forgot to mention, this is not exhaustive; e.g., sprepost() has not been updated.

Making ENR states work with mesolve()

---

qutip/tests/solver/test_stochastic.py
qutip/tests/test_wigner.py

Fix 2 other tests failing randomly with low probability:
- `test_spin_q_function_normalized`
- `test_m_ops`
`test_m_ops` had a mistake: `measurement`'s shape is not the same for homodyne and heterodyne.

Improve `test_m_ops` and `test_spin_q_function_normalized` stability

---

qutip/core/data/matmul.pyx
qutip/tests/core/data/test_dense.py

There was a logic error in the matmul's `out` shape check making the check too lenient.

Fix logic error in shape check

---

doc/changes/2354.misc
setup.cfg

We allow scipy version 1.12 (released about 2 months ago) to be used with qutip. Scipy 1.12 is already tested in the build matrix https://github.com/qutip/qutip/blob/master/.github/workflows/tests.yml#L93

Remove pin on scipy 1.12

---

qutip/core/qobj.py
qutip/tests/core/test_qobj.py

Currently, the output of printing a `Qobj` always contains `dtype=<class 'str'>`. This fixes it to `dtype=CSR`, `dtype=Dense`, etc.
Previous PR: https://github.com/qutip/qutip/pull/2352

Fixed Qobj string representation

---

qutip/solver/mcsolve.py
qutip/solver/multitraj.py
qutip/solver/stochastic.py

A few proposed changes to internals of the MultiTrajSolver and its subclasses. The changes are (a) to increase consistency between the monte carlo solvers and the stochastic solvers, (b) to reduce repeating code from MultiTrajSolver in the subclasses, (c) to fix some documentation.
* Renamed `_MTSystem` and `_MCSystem` into `_MultiTrajRHS` and `_MCRHS` to make them analogous to `_StochasticRHS`. Removed distinction between `.system` and `.rhs` which seemed unnecessary and confusing to me (please tell me if I'm wrong).
* Made `_integrate_one_traj` use the integrator's run method (which doesn't do anything special currently, but I imagine that it could potentially be implemented more efficiently than repeated calls to integrate). Made subclasses use `_run_one_traj`, `_integrate_one_traj` …

Multi trajectory solver: minor internal changes

---

doc/changes/2363.doc
qutip/core/states.py

In projection(dim, m, n, ...), m,n are Fock state numbers, so must be integers.  Also matches the docstring of basis() which is used by projection().

Fix argument type in doctring of projection()

---

.github/workflows/build.yml

We fixed cybuildwheel version to a version prior to 3.12 release. To build wheels for 3.12 we need to update it.

Update cibuildwheel version

---

CONTRIBUTING.md
README.md
setup.cfg

A few links to the documentation are broken because we moved to readthedoc.

Fix broken links for the doc

---

doc/requirements.txt
doc/rtd-environment.yml

@ajgpitch noticed that search is not working on our ReadTheDocs site. Some digging revealed that this was broken in sphinx-rtd-theme before 1.2.1 (https://github.com/readthedocs/sphinx_rtd_theme/pull/1448/). This PR updates the documentation builds to use version 1.2.1.
We'll need to merge this change to all release branches for search to work correctly on those builds.
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1448/

Update sphinx-rtd-theme to fix search.

---

README.md
qutip/core/coefficient.py
setup.cfg

- setuptools is used for cython coefficient compilation, but was not in the requirements.
- The readme still had a note saying that v5 was in alpha, now that it is released, it should be removed.

Update the readme note for v5 and add setuptools requirement

---

.github/workflows/tests.yml
doc/changes/2383.misc
setup.cfg

Scipy 1.13 change the way sparse operations are done.
Some changes to scipy fix most issues, but I get some segfault with the sparse eigen solver and I am unable to run all tests.
1.13 work with v5 so I changed the requirements to exclude that version in v4.7.

Set requirements to refuse scipy 1.13

---

doc/changes/2280.bugfix
qutip/core/tensor.py
qutip/tests/core/test_tensor.py

Use CSR as the default for expand_operator because the output is usually sparse.

Use CSR as the default for expand_operator

---

doc/changes/2382.bugfix
qutip/solver/result.py
qutip/tests/solver/test_mcsolve.py

Previously, if you specified a target tolerance when using `mcsolve`, the result's `end_condition` would show "target tolerance reached" regardless of whether this was true. I added a line to check this and set `end_condition` to "ntraj reached" when appropriate.

fix end condition on mcsolve when using target tolerance

---

doc/changes/2393.bugfix
qutip/solver/steadystate.py
qutip/tests/solver/test_steadystate.py

Two small bugs appeared in floquet steadystate in v5, this is a quick patch.
Two bugs:
1) Small minus sign error in one of the terms (comparing to v4.7 and what is written in the old toolbox guide).
2) Some kind of data copying confusion with the S and T operators when updating their data contents with the results.  Just initiating these two separately seems to fix it.
other minor fix: updated the link to the toolbox guide
Some other minor niggles that I didn't fix:
- some of the optional solver methods dont work (seem not to support square right hand sides in '_data.solve()'.  I didn't dig much on fixing these though
- the 'splu' method fails for a couple of reasons. I can get it to work by removing the choice of warnings as errors in 'solve.py' (which make it fail in …

fix two bugs in floquet steadystate

---

qutip/core/cy/coefficient.pyx
qutip/tests/core/test_coefficient.py

`qutip.coefficient` accept scipy's CubicSpline input, but only work for complex `y` array:
```
x = np.linspace(0, 1, 11)
y = np.exp(-1j*x)
H = qutip.QobjEvo([H0, scipy.interpolate.CubicSpline(x, y)])
```
worked, but 
```
x = np.linspace(0, 1, 11)
y = np.sin(x)
H = qutip.QobjEvo([H0, scipy.interpolate.CubicSpline(x, y)])
```
did not. 
This add support for CubicSpline built using real array. 
Also add a test for both real and imag arrays + using both PPoly (parent class of CubicSpline) and Bspline (another spline class of scipy.)
bug reported in: https://groups.google.com/g/qutip/c/MS0r6YNFkd8/m/0_cPnqheAQAJ

PPoly and Bspline accept real coeff + tested

---

qutip/solver/propagator.py

Clarify propagator's `t` input.
Fixes #950

Improve propagator doctring for `t`

---

doc/development/release_distribution.rst

The website now direct to readthedocs for documentation.
I updated the `release_distribution` guide to not copy the docs file into qutip.github.io but update the readthedocs links.

Update the release guide to use readthedocs 

---

.github/workflows/tests.yml

A new version of mac in github runners is not compatible with [setup-miniconda](https://github.com/conda-incubator/setup-miniconda/issues/344).
Until they fix it, to run on mac, we need to fix the mac version.

Fix macos version in runners

---

qutip/solver/integrator/krylov.py
qutip/tests/solver/test_sesolve.py

The error for too large minimum step was not raised.
The error therefore came later in scipy code and was hard to understand. 
Found from https://groups.google.com/g/qutip/c/NUcKnAwpx30/m/7IKDqbNOAgA
Fix the error and add a test for it.
Also added some sanity check on `min_step` and `max_step`, which could create infinite loop if `min_step = 0` or `min_step > max_step`.

Fix raise on too large min_step in krylov

---

qutip/tests/solver/test_nm_mcsolve.py

`test_nm_mcsolve.test_super_H` [failed in master's test](https://github.com/qutip/qutip/actions/runs/8807804559/job/24175678290). 
Same issue as #2344. The tolerance is too tight and the test can fail randomly with a low probability.

Increase `test_nm_mcsolve.test_super_H` tolerance

---

.github/workflows/build_documentation.yml
doc/changes/2413.misc
doc/installation.rst
doc/requirements.txt
setup.cfg

Set minimum python version to 3.9 for v5. While we don't use many feature that prevent previous version, we don't test them and pip install does not work because of conflict with `oldest-supported-numpy` (see #2412).
Improve `installation.rst`, it still listed requirement for v4, openmp support and instruction on installing v5's pre-releases.
[Exclude numpy 2 from requirements.](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice) We don't know if we are compatible yet.

Add minimum python version requirement

---

doc/changes/2409.doc
doc/guide/guide-bloch.rst

Before the change:
After the change:
I am using 
```
python==3.11.6
qutip==5.0.1
matplotlib==3.8.3
```
fix #2156

Fix #2156 code of Bloch animation in doc

---

pyproject.toml

In #2413 I updated `setup.cfg` but forgot `pyproject.toml`.

Syncronize setup.cfg and pyproject.toml requirements

---

qutip/tests/solver/test_stochastic.py

The test for the new method `run_from_experiment` has a time step too long for the euler method. This would cause fail once a few hundreds time as in https://github.com/qutip/qutip/actions/runs/8979789558/job/24662362047.
Reducing the system size with smaller steps makes the test more consistent (no failure in 20000 tries.)
Also reduced `test_feedback` step size to improve that test consistency.

More stable run_from_experiment test

---

qutip/solver/stochastic.py
qutip/tests/solver/test_stochastic.py

When calling `ssesolve` or `smesolve` without any stochastic collapse operators but `store_measurement` set to True, there is an IndexError. This PR fixes the error and adds a test for this situation.
Example code:
```python
r = qt.ssesolve(qt.sigmaz(), qt.basis(2, 1), [0, 1, 2], options={'store_measurement': True}, ntraj=15)
```

Stochastic solvers small bugfix

---

doc/biblio.rst
doc/changes/2416.feature
qutip/core/metrics.py
qutip/tests/core/test_metrics.py

The diamond norm [1] is a commonly used metric in quantum information theory for calculating the distance between two quantum channels. It has a number of useful properties making it the gold standard [2] in the field for several applications. In general, a complex semidefinite program is required to calculate the diamond norm. Although elegant, this approach is very inefficient. Unfortunately, no alternative method has been discovered for calculating the diamond norm in the general case of CPTP channels.
However, in the special case where we are trying to calculate the difference between two unitary channels, a very efficient implementation exists. This makes use of an unproved theorem on page 29 of [1]. I have proved this theorem and elaborated an efficient algorithm to calculate the …

Improve dnorm efficiency in unitary case

---

qutip/core/cy/qobjevo.pyx
qutip/tests/solver/test_mcsolve.py

Fix the bug in collapse feedback that made it work properly only for the first trajectories. (#2422)
Also added a check in the feedback test to ensure the collapse argument is reset for each trajectories.

Ensure feedback work for all trajectories

---

doc/changes/2425.misc
qutip/core/data/matmul.pyx
qutip/core/data/properties.pyx
qutip/core/qobj.py
qutip/tests/core/data/conftest.py
qutip/tests/core/data/test_properties.py
qutip/tests/core/test_qobj.py

As proposed in  #2420,  changed `Qobj.__eq__` to use both `rtol` and `atol`.
The a new low level function is needed to support `rtol`.
Also I found that our test did not properly shuffled CSR matrices indices in mathematics tests. There was a bug we missed in `multiply_csr`...
fix #2420

Add `rtol` to `Qobj.__eq__`

---

.github/workflows/build.yml
.github/workflows/build_documentation.yml
.github/workflows/tests.yml

We have warnings for actions using deprecated node.js version, such as:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/download-artifact@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Updating the tools from v3 to v4 should fix the issue.

Update actions tools versions

---

doc/changes/2436.doc
doc/conf.py
qutip/core/coefficient.py
qutip/core/cy/qobjevo.pyi
qutip/core/qobj.py
qutip/solver/krylovsolve.py
qutip/solver/mcsolve.py
qutip/solver/mesolve.py
qutip/solver/multitraj.py
qutip/solver/propagator.py
qutip/solver/result.py
qutip/solver/sesolve.py
qutip/solver/solver_base.py
qutip/typing.py

Following the workaround in [this stackoverflow answer](https://stackoverflow.com/a/67483317), added `autodoc_type_aliases` to the config of sphinx and added `from __future__ import annotations` where necessary. Makes it so that the docs say
```
H: QobjEvoLike
```
instead of
```
H: Qobj | QobjEvo | ~qutip.typing.QEvoProtocol | tuple['Qobj', typing.Union[ForwardRef('Coefficient'), str, qutip.typing.CoeffProtocol, numpy.ndarray, scipy.interpolate._interpolate.PPoly, scipy.interpolate._bsplines.BSpline, typing.Any]] | ~typing.Sequence[~qutip.typing.QEvoProtocol | Qobj | tuple['Qobj', typing.Union[ForwardRef('Coefficient'), str, qutip.typing.CoeffProtocol, numpy.ndarray, scipy.interpolate._interpolate.PPoly, scipy.interpolate._bsplines.BSpline, typing.Any]]]
```
(Also cleaned up imports in …

Tidy up formatting of type aliases in docs

---

README.md
doc/conf.py
doc/frontmatter.rst
doc/index.rst
qutip/about.py

A user was confused because they were on the readthedocs website, thought that was the main qutip website, and couldn't find the tutorial notebooks. I added a link to the main qutip website and the tutorials section to the landing page of the readthedocs.
I also used the opportunity to update the list of admins in several places to match the admin team as listed on the qutip website. Meaning, mostly, I added @AGaliciaMartinez , myself, and @flowerthrower . Let me know in case that isn't okay and I will undo it.

Small doc updates

---

doc/changes/2443.bugfix
qutip/solver/steadystate.py
qutip/tests/solver/test_steadystate.py

The permutation function used in v5 is reversed from v4, (it does `out[perm] = in`). This was not taken into account when updating the steadystates permutations functions.
Fixed and added tests.
fix #2443

Fix bug in steadystate where permutation was inversed

---

doc/changes/2437.feature
doc/guide/dynamics/dynamics-monte.rst
qutip/solver/mcsolve.py
qutip/solver/multitraj.py
qutip/solver/nm_mcsolve.py
qutip/tests/solver/test_mcsolve.py
qutip/tests/solver/test_nm_mcsolve.py

Enables use of `mcsolve` and `nm_mcsolve` with mixed initial conditions.
Added functions `run_mixed` to the MCSolver and NonMarkovianMCSolver classes. Instead of an initial pure state, these functions take either a density matrix or a list of `(psi_i, p_i)` where `psi_i` are pure initial states and `p_i` are the weights for the average over the initial states. In the latter case, the `ntraj` parameter can be a list specifying the number of trajectories to be used for each initial state. The trajectories automatically obtain correction weights if the fraction of trajectories starting in `psi_i` does not match `p_i`.
The functions `mcsolve` and `nm_mcsolve` take either a pure state or a density matrix as the initial state, and call either `run` or `run_mixed` of the solver, …

Monte-Carlo simulations with mixed initial states

---

doc/changes/2400.bugfix
qutip/visualization.py

**Checklist**
Fixes the rendering problem, upon going over matplotlib docs and discussions around [similar issues](https://github.com/matplotlib/matplotlib/issues/13728), I discovered that zsort was not set in when calling the ax.bar3d , I have set the sort to max which fixes the bars being rendered incorrectly. @BoxiLi  The PR is up for review , it should fix the rendering …

Fixing rendering problem

---

doc/changes/2453.feature
qutip/core/data/expm.py
qutip/core/qobj.py
qutip/tests/core/data/test_mathematics.py

Add dispatcher for `sqrtm` in `qobj.py`. This will help us to create a similar function in `jax` for `sqrtm` specifically.
This PR creates a dispatcher function for `sqrtm` that uses `scipy.linalg.sqrtm` to compute square root of a matrix
**Previous PR**
PR #2452  had some merge issues that were difficult to solve. Also merged the suggestions from the last PR.

[Fixed] Add dispatcher for sqrtm

---

doc/changes/2454.bugfix
qutip/solver/integrator/explicit_rk.pyx
qutip/tests/solver/test_integrator.py

Multiprocessing for `vernN` methods was failing because `Explicit_RungeKutta` objects were unpicklable. This PR adds a helper method `__reduce__` in that class to help with pickling. 
fix #2450

Add parallelization support for `verN` integrators

---

.github/workflows/tests.yml
doc/changes/2457.misc
pyproject.toml
qutip/core/data/expm.py
setup.cfg

Last week we added numpy 2 support but did not update the requirements in `setup.cfg`.
This update dependency to build using numpy 2 instead of oldest-supported-numpy.
I also increased the minimum requirements for matplotlib and scipy to version tested.
I added more test using numpy 2, only one tests build and run using numpy 1.X.
I added more windows / mac tests. Using these os for testing numpy versions and no cython.
`cvxopt` (`dnorm`) does not run with numpy 2 yet, so it's only tested with older numpy version.
Fix sqrtm needing copy. This mean that the test intended to run with numpy 2 previouly did not...

Update requirement to include numpy 2

---

doc/changes/2461.feature
qutip/core/metrics.py
qutip/core/options.py

This PR adds backend support to `metrics.py`. This change will help us to change backend to `jax.numpy`
A PR would be created to add the changes to `qutip-jax`
**Note**
`'fidelity', 'tracedist', 'bures_dist', 'bures_angle', 'hellinger_dist', 'hilbert_dist'` are tested and working with `jit`.
`'average_gate_fidelity', 'process_fidelity', 'unitarity', 'dnorm'` are not working as of now. I am finding some issues with testing them.
Only `trace_dist` and `hilbert_dist` are working with `grad` as there is no support for `sqrtm` in grad.

add support for jit and grad

---

qutip/solver/mcsolve.py
qutip/solver/multitrajresult.py
qutip/tests/solver/test_mcsolve.py
qutip/tests/solver/test_results.py

Fix issues with multi- trajectory results:
- When one result had trajectories and the other did not, but both stored the states, the merged result had no states.
- When merging 2 results with default ratio, that ratio would depend on whether the `improved_sampling` options was used. 
- When the no-jump probability was 1, the total weight as measured by sum(res.runs_weight) would not be one.
- A no-jump probability over 1 by numerical error would break the evolution.
- Fix weight application in the `_target_tolerance_end`. (At `abs_weight == 1`, the error should be 0).
- `average_final_state` not being computed properly when runs were stored.
This PR is a part of #2455. (1/4?)
The absolute weighted trajectories are still mixed with the other. (#2455 fixed the issues by not …

Multi Trajectory solver bugfixes

---

doc/changes/2473.misc
qutip/core/gates.py
qutip/core/operators.py
qutip/core/qobj.py
qutip/core/states.py
qutip/random_objects.py
qutip/tests/test_random.py
qutip/typing.py

Add type hints to function that create `Qobj` (`states.py`, `operators.py`, `gates.py` and `random_object.py`).
I also ran `mypy` on these files and fixed easy issues (`Qobj * Qobj` -> `Qobj @ Qobj`).
Some points to look at more closely: 
- We have a lot of `int, list of int, list of list of int, Space` etc. But what is actually accepted can change:
- `basis` can take super operators dimension to create an `operator-ket`, but not if `offset` is used.
Should we raise an error and officially not support these case or arrange it so offset is `supported`?
- Is `SpaceLike` an alias useful for these case or just confusing?
- Array of Qobj output have been changed to list of Qobj.
- I did not update most docstring. `qdiags` dims are `DimensionLike` in type hints, but `list` in …

Types.creators

---

.github/workflows/build.yml

`actions/upload-artifact@v4` and `actions/download-artifact@v4` have breaking change cause the 5.0.3 release to miss wheels on pypi.
Different jobs in one workflow can't create artifacts with the same name. (but not on retry).
Download artifact only download artifact from one job without the proper options.
(https://github.com/actions/upload-artifact/issues/478)
- Upload to different artifacts per OS.
- Merge artifacts when downloading.
- Add test that all wheels and source are available before pypi release.
- For test build, built artifacts are listed.

Adapt to download / upload artifacts v4

---

.github/workflows/build.yml

Fix the pipeline after latests changes in #2476. Now distribution is in wheels folder too.

Distribution is now also in wheels.

---

doc/changes/2466.bugfix
qutip/piqs/piqs.py

Dicke density state matrix should only have positive eigenvalues, but rounding errors causes eigenvalues of 0 to instead be represented as a very small negative number.
This causes `dicke_trace_function` to return -Inf, since `scipy.special.entr` returns -Inf for any values < 0.
This issue was fixed by simply taking the absolute value of the eigenvalues in dicke_trace_function, which we are allowed to do since the density state matrix should only have positive eigenvalues.
fix #1919

Fixed Dicke Entropy returns -Inf #1919

---

doc/changes/2445.bugfix
doc/guide/guide-bloch.rst
qutip/bloch.py

- Fix a dimension problem for the argument `color` of `Bloch.add_states`
```python
bloch.add_states([qt.basis(2,0), qt.basis(2,1)], colors=["crimson", "gold"]) # fails whereas it should work
bloch.add_states([qt.basis(2,0), qt.basis(2,1)], colors=[["crimson"], ["gold"]]) # what works
```
- Clean-up of the code in `Bloch.add_states` as asked in #1913 
- Add `Bloch.add_arc` and `Bloch.add_line` in the guide on Bloch class

Bloch `add_states` color argument dim bug

---

doc/guide/dynamics/dynamics-stochastic.rst

Add a simple example for `run_from_experiement` in the guide.
Also restore the link to the stochastic tutorial notebooks.

Add example of `SMESolver.run_from_experiement` in the guide.

---

qutip/tests/core/data/test_convert.py
qutip/tests/core/test_superop_reps.py

We had some duplicated tests in `test_superop_reps.py`, I removed the old ones.
There was also two tests in `test_convert.py` that had the same name. Renamed one of them.

Remove duplicated tests

---

doc/changes/2493.feature
qutip/measurement.py

This PR fixes Issue 3 mentioned in https://github.com/qutip/qutip-jax/issues/47 on measuring observables with `jax` and `jaxdia` operators via `qutip.measurement.measurement_statistics_observable`, by resolving the deprecation of indexing with lists in JAX.
Closes https://github.com/qutip/qutip-jax/issues/47.

Support measurement statistics for `jax` and `jaxdia` dtypes

---

qutip/core/blochredfield.py
qutip/core/dimensions.py
qutip/core/expect.py
qutip/core/operators.py
qutip/core/options.py
qutip/core/properties.py
qutip/core/qobj.py
qutip/core/subsystem_apply.py
qutip/core/superop_reps.py
qutip/core/superoperator.py
qutip/core/tensor.py
qutip/settings.py
qutip/tests/core/test_expect.py

Add hints for most of the remaining user facing function in `qutip/core`.
Fixed the docstring of `Qobj`: fix #2480
Improved the docstring of `expect` to fix the confusion with array input: fix #2456
I changed `numbers.Number` for `complex` as the later is not recognized by static type checkers.
I also changed the way `qobj.py` handle circular import. This makes it easier to import it and `qobjevo.py` without causing circular import elsewhere.
Changed the type of expect output. It was
|  | qobj oper | list oper |
|---|---|---|
| qobj state | scalar | Array |
| list state | Array | list[Array]  |
and now is
|  | qobj oper | list oper |
|---|---|---|
| qobj state | scalar | list |
| list state | Array | list[Array]  |
With multiple operators, the output dtype, float or …

Add types hints qutip/core

---

doc/changes/2484.bugfix
qutip/core/operators.py
qutip/core/qobj.py

In accordance with our ongoing effort to make `qobj` work with `jax`. This change makes `expm`, `cosm`, `sinm` work with `jax`.

fix expm, cosm, sinm to work with jax

---

doc/conf.py
qutip/core/coefficient.py
qutip/core/cy/coefficient.pyx
qutip/solver/brmesolve.py
qutip/solver/floquet.py
qutip/solver/mcsolve.py
qutip/solver/mesolve.py
qutip/solver/multitraj.py
qutip/solver/nm_mcsolve.py
qutip/solver/sesolve.py
qutip/solver/solver_base.py
qutip/solver/stochastic.py
qutip/tests/solver/test_nm_mcsolve.py
qutip/typing.py

With this most solver have hints. 
I changed the type for `e_ops` to accept single, list and dict instead of just the dict. We almost never use dict in documentation and it was missing in many docstring, so having it as the only hinted type felt wrong.
I also removed the `args` from the `NonMarkovianMCSolver` to make it match the other solvers. It was not used for the Hamiltonian as was indicated in the docstring.

More types hints for solvers

---

doc/changes/2507.bugfix
qutip/entropy.py

`clip` gives deprecation warning, that might be a problem in the future. Hence switch to `where`

Change `clip` to `where`

---

doc/changes/2499.feature
qutip/solver/mcsolve.py
qutip/solver/multitraj.py
qutip/solver/multitrajresult.py
qutip/solver/result.py

As it is already possible to run `mcsolve` with gpus. The next step in the process to make `mcsolve` work with `grad`.
With the changes, I can get
```
`import qutip_jax as qjax
import jax
import jax.numpy as jnp
from functools import partial
qjax.use_jax_backend()
@partial(jax.jit, static_argnames=("omega",))
def H_1_coeff(t, omega):
return 2.0 * jnp.pi * 0.25 * jnp.cos(2.0 * omega * t)
N = 100
with qt.CoreOptions(default_dtype="jaxdia"):
a = qt.tensor(qt.qeye(2), qt.destroy(N))
sm = qt.tensor(qt.destroy(2), qt.qeye(N))
H_0 = 2.0 * jnp.pi * a.dag() * a + 2.0 * jnp.pi * sm.dag() * sm
H_1_op = sm * a.dag() + sm.dag() * a
H = [H_0, [H_1_op, qt.coefficient(H_1_coeff, args={"omega": 1.0})]]
state = qt.tensor(qt.fock(2, 0, dtype="jax"), qt.fock(N, 8, …
```

Enable `mcsolve` with `jax.grad`

---

qutip/core/numpy_backend.py
qutip/core/options.py

Change numpy_backend to contain the numpy implementation in an attribute instead of reading it from the settings each time. This is done by making the options work as a property, when it is set, it update the `np` instance.

Optimize `numpy_backend`

---

qutip/core/superop_reps.py
qutip/partial_transpose.py
qutip/solver/sode/_noise.py
qutip/tests/core/data/test_expect.py
qutip/tests/core/data/test_reshape.py

Numpy 2.1 changed `reshape` signature making `order` keyword only and changing the `newshape` parameter to `shape`.

Fix numpy 2.1 deprecation warnings

---

qutip/tests/solver/test_mesolve.py

A test was failing since the numpy 2.1 release on windows. 
It seems to be related the the way low level libraries are linked, a lower precision was used on windows...
Loosening the ODE tolerance fix the issue.

Fix the failing test with numpy 2.1 on windows

---

doc/changes/2497.misc
doc/guide/guide-settings.rst
qutip/_mkl/spsolve.py
qutip/settings.py

The mkl finding was sometime missing the library even when available.
Sometime the library can has a version number in the file name:
`libmkl_rt.so.2`, `mkl_rt.2.dll`, with or without a symbolic link to the version less name.
Also it ouly look for it if it's found in numpy's config, but the module mkl is available an could be installed even if numpy does not link to it. Our use using ctypes does not require numpy to be using it to work.
So I changed the lookup function to look for the library without checking is numpy uses it. I also added a new setting, `settings.mkl_lib_location`, which is not read only and allow users to enter the path to their mkl implementation. We only look inside the python library path, this would allow to use libraries installed at the OS level. …

Better mkl lookup

---

doc/requirements.txt
doc/rtd-environment.yml

When building the documentation for the action (on locally on my side), we install with `pip`, however with readthedocs, we use manba. Some packages versions are not available on conda-forge, just pypi, causing the rtd build to fall with #2526...

Use versions available on conda

---

doc/changes/2538.misc
qutip/tests/core/data/test_convert.py
qutip/tests/core/test_states.py
qutip/tests/test_random.py

The `4.x` documentation suggests that the user test the installation by
```python
import qutip.testing
qutip.testing.run()
```
and when something fails (e.g. due to missing `matplotlib`), the obvious reaction would be to re-execute `qutip.testing.run()`. However, this does not currently work, because passing a `zip` generator to `pytest.parametrize` limits that test case to be executed only once. This PR does nothing but allowing tests to be executed multiple times in one Python session.
P.S. I would recommend backporting the new shell testing command `pytest qutip/qutip/tests` to the `4.x` documentation.

Allow repeating tests without quitting Python

---

doc/changes/2530.bugfix
qutip/solver/brmesolve.py

When using `brmesolve`, the tensor would always be seen as time-dependent. Which for Bloch Redfield mean computing eigen vectors at each time-step and result is a massive slowdown when not required.
There is no tests, the result does not change. 
fix #2530

Fix `brmsolve` time-dependent a_ops detection

---

doc/guide/dynamics/dynamics-monte.rst

Thank you @hodgestar for noticing that there was nothing about MPI in the Users Guide yet. I wrote a short section based on the example in the `nm_mcsolve` tutorial notebook.

Added MPI section in Users Guide

---

doc/changes/2545.feature
qutip/core/dimensions.py
qutip/tests/core/test_dimensions.py

Added a einsum, a numpy.einsum (Evaluates the Einstein summation convention on the operands.) version for Qobj dimensions.
fixes #2340
** Question: Not sure if I should update the documentation and how. Just in case I did not modify the docs yet.

Add einsum

---

doc/guide/heom/bosonic.rst

In the guide for using HEOM with a bosonic bath, in the description of the Drude Lorentz BCF the Matsubara terms are split between real and imaginary parts. However, in the maths section of the real part, $c_{k,real}$ the $-i$ term remains for $k=0$.  In the python section it is already correctly removed.
This was fixed
for k=0 changed  $` c_{k,real} = \lambda \gamma   [\cot(\beta \gamma / 2) - i] `$ to  $` c_{k,real} = \lambda \gamma   [\cot(\beta \gamma / 2)] `$

c_{k,real} should not have -i in the math section

---

doc/changes/2557.misc
qutip/core/data/dense.pyx

We improve performance of `Qobj` construction by moving the numpy version check out of the `__init__`. On a microbenchmark
```
import numpy as np
x = np.array([1., 0.])
%timeit qt.Qobj(x)
```
performance improves from
```
23.5 μs ± 2.18 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
to
```
8.24 μs ± 732 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

Improve performance of qt.Qobj by static version check

---

.github/workflows/tests.yml
qutip/tests/core/data/test_csr.py

`macos-12` that we use in tests is deprecated and will be removed soon. (https://github.com/actions/runner-images/issues/10721) The issue with `macos-latest` and miniconda is solved, so we can use it once again. 
There is however a warning appearing when converting an array to unsigned int. I had to add a filter for it for the tests to pass.

Update macos version used in tests

---

.github/workflows/tests.yml

The windows tests are failing. The reason is not clear, but it has to do with the base mathematics library. 
This change the tests to use OpenBlas instead of MKL, which does not have the issue.
fix #2563

Use openblas for 'Windows - numpy fallback' tests

---

qutip/distributions.py
qutip/tests/core/test_environment.py
qutip/tests/test_visualization.py

- `mpmath` is optional, so skip tests that uses it when not installed.
This skip all tests in that file when missing. If some bath feature should be tested even when missing, we should skip only these tests .
- Remove `ket2dm(basis(...))` from `parametrize` in visualization tests. Function in parametrize decorator are called when tests are collected, while inside fixture they are call when tests are run.
Also use a larger state for the density matrix tests. `basis(1)` can be both `ket`, `bra` and `operator`... 
- Use `full` in distribution. When using a `fock_dm` instead of a `ket2dm(basis(...))`, `data_as` returned a `dia_matrix` which did not works in that case.

Small tests fixes

---

qutip/tests/core/test_gates.py

A test did not start with `test` and was skipped...

Activate miss-named test

---

qutip/solver/correlation.py

We import `scipy.fftpack`, but never used it.
In the past, importing it caused some issue (#1915).
closes #1915

Remove unused fft import

---

qutip/core/data/dense.pyx

We use int32 per default for the shape of the data.
When allocating memory ourselves for dense layer, the number of elements was computed using these int32 an could overflow:
allocating a `2**16 x 2**16` matrix would allocate a matrix of `0` elements and segfault instead of raising a MemoryError.
fix #2575

Check for integer overflow when computing Dense data size

---

.github/workflows/build.yml
.github/workflows/tests.yml

From a discussion on discord between Jake and Simon.
We are no longer building wheels for mac with intel chips.
`macos-13`: intel chips
`macos-latest`: apple silicon
Changed the tests so both mac versions are covered.

Build wheels for mac with intel chips

---

qutip/simdiag.py

The ordering of the return type is (eigenvalues, eigenvectors), not the other way round.

Update docstring of simdiag

---

doc/changes/2555.bugfix
qutip/core/dimensions.py
qutip/tests/core/test_dimensions.py

Fix a bug in the function to get the permutation to get a tensor from a uneven super operators.  (`[ [[2, 3], [4, 5, 6]], [...]]`) 
Add tests for `to_tensor_rep` and `from_tensor_rep`.
fix #2555

Fix bug in permutation of tensor reprensentation

---

qutip/core/data/eigen.py
qutip/simdiag.py
qutip/tests/test_simdiag.py

The check for degenerate eigenvalues in sparse eigen function had a bug where close eigenvalues could create overlapping sets of degenerate values. For example, with the set of eigenvalues `[1-1e-14, 1, 1+1e14]` and the tolerance `1.5e-14`. The first and last are not detected as degenerate but they both are with the middle one. 
I made multiple small fixes:
- Exclude values that are already in a set.
- Improve default tolerance value, `tol=0` is machine precision, but the real error seems proportional to the size.
- Have simdiag use the dense eigen solver per default. The sparse eigen solver is not made to get all states
fix #2584

fix simdiag degen eigenval issue

---

qutip/core/data/eigen.py
qutip/tests/test_animation.py
qutip/tests/test_visualization.py
qutip/wigner.py

- Sparse eigen solver fails with empty matrix input. We can easily detect them.
- `sph_harm` is replaced by `sph_harm_y`. It has reversed input. `sph_harm` will exist until 1.17, but is a lot slower for some reason.
- `toeplitz` will change behavior for multi dimension arrays. Our inputs where vector in a 2D array, just removing the extra dimensions remove the warning.

Support for scipy1.15 

---

.github/workflows/tests.yml

I merged #2589 as it was approved not remembering why it was on hold...
`coveralls` does not support python 3.13, so even if the tests passes, the action fail.
Here I skip the step that upload the coverage for python 3.13 tests.

Only use coveralls for selected cases

---

doc/changes/2595.bugfix
qutip/core/qobj.py
qutip/tests/test_enr_state_operator.py

Use the class dims instead of the list dims in `eigenstates` so it support ENR.
fix #2595

ENR dimensions work with eigenstates

---

CITATION.bib
qutip/cite.py

`qutip.cite()` now lists only the current paper, which is the proper citation.  The old citations of versions 1 and 2 are left in `CITATION.bib` for historical interest.
I took the liberty of tweaking Paul's name to match how he usually puts himself on IBM papers (I think there's another "P Nation").
None.

Update citation commands to latest paper

---

doc/development/ideas.rst

Add missing Google Summer of Code wiki links to the ideas page.

Add links to Google Summer of Code wiki notes for 2023 and 2024.

---

doc/changes/2604.feature
qutip/about.py
qutip/tests/test_about.py

Adds information on installed QuTiP family packages (e.g. qutip-qip) to `qutip.about()` using an improved version of my suggestion in #1870.
Each family package that wishes to be included in the about information should:
* Register a `qutip.family` entry point that points to a module.
* Add a `version` function to the module that returns a tuple of `(package_name, version_string)`.
In future the `qutip.family` entry point might contain additional functions or attributes.
See https://github.com/qutip/qutip-qip/pull/261 for an example entry point implementation in qutip-qip.
- #1870 for a first implementation of these ideas.
**Example qubit.about() output**
```
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP …
```

Add installed family package information to qutip.about()

---

doc/changes/2606.bugfix
qutip/settings.py

The mkl finding routine only supports a fixed set of `sys.platform` values. This PR adds support for the "emscripten" platform (used by, e.g., try-qutip).
The error was reported by the emscripten-forge package builder for qutip in https://github.com/emscripten-forge/recipes/pull/1475. The build log is at https://github.com/emscripten-forge/recipes/actions/runs/12423612434/job/34687415066?pr=1475 and the relevant portion is:
```
│ │ │         elif plat in ['linux2', 'linux']:
│ │ │             ext = ".so"
│ │ │         else:
│ │ │ >           raise Exception('Unknown platfrom.')
│ │ │ E           Exception: Unknown platfrom.
│ │ │ /lib/python3.11/site-packages/qutip/settings.py:98: Exception
```
- …

Update mkl finding to support the 'emscripten' sys.platform.

---

qutip/core/data/csr.pyx
qutip/tests/core/data/test_convert.py

Conversion from csr to dense keeps all non strictly `0` entries.
This could cause strange result: `oper.expm().to("csr")` would not round, but `oper.expm(dtype="csr")` would.
With this change, the `auto_tidyup` options is used to round off small values.
The default for `auto_tidyup_atol` is `1e-14` to 0.

Apply tidyup options in `csr.from_dense`

---

qutip/core/data/eigen.py
qutip/core/qobj.py
qutip/tests/core/test_eigen.py
qutip/tests/core/test_eigenstates.py

The sparse eigen solver got more finicky since it was updated with last scipy version.
It makes our tests randomly fails quite often:
https://github.com/qutip/qutip/actions/runs/13191102536/job/36824098439?pr=2628
https://github.com/qutip/qutip/actions/runs/13169799701/job/36757919548?pr=2626
https://github.com/qutip/qutip/actions/runs/13151403307/job/36699388137#step:7:14687
We use it wrong as it was never meant to be used to compute all eigen values / vector as once.
We call scipy sparse solver twice and stitch the result together but it's not perfect (#1998).
This change the tests so we use the sparse solver mostly for a limited number of eigen states and make it clean in the docstring.
Also remove `eigs_csr` from the dispatched function. It can be still be used with …

Use less the sparse eigen solver

---

doc/apidoc/solver.rst
doc/guide/dynamics/dynamics-monte.rst
doc/requirements.txt
doc/rtd-environment.yml
qutip/solver/multitrajresult.py

Trying to help someone with mc output, I saw that the McResult apidoc was not great.
It list the parameters needed to create one, but not the output the user has access to:
https://qutip.readthedocs.io/en/latest/apidoc/solver.html#qutip.solver.multitrajresult.McResult
Listing the inherited member is better, but some of the output (`collapse`, `runs_trace`, ...) are attributes.
We also have half public method such as `add` and `add_processor` that are not useful for users.
I rewrote (cut pasted) the docstring to focus on attributes useful for the user and only added specific methods.
I also added `mpmath` to the doc requirement file since I needed it to build the documentation.

Improve McResult apidoc

---

doc/changes/2634.bugfix
qutip/core/tensor.py

Allow `expand_operator()` to work with `np.int`'s as targets, e.g. in `expand_operator(op, dims, np.ravel_multi_index(...))`.
Currently this would raise `"targets should be an integer or a list of integer"`.

allow np.int as targets in expand_operator

---

doc/apidoc/quantumobject.rst
doc/changes/2628.feature
doc/guide/dynamics/dynamics-bloch-redfield.rst
qutip/core/_brtensor.pyx
qutip/core/_brtools.pyx
qutip/core/blochredfield.py
qutip/core/environment.py
qutip/solver/brmesolve.py
qutip/tests/core/test_brtools.py
qutip/tests/solver/test_brmesolve.py

- Add support for `FermionicEnvironment` in Bloch `brmesolve`, `BRSolver` and `bloch_redfield_tensor`.
- Any environment are valid spectra for the above function.
- Add a new function: `brcrossterm`, compute cross term in equation (6) of our [guide](https://qutip.readthedocs.io/en/latest/guide/dynamics/dynamics-bloch-redfield.html).
- Improve documentation for the `br_dtype` parameter in `bloch_redfield_tensor`.
- Fix the equations in the documentation.
An example of fermion environment in the guide could be good.

Add support for FermionicEnvironment in Bloch RedFieldTensor.

---

.github/workflows/tests.yml

In our tests, installing matplotlib upgrade the version of numpy, but we want to test support of older version of numpy.
By adding a flag to install pre numpy 2 matplotlib version with tests using numpy 1 solve the issue.

Install older mpl when using numpy 1

---

.github/workflows/tests.yml
setup.cfg

loky 3.5.0, released last week, has a bug on python 3.10, see joblib/loky#444
It will hopefully be fixed soon, but it breaks some tests until then.
I exclude only that exact version for now, expecting 3.5.1 to work.
For the tests, I did not add branching on python version for simplicity. 
If a bugfix release does not fix the issue, I will make a follow up PR.

Skip loky version

---

qutip/core/dimensions.py

I just came across this in `dimensions.py`. The current code looks definitely wrong. In the docstring it says
```Space([2, 3, 4]).remove(1) == Space([2, 4])```
but currently
``Space([2, 3, 4]).remove(1)``
gives an error because the argument is not a list, and
``Space([2, 3, 4]).remove([1])``
gives an error as well.
I am not sure if this is even used anywhere, but I have tried to fix it.

Bugfix dimensions.Compound.remove

---

qutip/about.py

In older version of python `importlib`'s `metadata` must be imported directly.

Safer metadata import for older python

---

qutip/core/cy/qobjevo.pyx
qutip/tests/core/test_qobjevo.py

There is a bug in `QobjEvo.dag` and `QobjEvo.trans`, where the shape was not updated, only the dims and data.
The Qobj created when calling the function would have the right shape, so it was missed in the tests.

Update shape in qobjevo dag/trans

---

doc/changes/2669.bugfix
qutip/core/data/properties.pyx
qutip/tests/core/data/test_properties.py

Fix a bug in `isequal_dia` for case where the number of diagonals doesn't match.
Fix #2669

Fix isequal_dia for unequal number of diags

---

.github/workflows/tests.yml
doc/changes/2643.misc
qutip/core/expect.py
qutip/solver/integrator/explicit_rk.pyx
qutip/solver/integrator/qutip_integrator.py
qutip/solver/integrator/scipy_integrator.py
qutip/solver/mcsolve.py
qutip/solver/nm_mcsolve.py
qutip/solver/result.py
qutip/tests/solver/test_results.py

Benchmarks for QuantumToolbox showed that the difference between us and them was particularly bad for `mcsolve`.
After some looking around, the `adams` method is bad with quantum jumps. It's an ODE method that remembers previous steps and accelerate. Being reset at each jumps is slow when there are a lot of them. Using runge-kutta methods (`vern7`, `dop853`, ...) are therefore more appropriate for mcsolve and I changed the default.
I also checked code that took more time than expected:
- I removed extra copies of the state.
- `np.cumsum` used to look at which jump happen took as much time as a ODE step. Pure python is faster.
- Comparing list format dims is slow.
Overall, mcsolve is 20% faster with the same method, 3x with the change of method for the benchmark used for …

Optimize solvers

---

doc/changes/2677.doc
qutip/solver/sesolve.py

Fix small typo in docstring for `sesolve`.
N/A

Fix small typo in sesolve.py

---

doc/changes/2678.bugfix
qutip/bloch.py
qutip/tests/test_bloch.py

Before #2445, it was unwanted but possible to plot a state as a point on the Bloch sphere using a color as a RGB or RGBA tuple. This PR makes it possible again and also possible now when plotting as a vector. It also makes possible to specify a color as a string for all the states.

Enable again to plot states with RGBA tuple color on the Bloch sphere

---

.github/workflows/tests.yml
doc/installation.rst

We are including the MPI tests in only one of the test runs. I am changing that to be the one with the latest python and numpy (which it was always supposed to be, but it didn't get updated when python 3.13 came out). I am also changing openmpi, which was pinned to `<5` due to dependency issues, to the latest version.
This gets rid of some warning messages, and it seems to fix the problem with the test timing out. I still do not know exactly what caused that problem, but I am fine if things are working with the latest openmpi / mpi4py versions.

Update openmpi version used in tests

---

qutip/core/data/csr.pyx
qutip/tests/core/data/test_csr.py

For scipy version >= 1.14, we are accidentally calling `object.__init__` instead of `scipy.sparse._data._data_matrix.__init__` on CSR matrices created in the data layer.
Fixes #2690

Bugfix: ensure CSR matrices are initialized correctly

---

qutip/tests/core/test_eigen.py

Some eigen tests can randomly fail.
Trying it locally, `test_FewState` would fail 0.3% of the time.

Make sparse eigen test xfail in know risky cases

---

doc/changes/2696.feature
qutip/core/energy_restricted.py
qutip/tests/test_enr_state_operator.py

**Checklist**
The purpose of these changes is to have partial trace and tensor support in ENR space. I have only implemented these for Qobj's with CSR backing. As part of this, I made functions to calculate the number of states in an ENR space and to convert between state labels and indexes. Previously, this could only be done by fully enumerating all the states. If the state space is large, this can be a substantial speed-up. 
I have set these functions (`enr_nstates`, `enr_state2idx`, and `enr_idx2state`) to be cached, which I'm not sure is ok as I …

partial trace and tensor product for energy-restricted space

---

doc/changes/2700.misc
qutip/core/data/convert.pyx
qutip/core/data/matmul.pyx
qutip/core/data/project.pyx
qutip/tests/core/data/test_mathematics.py
qutip/tests/core/data/test_operators.py
qutip/tests/solver/test_stochastic.py

We made it so `|ket><bra|` return a sparse when appropriate, but `basis(10, 2).proj()` would still return a dense matrix...
This update `proj` to match the matmul behavior and add a test.
Ideally, this should be the dispatcher that can choose the appropriate output type so we don't have to do the same in qutip-jax etc.

Creating operator from dense ket.proj return CSR when appropriate

---

.github/workflows/build_documentation.yml
.github/workflows/tests.yml

Github action have a `concurrency` clause that control limit the number of job in a group that can run at once.
In a PR late stage, it is not unusual to make a lot of small commit in quick succession (pep8, towncrier, merge suggestions...).
In these case, usually only the latest run is useful.
This `concurrency` will cancel previous jobs and start the latest one quicker if waiting for resources. 
It's set to not cancel jobs in the master branch, but will force them to run one at a time.

Add concurrency limit to action

---

.github/workflows/tests.yml
doc/changes/2711.misc
qutip/core/data/expm.py
qutip/tests/core/data/test_dia.py
setup.cfg

Update for scipy 1.16.
2 changes broke our tests:
- Faster dia operations: it does no longer clean the `0` after the operation. So `(dia - dia).nnz` is no longer 0 even if all values are zero. `==` raise a warning so `not any(dia != dia)` it is...
- New `sqrtm`, it raise a warning when the matrix is singular. I just filtered the warnings in the tests, expecting the result to still be right most of the time. But we should see it fail if the result it wrong.

Add support for scipy 1.16

---

qutip/core/data/dispatch.pyx
qutip/core/options.py
qutip/tests/core/data/conftest.py
qutip/tests/core/data/test_dispatch.py

- Add `Dispatcher.register` a decorator for adding specialization.
- Add random generator input in random operator generators. 
Not used here, but can be used to make the mathematics test reproductive.
- Add error message when settings `default_dtype_scope` without `default_dtype`.
- Fix `_group_specialisation` repr using removed group name.

Pluging utilities

---

qutip/solver/integrator/qutip_integrator.py
qutip/solver/solver_base.py

In 5.2, we made it easier to get the right data type for operator by ensuring operators created from ket are sparse:
`basis(n) @ basis(n).dag()` and `basis(n).proj()` now return sparse matrix. 
Before it would default to dense, which would surprise users and slow down their simulation.
But, sparse density matrix as state in solvers has the same negative impact on computation time...
All our integrators converted the state to dense, but stochastic integrators did not...
I set it so `_prepare_state` in the solver does the conversion to dense (not the Dense class, but any dense format of any sub project).
fix #2733

Force dense state in solver

---

qutip/settings.py

As @pmenczel found, `numpy.__config__` is mostly empty (all private) for recent numpy version.
Instead `numpy.show_config` can return a dict instead of printing and it has the needed information . (new with numpy 1.26)
Also, numpy and scipy can uses different blas libraries.
Updated `_blas_info` to read from `scipy.show_config` when available. It's used to detect the implementation of the eigen solvers, so the scipy inplementation is better.
Update `_find_mkl` to look at the blas/lapack implementation used by scipy, numpy then anaconda default location.

Better mkl finding for recent numpy
